import type { WidgetCatalog, WidgetFamily } from "../types";

export const WIDGET_FAMILY_LABELS: Record<WidgetFamily, string> = {
  "time": "Time",
  "timers": "Timers",
  "calendar": "Calendar",
  "weather": "Weather",
  "media": "Media",
  "system": "System",
  "utilities": "Utilities",
  "social": "Social",
  "people": "People",
  "finance": "Finance",
  "analytics": "Analytics"
};

export const WIDGET_FAMILIES = Object.keys(WIDGET_FAMILY_LABELS) as WidgetFamily[];

export const widgetCatalog = {
  "clock-digital": { id: "clock-digital", family: "time", size: "WP", title: "Digital Clock" },
  "date-badge": { id: "date-badge", family: "calendar", size: "S", title: "Date" },
  "clock-world": { id: "clock-world", family: "time", size: "W", title: "World Clock" },
  "timer-countdown": { id: "timer-countdown", family: "timers", size: "WP", title: "Countdown Timer" },
  "task-list": { id: "task-list", family: "utilities", size: "W", title: "Tasks" },
  "agenda-today": { id: "agenda-today", family: "calendar", size: "S", title: "Today's Agenda" },
  "weather-now": { id: "weather-now", family: "weather", size: "S", title: "Weather Now" },
  "weather-hourly": { id: "weather-hourly", family: "weather", size: "WP", title: "Hourly Forecast" },
  "now-playing": { id: "now-playing", family: "media", size: "WP", title: "Now Playing" },
  "audio-eq": { id: "audio-eq", family: "media", size: "SP", title: "Audio EQ" },
  "inbox-count": { id: "inbox-count", family: "people", size: "S", title: "Inbox" },
  "contacts-row": { id: "contacts-row", family: "people", size: "WP", title: "Contacts" },
  "cpu-graph": { id: "cpu-graph", family: "system", size: "W", title: "CPU Load" },
  "ring-gauge": { id: "ring-gauge", family: "system", size: "S", title: "System Ring" },
  "quick-toggles": { id: "quick-toggles", family: "system", size: "WP", title: "Quick Toggles" },
  "net-throughput": { id: "net-throughput", family: "system", size: "WP", title: "Network" },
  "watchlist": { id: "watchlist", family: "finance", size: "W", title: "Watchlist" },
  "revenue-card": { id: "revenue-card", family: "finance", size: "WP", title: "Revenue" },
  "dot-heatmap": { id: "dot-heatmap", family: "analytics", size: "WP", title: "Activity" },
  "clock-analog": { id: "clock-analog", family: "time", size: "S", title: "Analog Clock" },
  "clock-flip": { id: "clock-flip", family: "time", size: "W", title: "Flip Clock" },
  "sun-arc": { id: "sun-arc", family: "time", size: "W", title: "Sun Arc" },
  "date-card": { id: "date-card", family: "time", size: "S", title: "Date" },
  "time-combo": { id: "time-combo", family: "time", size: "WP", title: "Date, Time & Temperature" },
  "stopwatch": { id: "stopwatch", family: "timers", size: "WP", title: "Stopwatch" },
  "focus-session": { id: "focus-session", family: "timers", size: "W", title: "Focus Session" },
  "voice-memo": { id: "voice-memo", family: "timers", size: "WP", title: "Voice Memo" },
  "week-strip": { id: "week-strip", family: "calendar", size: "W", title: "Week strip" },
  "calendar-month": { id: "calendar-month", family: "calendar", size: "W", title: "Month grid" },
  "next-event": { id: "next-event", family: "calendar", size: "L", title: "Next event" },
  "ticket-card": { id: "ticket-card", family: "calendar", size: "WP", title: "Ticket card" },
  "weather-days": { id: "weather-days", family: "weather", size: "W", title: "3-Day Forecast" },
  "wind-compass": { id: "wind-compass", family: "weather", size: "S", title: "Wind Compass" },
  "precip-now": { id: "precip-now", family: "weather", size: "S", title: "Precipitation" },
  "weather-full": { id: "weather-full", family: "weather", size: "WP", title: "Weather Summary" },
  "reaction-tray": { id: "reaction-tray", family: "media", size: "W", title: "Reactions" },
  "device-audio": { id: "device-audio", family: "media", size: "W", title: "Output Devices" },
  "file-search": { id: "file-search", family: "utilities", size: "WP", title: "File Search" },
  "web-search": { id: "web-search", family: "utilities", size: "WP", title: "Web Search" },
  "palette": { id: "palette", family: "utilities", size: "S", title: "Palette" },
  "social-count": { id: "social-count", family: "social", size: "W", title: "Social count" },
  "contact-card": { id: "contact-card", family: "people", size: "S", title: "Contact card" },
  "ticker-spark": { id: "ticker-spark", family: "finance", size: "W", title: "Ticker — AAPL" },
  "currency-convert": { id: "currency-convert", family: "finance", size: "W", title: "Currency converter" },
  "visitors-spark": { id: "visitors-spark", family: "analytics", size: "WP", title: "Visitors · last 7d" },
  "usage-meter": { id: "usage-meter", family: "analytics", size: "WP", title: "Usage · tokens" },
  "orders-summary": { id: "orders-summary", family: "analytics", size: "WP", title: "Orders · Northline Supply" },
} satisfies WidgetCatalog;

export const widgetDescriptors = Object.values(widgetCatalog);
