/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-init-imports.ts
 * Source: each feature's init.ts (glob: frontend/slices/[slug]/init.ts)
 *
 * To update, add init.ts to your feature and run: pnpm run sync:all
 */

// Feature init files (auto-discovered)
import "@/frontend/slices/accounting/init"
import "@/frontend/slices/ai-admin/init"
import "@/frontend/slices/ai-agents/init"
import "@/frontend/slices/ai-chat/init"
import "@/frontend/slices/ai-router/init"
import "@/frontend/slices/ai-studio/init"
import "@/frontend/slices/ai/init"
import "@/frontend/slices/analytics/init"
import "@/frontend/slices/approvals/init"
import "@/frontend/slices/asset-management/init"
import "@/frontend/slices/audit-log/init"
import "@/frontend/slices/bi/init"
import "@/frontend/slices/blog/init"
import "@/frontend/slices/branch-health-scoring/init"
import "@/frontend/slices/calendar/init"
import "@/frontend/slices/cash-flow-forecast/init"
import "@/frontend/slices/cms-lite/init"
import "@/frontend/slices/command-menu/init"
import "@/frontend/slices/communications/init"
import "@/frontend/slices/contacts/init"
import "@/frontend/slices/content/init"
import "@/frontend/slices/create-your-mcp/init"
import "@/frontend/slices/crm/init"
import "@/frontend/slices/customer-loyalty/init"
import "@/frontend/slices/daily-closing/init"
import "@/frontend/slices/damage-reports/init"
import "@/frontend/slices/database/init"
import "@/frontend/slices/datasets/init"
import "@/frontend/slices/documents/init"
import "@/frontend/slices/example/init"
import "@/frontend/slices/forms/init"
import "@/frontend/slices/guest-booking/init"
import "@/frontend/slices/hr/init"
import "@/frontend/slices/i18n-translate/init"
import "@/frontend/slices/import-export/init"
import "@/frontend/slices/integrations/init"
import "@/frontend/slices/inventory/init"
import "@/frontend/slices/knowledge/init"
import "@/frontend/slices/kpi-thresholds/init"
import "@/frontend/slices/maintenance-scheduling/init"
import "@/frontend/slices/marketing/init"
import "@/frontend/slices/notifications/init"
import "@/frontend/slices/notion/init"
import "@/frontend/slices/operational-checklist/init"
import "@/frontend/slices/overview/init"
import "@/frontend/slices/owner-analytics/init"
import "@/frontend/slices/owner-transfers/init"
import "@/frontend/slices/petty-cash/init"
import "@/frontend/slices/platform-admin/init"
import "@/frontend/slices/pos/init"
import "@/frontend/slices/projects/init"
import "@/frontend/slices/qsr-allowances/init"
import "@/frontend/slices/qsr-dashboard/init"
import "@/frontend/slices/qsr-master-data/init"
import "@/frontend/slices/qsr-payables/init"
import "@/frontend/slices/qsr-petty-cash/init"
import "@/frontend/slices/qsr-product-changes/init"
import "@/frontend/slices/rate-limit/init"
import "@/frontend/slices/reports/init"
import "@/frontend/slices/sales/init"
import "@/frontend/slices/staff-operations/init"
import "@/frontend/slices/status/init"
import "@/frontend/slices/store/init"
import "@/frontend/slices/support/init"
import "@/frontend/slices/tasks/init"
import "@/frontend/slices/user-management/init"

// Non-feature init files
import "@/frontend/shared/foundation/utils/notifications/init"

if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  console.log("[FeatureSettings] Auto-discovered 66 feature init files")
}

