<script lang="ts">
 import{onMount,setContext,untrack}from"svelte";import"../appshell/appshell.css";import"./lib/bootstrap";
 import MacShell from"./shells/MacShell.svelte";import WindowsShell from"./shells/WindowsShell.svelte";import MobileShell from"./shells/MobileShell.svelte";import AppLauncher from"./components/AppLauncher.svelte";import CommandPalette from"./components/CommandPalette.svelte";import Notifications from"./components/Notifications.svelte";import InspectorPanel from"./components/InspectorPanel.svelte";import SystemSheets from"./components/SystemSheets.svelte";import Slot from"./components/Slot.svelte";
 import{APPSHELL_CONTEXT}from"./lib/context";import{configureWindowTitle,startWindowTitleSync}from"../appshell/lib/window-title";import{hydrateBoot,serialize}from"../appshell/lib/store-persist";import{setInspectorOpen,setSpotlightOpen,shellStore,toggleInspector,toggleSpotlight}from"../appshell/lib/store";import{setClipboardOpen,startClipboardCapture}from"../appshell/lib/clipboard-core";import{openQuickLook,toggleQuickLook}from"../appshell/lib/quick-look-core";import{setShortcutHelpOpen}from"../appshell/lib/shortcuts-core";import{getChromeKit,tokenPackToVars}from"../appshell/registry/chrome-kit";import{resolveShellId,setShell,shellPrefsStore,surfaceOf,type ShellPrefs}from"../appshell/registry/shell-core";import type{ShellManifest}from"./types";
 let{manifest}:{manifest:ShellManifest}=$props();setContext(APPSHELL_CONTEXT,untrack(()=>({apps:manifest.apps,manifest})));let vw=$state(1200),pv=$state(0),prefs=$state<ShellPrefs>(shellPrefsStore.get());let surface=$derived(vw<768?"mobile":"desktop");let shellId=$derived(resolveShellId(surface,prefs));
 onMount(()=>{const applyTokens=()=>{const id=resolveShellId(window.innerWidth<768?"mobile":"desktop",shellPrefsStore.get());const kit=getChromeKit(id);document.documentElement.dataset.shell=id;if(kit){const vars=tokenPackToVars(kit.tokens??{},kit.motion);for(const[key,value]of Object.entries(vars))document.documentElement.style.setProperty(key,value)}};vw=window.innerWidth;applyTokens();const resize=()=>{vw=window.innerWidth;applyTokens()};window.addEventListener("resize",resize);const unsubPrefs=shellPrefsStore.subscribe(()=>{prefs=shellPrefsStore.get();pv++;applyTokens()});if(manifest.shell)setShell(surfaceOf(manifest.shell),manifest.shell);configureWindowTitle({suffix:manifest.brand.name,enabled:manifest.titleSync!==false});if(manifest.titleSync!==false)startWindowTitleSync();const key=manifest.persistKey??"appshell:layout";try{const raw=localStorage.getItem(key);if(raw)hydrateBoot(JSON.parse(raw),new Set(manifest.apps.filter(a=>a.multi).map(a=>a.id)))}catch{}let timer=0;const unsubStore=shellStore.subscribe(()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(serialize()))}catch{}},120)});const stopClip=startClipboardCapture();const keydown=(e:KeyboardEvent)=>{const typing=(e.target as HTMLElement|null)?.matches?.("input,textarea,[contenteditable=true]");if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"&&!typing){e.preventDefault();toggleSpotlight()}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="i"&&!typing){e.preventDefault();toggleInspector()}else if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==="v"&&!typing){e.preventDefault();setClipboardOpen(true)}else if((e.metaKey||e.ctrlKey)&&e.key==="/"&&!typing){e.preventDefault();setShortcutHelpOpen(true)}else if(e.key===" "&&!typing){toggleQuickLook()}};window.addEventListener("keydown",keydown);return()=>{unsubPrefs();unsubStore();stopClip();window.removeEventListener("resize",resize);window.removeEventListener("keydown",keydown);window.clearTimeout(timer)}});
</script>
<div class={`appshell shell-${shellId}`} data-slice="appshell-svelte"><div class="wallpaper"></div>{#if shellId==="macos"}<MacShell apps={manifest.apps} brand={manifest.brand}/>{:else if shellId==="windows"}<WindowsShell apps={manifest.apps}/>{:else if shellId==="android"}<MobileShell apps={manifest.apps} kind="android"/>{:else}<MobileShell apps={manifest.apps} kind="ios"/>{/if}<AppLauncher apps={manifest.apps}/><CommandPalette apps={manifest.apps}/><Notifications/><InspectorPanel/><SystemSheets/><Slot region="overlay"/><Slot region="notifications"/></div>
<style>.appshell{position:relative;height:100dvh;min-height:32rem;width:100%;overflow:hidden;background:#0b1020;color:white;font-family:var(--font-os,system-ui)}.wallpaper{position:absolute;inset:0;background:radial-gradient(circle at 18% 15%,#3b82f688,transparent 34%),radial-gradient(circle at 78% 20%,#a855f766,transparent 30%),linear-gradient(145deg,#172033,#070b14 65%,#101829)}.shell-windows .wallpaper{background:radial-gradient(circle at 48% 45%,#76b9edaa,transparent 48%),linear-gradient(145deg,#0c4a6e,#0f172a)}.shell-ios .wallpaper,.shell-android .wallpaper{background:#18243a}</style>
