// AUTO-GENERATED by packages/cli/scripts/gen-preview-registry.mjs — do not edit.
// One dynamic import per slug keeps every preview in its own client chunk.
import type { SlicePreviewModule } from "@/shared/preview/types";

export const PREVIEW_REGISTRY: Record<string, () => Promise<{ default: SlicePreviewModule }>> = {
  "full-width-toggle": () => import("@/features/full-width-toggle/preview"),
  "markdown": () => import("@/features/markdown/preview"),
  "notion-database": () => import("@/features/notion-database/preview"),
};

export type PreviewSlug = keyof typeof PREVIEW_REGISTRY;
