// Tier-3 slice registry — single source of truth.
//
// Was duplicated by the deprecated lib/content/features.ts (same 8 concepts,
// drifted slugs). Consolidated 2026-05-09: features.ts deleted, slices.ts
// now carries the rich docsUrl/install/exampleCode/usedBy fields too.
//
// Consumed by: npm tarball manifest, /slices catalog page, Bundle Builder UI,
// MCP `rr_list_slices`/`rr_get_slice`, sidebar Slices group.

import type { SliceCategory } from "@/lib/shared/features/defineFeature";
import type { PreviewView } from "@/lib/preview-presets";

export type SlicePeer = { slug: string; range: string; reason?: string };
export type SliceEnvVar = {
  name: string;
  scope: "convex" | "next-public" | "server";
  required?: boolean;
  description?: string;
};

/**
 * Slice shape — what the slice ships at a glance.
 *
 *   "ui"        — pure frontend; no Convex tables/actions. Pop in & style.
 *                 Lives under frontend/slices/* but `convexPaths` is empty.
 *                 Examples: motion primitives, command palette, layout shell.
 *   "backend"   — pure Convex (schema + queries/actions). No UI shipped.
 *                 Lives under convex/features/*. `slicePath` may be empty.
 *                 Examples: vector-search index helper, ai-router proxy.
 *   "full"      — both frontend + Convex, full vertical feature.
 *                 Examples: doku-payment, midtrans-payment, mdx-blog.
 *
 * Builder UI filters by kind so users picking "just a UI primitive" don't
 * see env-var requirements for backend-coupled slices.
 */
export type SliceKind = "ui" | "backend" | "full";

/** Compat status per (template × slice) or (slice × slice) pairing. */
export type CompatStatus = "native" | "recommended" | "warn" | "incompatible";
export type SliceCompatEntry = { status: CompatStatus; note?: string };

/**
 * Compat declared per slice. Moved here from `lib/build/compat.ts` matrix
 * (Phase 4 of REFACTOR-PLAN.md, 2026-05-12). Single source of truth.
 *
 *   templates  — per-template compatibility. Missing = silent compatible.
 *   conflicts  — slices this one is MUTUALLY EXCLUSIVE with.
 *   enhances   — slices this one pairs well with (informational).
 */
export type SliceCompat = {
  templates?: Record<string, SliceCompatEntry>;
  conflicts?: string[];
  enhances?: string[];
};

export type SliceEntry = {
  slug: string;
  title: string;
  category: SliceCategory;
  /** Default "full" so old entries without `kind` keep working — but every
   *  new entry SHOULD set this explicitly. */
  kind?: SliceKind;
  version: string;
  description: string;
  source: string;
  slicePath: string;
  convexPaths: string[];
  npm?: string[];
  shadcn?: string[];
  env?: SliceEnvVar[];
  peers?: SlicePeer[];
  providers?: string[];
  tags?: string[];
  /** Upstream docs (vendor or platform). */
  docsUrl?: string;
  /** Plain copy-paste install line — kept for the catalog page snippet. */
  install?: string;
  /** Inline example code shown on the slice detail page. */
  exampleCode?: string;
  /** Templates that ship with this slice pre-wired. */
  usedBy?: string[];
  /** Brief recipe for an AI agent installing the slice manually. */
  agentRecipe?: string;
  /** Live preview route, e.g. "/preview/slices/full-width-toggle". When set,
   *  the slice detail page renders a PreviewFrame iframing this URL. */
  previewPath?: string;
  /** Optional second preview surface — admin/operator side of a full slice.
   *  When set together with `previewPath`, slice detail page shows a
   *  Public / Admin tab pair like the website-template detail page. */
  adminPreviewPath?: string;
  /** When both preview paths exist, which surface opens first. Defaults to "public". */
  defaultSurface?: "public" | "admin";
  /** Initial preview viewport on the detail page. Defaults to desktop.
   *  Pick "mobile" for mobile-first UIs (e.g. comments thread, forms). */
  defaultView?: PreviewView;
  /** Initial preview zoom (1.0 = real size). Override when the slice
   *  is dense and benefits from being scaled down inside the iframe. */
  defaultZoom?: number;
  /** Compatibility: per-template status + slice peer/conflict declarations.
   *  Was hand-curated in lib/build/compat.ts pre-Phase-4. */
  compat?: SliceCompat;
};

export const slices: SliceEntry[] = [
  {
    slug: "convex-auth",
    title: "Convex Auth — Email Magic Link",
    category: "auth",
    kind: "backend",
    version: "0.1.0",
    description: "@convex-dev/auth with email magic link via Resend. Self-hosted Convex friendly. Hard mandate per kitab CLAUDE.md (no Clerk).",
    source: "rahmanef63/resource-site",
    docsUrl: "https://labs.convex.dev/auth",
    install: "npm i @convex-dev/auth @auth/core resend",
    slicePath: "frontend/slices/convex-auth",
    convexPaths: ["convex/features/auth"],
    npm: ["@convex-dev/auth@^0.0.84", "@auth/core@^0.37.0", "resend@^4.0.0"],
    shadcn: ["button", "card", "input", "label", "dropdown-menu", "avatar"],
    env: [
      { name: "AUTH_RESEND_KEY", scope: "convex" },
      { name: "JWT_PRIVATE_KEY", scope: "convex" },
      { name: "JWKS", scope: "convex" },
      { name: "SITE_URL", scope: "convex" },
    ],
    peers: [],
    tags: ["auth", "convex", "magic-link", "no-clerk"],
    usedBy: ["personal-brand-os", "wirausaha-os", "konsultan-os"],
    agentRecipe: "Run `rr add convex-auth`. Then create convex/auth.ts using the kitab pattern (Resend provider). Set env via `npx convex env set` for self-hosted.",
    previewPath: "/preview/slices/convex-auth",
    defaultView: "mobile",
    defaultZoom: 1,
    compat: {
      templates: {
        "personal-brand-os": { status: "native" },
        "agency-studio-os": { status: "native" },
        "konsultan-os": { status: "native" },
        "wirausaha-os": { status: "native" },
        "kreator-studio-os": { status: "native" },
        "riset-kit": { status: "native" },
        "saas-marketing-os": { status: "recommended" },
        "cms-public-storefront": { status: "recommended" },
      },
      enhances: ["midtrans-payment", "doku-payment", "resend-newsletter", "ai-router"],
    },
    exampleCode: `// convex/auth.ts
import { convexAuth } from "@convex-dev/auth/server";
import Resend from "@convex-dev/auth/providers/Resend";

export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
  providers: [Resend({ from: "auth@yourdomain.com" })],
});

// app/proxy.ts (Next 16 — NOT middleware.ts)
import { convexAuthNextjsMiddleware } from "@convex-dev/auth/nextjs/server";
export default convexAuthNextjsMiddleware();`,
  },
  {
    slug: "doku-payment",
    title: "DOKU — Indonesia Payment",
    category: "payment",
    kind: "full",
    version: "0.1.0",
    description: "Pembayaran lokal Indonesia via DOKU — Checkout (hosted) + Direct (VA / QRIS / e-Wallet / PayLater / Minimarket / Kartu). HMAC-signed REST + signature-verified webhook + idempotent retries. Sibling slice to midtrans-payment dengan paymentOrders schema yang dishare.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://sandbox.doku.com/integration",
    install: "",
    slicePath: "frontend/slices/doku-payment",
    convexPaths: ["convex/features/payment"],
    npm: [],
    shadcn: ["card", "button", "dialog", "input", "label", "select", "badge", "skeleton"],
    env: [
      { name: "DOKU_CLIENT_ID", scope: "convex", required: true },
      { name: "DOKU_SECRET_KEY", scope: "convex", required: true },
      { name: "DOKU_IS_PRODUCTION", scope: "convex" },
      { name: "DOKU_NOTIFY_PATH", scope: "convex" },
    ],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Order ownership requires authenticated user." }],
    providers: ["doku"],
    tags: ["payment", "doku", "indonesia", "qris", "virtual-account", "ewallet", "checkout"],
    usedBy: ["personal-brand-os", "konsultan-os", "wirausaha-os", "kreator-studio-os", "riset-kit", "agency-studio-os", "cms-public-storefront"],
    agentRecipe: "DOKU dual-mode: Checkout (hosted, all channels) atau Direct (single channel, returns VA/QRIS/deeplink). Webhook di /webhooks/doku verify HMAC-SHA256 (canonical: Client-Id + Request-Id + Request-Timestamp + Request-Target + Digest). Idempotency by request_id index. Server-only — no NEXT_PUBLIC_*. Sandbox default (api-sandbox.doku.com); flip DOKU_IS_PRODUCTION=true for live.",
    previewPath: "/preview/slices/doku-payment",
    defaultView: "mobile",
    defaultZoom: 1,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended", note: "Pairs with services/digital-product flow. Mount checkout-page at /checkout." },
        "agency-studio-os": { status: "recommended", note: "Invoice payment via VA — Direct mode fits B2B flow." },
        "saas-marketing-os": { status: "warn", note: "SaaS biasanya butuh recurring billing — DOKU best untuk one-time. Pakai Stripe untuk subscription." },
        "konsultan-os": { status: "recommended", note: "Pembayaran sesi konsultasi — Checkout mode untuk paket bundling." },
        "wirausaha-os": { status: "recommended", note: "Multi-channel commerce — VA + QRIS + e-Wallet untuk customer pilih sendiri." },
        "kreator-studio-os": { status: "recommended", note: "Digital product / coaching purchase — Checkout mode redirect to DOKU page." },
        "riset-kit": { status: "recommended", note: "Paid research bundle — one-time Checkout flow." },
        "cms-public-storefront": { status: "recommended", note: "Cart checkout — Direct mode untuk control UI atau Checkout untuk quick wins." },
      },
      conflicts: ["midtrans-payment", "stripe-payment"],
      enhances: ["convex-auth", "ai-router"],
    },
  },
  {
    slug: "midtrans-payment",
    title: "Midtrans — Indonesia Payment",
    category: "payment",
    kind: "full",
    version: "0.1.0",
    description: "Pembayaran lokal Indonesia via Midtrans Snap (BCA, Mandiri, BRI, e-wallet GoPay/OVO/Dana, QRIS). Webhook untuk konfirmasi. Provider-isolated under components/providers/midtrans + actions/midtrans so Doku/Stripe land as siblings.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://docs.midtrans.com",
    install: "npm i midtrans-client",
    slicePath: "frontend/slices/midtrans-payment",
    convexPaths: ["convex/features/payment"],
    npm: ["midtrans-client@^1.4.2"],
    shadcn: ["card", "button", "dialog", "input", "label"],
    env: [
      { name: "MIDTRANS_SERVER_KEY", scope: "convex", required: true },
      { name: "MIDTRANS_CLIENT_KEY", scope: "next-public", required: true },
      { name: "MIDTRANS_IS_PRODUCTION", scope: "convex" },
    ],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Order ownership requires authenticated user." }],
    providers: ["midtrans"],
    tags: ["payment", "midtrans", "indonesia", "qris", "snap"],
    usedBy: ["wirausaha-os", "konsultan-os", "kreator-studio-os"],
    agentRecipe: "Midtrans Snap untuk pembayaran instant. Webhook ke Convex HTTP action /api/midtrans-callback untuk update order status. Ingat: PPN 11% sudah included di amount, jangan double-count.",
    previewPath: "/preview/slices/midtrans-payment",
    defaultView: "mobile",
    defaultZoom: 1,
    compat: {
      templates: {
        "personal-brand-os": { status: "warn", note: "Personal-brand has no checkout slice; you'll add one manually." },
        "agency-studio-os": { status: "warn", note: "B2B template; payment slice not included." },
        "saas-marketing-os": { status: "warn", note: "SaaS biasanya butuh recurring billing — Midtrans Snap untuk one-time only." },
        "konsultan-os": { status: "recommended", note: "Alternative Indonesian gateway." },
        "wirausaha-os": { status: "recommended", note: "Alternative Indonesian gateway." },
        "kreator-studio-os": { status: "recommended", note: "Alternative Indonesian gateway." },
        "cms-public-storefront": { status: "recommended", note: "Alternative Indonesian gateway." },
      },
      conflicts: ["stripe-payment", "doku-payment"],
      enhances: ["convex-auth"],
    },
  },
  {
    slug: "resend-newsletter",
    title: "Resend — Transactional & Newsletter",
    category: "email",
    kind: "backend",
    version: "0.1.0",
    description: "Transactional email + newsletter blast via Resend. Double opt-in flow + audience segmentation. Magic-link delivery for Convex Auth.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://resend.com/docs",
    install: "npm i resend react-email @react-email/components",
    slicePath: "frontend/slices/resend-newsletter",
    convexPaths: ["convex/features/newsletter"],
    npm: ["resend@^4.0.0"],
    shadcn: ["button", "card", "input", "label", "textarea"],
    env: [
      { name: "RESEND_API_KEY", scope: "convex", required: true },
      { name: "RESEND_FROM", scope: "convex", required: true },
    ],
    peers: [],
    tags: ["email", "newsletter", "resend"],
    usedBy: ["personal-brand-os", "kreator-studio-os", "wirausaha-os"],
    agentRecipe: "Use Resend Audiences API for newsletter — store subscriber emails in Convex too for segmentation. Double opt-in: subscriber.create with status 'pending' → click link → status 'confirmed'.",
    previewPath: "/preview/slices/resend-newsletter",
    defaultView: "tablet",
    defaultZoom: 0.8,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended", note: "Newsletter slice already calls Resend Audiences API." },
        "agency-studio-os": { status: "recommended", note: "Leads → broadcast wired through admin." },
        "saas-marketing-os": { status: "recommended" },
      },
      enhances: ["mdx-blog"],
    },
  },
  // ─────────────────────────────────────────────────────────────
  // AI features (consolidated 2026-05-16 — was 7 entries, merged into
  // 3 consumer archetypes + 1 admin + 1 backend).
  //
  // Ordering follows the user mental model:
  //   1. ai-chat   — talk to the model (chatbot / copilot / search)
  //   2. ai-studio — make stuff with the model (generation canvas)
  //   3. ai-agents — let the model work asynchronously (workers)
  //   4. ai-admin  — operator console (instructions / skills / tools /
  //                  agents / providers / budgets / audit)
  //   5. ai-router — backend infra (provider proxy + cost guard)
  //
  // Tag taxonomy:
  //   "ai"            — umbrella (every entry)
  //   "ai:<arch>"     — chat | studio | agents | admin | backend
  //   capability tags — streaming, multimodal, tool-calls, rag,
  //                     agent-mode, citations, branching, history,
  //                     image-gen, voice
  // ─────────────────────────────────────────────────────────────
  {
    slug: "ai-chat",
    title: "AI Chat — Workbench / Sidebar / Search",
    category: "ai",
    kind: "full",
    version: "0.1.0",
    description: "One conversational AI feature, three render modes. Same Convex backend (threads + streaming + tool calls + RAG), pick the surface via prop:\n\n  • workbench — Claude.ai / ChatGPT three-column page (default)\n  • sidebar — collapsible copilot panel inside another CRUD app\n  • search — single-question + answer + citations (Perplexity)\n\nUse cases:\n  – Customer-support chatbot embedded in your marketing site\n  – Developer copilot in your PR/docs admin\n  – Knowledge-base search over your blog + docs corpus\n  – Internal AI assistant in your dashboard\n\nWhat it ships: multi-provider (Anthropic / OpenAI / Google / Mistral / Ollama), multimodal (text + image + PDF + audio), typed tool calls with inline inspector, agent mode (plan→execute→reflect), branching threads, RAG citations, resumable streams, usage telemetry. Public surface = consumer chat; admin surface = persona, fallback, guardrails per-bot.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://sdk.vercel.ai/docs",
    install: "npm i ai @ai-sdk/anthropic @ai-sdk/openai",
    slicePath: "frontend/slices/ai-chat",
    convexPaths: ["convex/features/ai-chat"],
    npm: ["ai@^4.0.0", "@ai-sdk/anthropic@^0.0.50", "@ai-sdk/openai@^0.0.60"],
    shadcn: ["button", "card", "badge", "avatar", "scroll-area", "select", "separator", "slider", "switch", "textarea", "tabs", "command", "sheet"],
    env: [
      { name: "ANTHROPIC_API_KEY", scope: "convex", required: false },
      { name: "OPENAI_API_KEY", scope: "convex", required: false },
      { name: "GOOGLE_GENERATIVE_AI_API_KEY", scope: "convex", required: false },
    ],
    peers: [
      { slug: "convex-auth", range: "^0.1", reason: "Thread ownership requires authenticated user." },
      { slug: "ai-router", range: "^0.1", reason: "Routes provider calls through tiered proxy." },
      { slug: "ai-admin", range: "^0.1", reason: "Reads instructions / skills / tools / models from ai-admin registry." },
      { slug: "vector-search", range: "^0.1", reason: "Optional — RAG / search modes pull workspace embeddings." },
    ],
    tags: ["ai", "ai:chat", "streaming", "multimodal", "tool-calls", "agent-mode", "rag", "citations", "branching", "history"],
    usedBy: [],
    agentRecipe: "Run `npx rr add ai-chat`. Pick `mode=\"workbench\" | \"sidebar\" | \"search\"` on `<AIChat />` (or use the convenience exports `<AIChatWorkbench />`, `<AIChatSidebar />`, `<AIChatSearch />`). Same backend tables + streaming action for all three.",
    previewPath: "/preview/slices/ai-chat",
    adminPreviewPath: "/preview/slices/ai-chat/admin",
    defaultSurface: "public",
    defaultView: "desktop",
    defaultZoom: 0.55,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended", note: "Customer support (workbench) + author copilot (sidebar)." },
        "kreator-studio-os": { status: "recommended", note: "Default content-ideation surface (workbench mode)." },
        "saas-marketing-os": { status: "warn", note: "Only the search mode is a natural fit for marketing sites." },
      },
      enhances: ["ai-router", "ai-admin", "vector-search"],
    },
  },
  {
    slug: "ai-studio",
    title: "AI Studio — Generation Canvas",
    category: "ai",
    kind: "full",
    version: "0.1.0",
    description: "AI is the primary UI — single big prompt input → live-streaming output → variation grid → version tree. Suno / Midjourney / Lovable / v0 pattern. Output kinds: text, code, image, audio (configurable per template).\n\nUse cases:\n  – AI image generation product (creative output)\n  – AI logo / banner / social-post studio\n  – AI code-snippet generator (component scaffolder)\n  – AI music / voiceover producer\n  – AI blog-draft factory (text)\n\nFeatures: prompt history, branch + compare outputs, like + favorite, share-to-link, templates from ai-admin.",
    source: "rahmanef63/resource-site",
    install: "",
    slicePath: "frontend/slices/ai-studio",
    convexPaths: ["convex/features/ai-studio"],
    npm: ["ai@^4.0.0"],
    shadcn: ["button", "card", "badge", "textarea", "tabs", "tooltip", "scroll-area", "select"],
    env: [],
    peers: [
      { slug: "convex-auth", range: "^0.1", reason: "Generation history per user." },
      { slug: "ai-router", range: "^0.1", reason: "All generation calls flow through router." },
      { slug: "ai-admin", range: "^0.1", reason: "Templates + few-shot library + moderation rules live in ai-admin." },
    ],
    tags: ["ai", "ai:studio", "generation", "streaming", "history", "branching", "image-gen"],
    usedBy: [],
    agentRecipe: "Run `npx rr add ai-studio`. Mount `<GeneratorCanvas />` at /. Use case: prompt → output IS the entire product. Wire your output renderer (text/image/code/audio) via the OutputSlot adapter. Templates loaded from ai-admin.studio.templates.",
    previewPath: "/preview/slices/ai-studio",
    adminPreviewPath: "/preview/slices/ai-studio/admin",
    defaultSurface: "public",
    defaultView: "desktop",
    defaultZoom: 0.6,
    compat: {
      templates: {
        "kreator-studio-os": { status: "recommended", note: "Native fit for creator-output products." },
        "personal-brand-os": { status: "recommended", note: "Post-draft factory + cover-image studio." },
      },
      enhances: ["ai-router", "ai-admin"],
    },
  },
  {
    slug: "ai-agents",
    title: "AI Agents — Autonomous Workers",
    category: "ai",
    kind: "full",
    version: "0.1.0",
    description: "Background AI workers. Define an agent (skill × model × tools × max-iter), trigger it on-demand or on a cron schedule, watch the step-by-step trace as it runs. Devin / Replit-Agent / Manus pattern.\n\nUse cases:\n  – Nightly audit-bp on the codebase (PR-reviewer style)\n  – Weekly SEO crawl + content suggestions\n  – Auto-moderate comment queue\n  – Scheduled data ingestion + summarization\n  – Long-form research task with multi-source citations\n\nFeatures: queue + live trace, per-step retry policy, hard cost cap, shareable trace URLs, full audit-log integration.",
    source: "rahmanef63/resource-site",
    install: "",
    slicePath: "frontend/slices/ai-agents",
    convexPaths: ["convex/features/ai-agents"],
    npm: ["ai@^4.0.0"],
    shadcn: ["button", "card", "badge", "table", "tabs", "scroll-area", "progress"],
    env: [],
    peers: [
      { slug: "convex-auth", range: "^0.1", reason: "Per-user agent run ownership." },
      { slug: "ai-router", range: "^0.1", reason: "Step calls flow through router." },
      { slug: "ai-admin", range: "^0.1", reason: "Agent definitions live in ai-admin → Agents." },
      { slug: "audit-log", range: "^0.1", reason: "Every step logged." },
    ],
    tags: ["ai", "ai:agents", "agent-mode", "tool-calls", "async", "queue", "traces"],
    usedBy: [],
    agentRecipe: "Run `npx rr add ai-agents`. Mount `<RunnerDashboard />` at /agents. Trigger runs via `runAgent({agentSlug, input, scheduleAt?})`. Cron scheduler via Convex cron — wire if you need scheduled runs. Agent definitions managed in ai-admin.",
    previewPath: "/preview/slices/ai-agents",
    adminPreviewPath: "/preview/slices/ai-agents/admin",
    defaultSurface: "public",
    defaultView: "desktop",
    defaultZoom: 0.6,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended", note: "Schedule SEO audits, comment moderation, weekly digests." },
        "kreator-studio-os": { status: "recommended", note: "Background batch generations." },
      },
      enhances: ["ai-router", "ai-admin", "audit-log"],
    },
  },
  {
    slug: "ai-admin",
    title: "AI Admin — Console (Instructions · Skills · Tools · Agents · Providers)",
    category: "ai",
    kind: "full",
    version: "0.2.0",
    description: "Central operator console for the whole AI stack. Every other ai-* feature reads its registries from here. Tabs ordered to match the build-flow:\n\n  1. Providers   — register Anthropic / OpenAI / Google / Mistral / Ollama (API keys AES-encrypted at rest)\n  2. Models      — per-provider catalog (capabilities, context window, pricing)\n  3. Instructions — custom system-prompt library (Claude Projects-style)\n  4. Skills      — named instruction + model default + tool defaults (consumed by chat + studio)\n  5. Tools       — JSON-schema function specs + impl (http / convex / shell) + sandbox flag\n  6. Agents      — skill × model × tools × max-iter (consumed by ai-agents)\n  7. Budgets     — per-workspace cost caps + alerts + hard kill\n  8. Audit       — every AI call: actor / agent / tokens / cost / latency / outcome\n\nIncludes Create-Agent / Create-Skill / Create-Tool / Create-Instruction wizards.",
    source: "rahmanef63/resource-site",
    install: "",
    slicePath: "frontend/slices/ai-admin",
    convexPaths: ["convex/features/ai-admin"],
    npm: [],
    shadcn: ["card", "button", "badge", "tabs", "table", "dialog", "input", "label", "select", "textarea", "switch", "command"],
    env: [{ name: "AI_ADMIN_ENCRYPTION_KEY", scope: "convex", required: true, description: "Encrypts stored provider API keys at rest." }],
    peers: [
      { slug: "convex-auth", range: "^0.1", reason: "requireAdmin gate." },
      { slug: "rbac-roles", range: "^0.1", reason: "Section gated by ai.* permissions (manage_providers, manage_skills, etc)." },
      { slug: "admin-panel", range: "^0.1", reason: "Lives as a registered admin section." },
      { slug: "audit-log", range: "^0.1", reason: "Every config change + AI call routes through audit-log." },
    ],
    tags: ["ai", "ai:admin", "instructions", "skills", "tools", "agents", "providers", "models", "budgets", "audit"],
    usedBy: [],
    agentRecipe: "Run `npx rr add ai-admin`. Adds an `AI` section to the admin-panel ADMIN_SECTIONS registry. Sub-tabs ordered to match build-flow: Providers → Models → Instructions → Skills → Tools → Agents → Budgets → Audit. Includes Create-* wizards for instructions / skills / tools / agents. API keys AES-encrypted via AI_ADMIN_ENCRYPTION_KEY env. The instruction / skill / tool / agent registries are SSOTs consumed by every ai-* consumer slice (chat + studio + agents).",
    previewPath: "/preview/slices/ai-admin",
    defaultView: "desktop",
    defaultZoom: 0.55,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended", note: "Mounts as admin section — owner manages all AI." },
        "kreator-studio-os": { status: "recommended" },
      },
      enhances: ["ai-chat", "ai-studio", "ai-agents", "ai-router", "audit-log"],
    },
  },
  {
    slug: "ai-router",
    title: "AI Router — Backend Provider Proxy",
    category: "ai",
    kind: "backend",
    version: "0.1.0",
    description: "Backend infrastructure (no UI). Single proxy that every other ai-* feature calls. Tier-routed — nano (Haiku) for classification, mid (Sonnet) for chat, flagship (Opus) for deep reasoning. Per-call usage log + cost guard. Works with direct provider keys or OpenRouter umbrella.\n\nNot something you mount — installed automatically as a peer when you add ai-chat / ai-studio / ai-agents.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://sdk.vercel.ai/docs",
    install: "npm i ai @openrouter/ai-sdk-provider",
    slicePath: "frontend/slices/ai-router",
    convexPaths: ["convex/features/ai"],
    npm: ["ai@^4.0.0", "@openrouter/ai-sdk-provider@^0.0.5"],
    shadcn: ["button"],
    env: [{ name: "OPENROUTER_API_KEY", scope: "convex", required: true }],
    peers: [],
    tags: ["ai", "ai:backend", "tier-routing", "cost-guard"],
    usedBy: ["personal-brand-os"],
    agentRecipe: "Wrap every AI call through ai-router. Tiers: nano = quick classification (spam-flag, headline-suggest), mid = chat / draft, flagship = methodology-review / deep-think. Token usage logs to ai_usage table for the cost dashboard.",
    previewPath: "/preview/slices/ai-router",
    defaultView: "desktop",
    defaultZoom: 0.7,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended" },
        "kreator-studio-os": { status: "recommended" },
        "saas-marketing-os": { status: "warn", note: "Only needed if site uses ai-chat search mode." },
      },
      enhances: ["ai-chat", "ai-studio", "ai-agents", "ai-admin"],
    },
  },
  {
    slug: "vector-search",
    title: "Convex Vector Search",
    category: "search",
    kind: "full",
    version: "0.1.0",
    description: "Embeddings-based search via Convex's built-in vector index. Embed via OpenAI text-embedding-3-small (1536-dim), query via vectorIndex().",
    source: "rahmanef63/resource-site",
    docsUrl: "https://docs.convex.dev/database/vector-search",
    install: "npm i openai",
    slicePath: "frontend/slices/vector-search",
    convexPaths: ["convex/features/search"],
    npm: ["@convex-dev/vector-search@^0.0.5"],
    shadcn: ["card", "input"],
    env: [{ name: "OPENAI_API_KEY", scope: "convex", required: true }],
    peers: [],
    tags: ["search", "vector", "embeddings", "convex", "rag"],
    usedBy: ["personal-brand-os", "riset-kit"],
    agentRecipe: "Add embedding field + vectorIndex per searchable table. Re-embed on upsert via Convex action. Cache embeddings — don't re-call OpenAI on every read.",
    previewPath: "/preview/slices/vector-search",
    defaultView: "tablet",
    defaultZoom: 0.8,
    compat: {
      templates: {
        "riset-kit": { status: "native", note: "Research kit pakai embedding search untuk konten." },
      },
    },
  },
  {
    slug: "mdx-blog",
    title: "MDX Blog",
    category: "content",
    kind: "ui",
    version: "0.2.0",
    description: "Markdown-with-JSX untuk blog post. File-based MDX content collection. Portable defineMdxBlog(opts) factory dengan 4 config props (basePath, contentDir, labels.list, nav) — defaults preserve legacy /blog + content/blog. Auto-generate ToC, reading-time, syntax highlight, plus embed React components inline.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://github.com/hashicorp/next-mdx-remote",
    install: "npm i next-mdx-remote rehype-pretty-code remark-gfm reading-time",
    slicePath: "frontend/slices/mdx-blog",
    convexPaths: [],
    npm: ["@next/mdx@^16.0.0", "gray-matter@^4.0.3", "rehype-pretty-code@^0.14.0"],
    shadcn: ["card"],
    env: [],
    peers: [],
    tags: ["content", "blog", "mdx", "static"],
    usedBy: ["personal-brand-os", "konsultan-os", "saas-marketing-os"],
    agentRecipe: "Store post body sebagai markdown di content/blog/*.mdx. Render dengan MDXRemote di [slug]/page.tsx. Auto-extract headings ke ToC via remark plugin custom.",
    previewPath: "/preview/slices/mdx-blog",
    defaultView: "tablet",
    defaultZoom: 0.8,
    compat: {
      templates: {
        "saas-marketing-os": { status: "native", note: "Blog + changelog slices both render MDX." },
        "personal-brand-os": { status: "recommended", note: "Blog slice expects MDX bodies in Convex posts table." },
        "konsultan-os": { status: "recommended", note: "Konten ahli sebagai SEO funnel." },
        "agency-studio-os": { status: "warn", note: "Agency template ships no blog slice — bring your own route." },
      },
    },
  },
  {
    slug: "cal-com-booking",
    title: "Cal.com Booking",
    category: "data",
    kind: "full",
    version: "0.1.0",
    description: "Embedded Cal.com booking widget + webhook receiver to mirror bookings into Convex.",
    source: "rahmanef63/resource-site",
    docsUrl: "https://cal.com/docs/integrations/web-app/embed",
    install: "npm i @calcom/embed-react",
    slicePath: "frontend/slices/cal-com-booking",
    convexPaths: ["convex/features/bookings"],
    npm: ["@calcom/embed-react@^1.5.0"],
    shadcn: ["card"],
    env: [
      { name: "NEXT_PUBLIC_CALCOM_USERNAME", scope: "next-public", required: true },
      { name: "CALCOM_WEBHOOK_SECRET", scope: "convex", required: true },
    ],
    peers: [],
    tags: ["data", "scheduling", "cal-com", "bookings"],
    usedBy: ["personal-brand-os", "konsultan-os"],
    agentRecipe: "Embed Cal.com via @calcom/embed-react di halaman services. Configure webhook di Cal.com dashboard → POST ke /api/cal-webhook → upsert booking di Convex.",
    previewPath: "/preview/slices/cal-com-booking",
    defaultView: "mobile",
    defaultZoom: 1,
    compat: {
      templates: {
        "personal-brand-os": { status: "recommended", note: "Services slice has a booking placeholder slot." },
        "agency-studio-os": { status: "recommended", note: "Project intake form pairs with Cal.com." },
        "saas-marketing-os": { status: "recommended", note: "Demo-request form can swap to Cal.com." },
        "konsultan-os": { status: "recommended", note: "Konsultasi booking wajib — Cal.com embed di services page." },
      },
    },
  },
  {
    slug: "full-width-toggle",
    title: "Full Width Toggle",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "Page-container width toggle (contained / wide / full). Per-device localStorage + cross-tab sync. Ships useFullWidth hook + FullWidthToggle button (icon/button/segment variants) + WidthContainer wrapper. Zero backend, zero env.",
    source: "rahmanef63/resource-site",
    docsUrl: "",
    install: "",
    slicePath: "frontend/slices/full-width-toggle",
    convexPaths: [],
    npm: [],
    shadcn: ["button"],
    env: [],
    peers: [],
    tags: ["ui", "layout", "preference", "localstorage", "dashboard"],
    usedBy: ["personal-brand-os", "agency-studio-os", "konsultan-os", "wirausaha-os", "kreator-studio-os", "saas-marketing-os", "riset-kit", "cms-public-storefront"],
    agentRecipe: "Drop <WidthContainer> around page content, <FullWidthToggle variant='icon' /> in topbar. Variant 'segment' best for settings page. Hook useFullWidth() returns [mode, setMode, cycle]. SSR-safe — defaults to 'contained' until hydrate.",
    previewPath: "/preview/slices/full-width-toggle",
    defaultView: "desktop",
    defaultZoom: 0.6,
  },
  {
    slug: "command-menu",
    title: "Command Menu",
    category: "ui",
    kind: "ui",
    version: "0.2.0",
    description: "Renderless ⌘K command palette + generic search modal. Consumer supplies CommandGroup[] + onSelect + label bag; slice owns dialog chrome, ⌘K hotkey, MRU history. Pulled UP from notion-page-clone's command-palette renderless surface (Wave N+3.7) — Nosion adapters dropped at the kitab boundary.",
    source: "notion-page-clone (consumerVersion 0.3.0) + earlier superspace facade",
    docsUrl: "https://cmdk.paco.me",
    install: "npm i cmdk",
    slicePath: "frontend/slices/command-menu",
    convexPaths: [],
    npm: ["cmdk@^1.0.0"],
    shadcn: ["command", "dialog"],
    env: [],
    peers: [],
    tags: ["ui", "palette", "cmd-k", "navigation", "keyboard", "search"],
    usedBy: ["personal-brand-os", "agency-studio-os", "konsultan-os", "wirausaha-os", "kreator-studio-os", "saas-marketing-os", "riset-kit", "cms-public-storefront"],
    agentRecipe: "Wire <CommandPalette groups={...} onHistorySelect={...} labels={...} /> at the dashboard shell. Build groups from your feature registry; each item.onSelect handles navigation. Use <SearchModal bindings={{ pages, databases, recents, isLoading, onQueryChange, onSelectPage, onSelectDatabase }} /> for the search dialog — see slice README.md for adapter shapes.",
    previewPath: "/preview/slices/command-menu",
    defaultView: "mobile",
    defaultZoom: 1,
  },
  {
    slug: "motion-primitives",
    title: "Motion Primitives (8)",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "Eight ready-to-style motion components: marquee, kinetic-heading, magnetic, cursor-spotlight, stat-counter, reading-progress, grain, lightbox. Framer-Motion-powered, tree-shakeable. Facade slice — pulls from template-base/frontend/slices/motion-primitives.",
    source: "rahmanef.com",
    docsUrl: "",
    install: "npm i framer-motion",
    slicePath: "template-base/frontend/slices/motion-primitives",
    convexPaths: [],
    npm: ["framer-motion@^11.0.0"],
    shadcn: [],
    env: [],
    peers: [],
    tags: ["ui", "motion", "animation", "marquee", "framer-motion"],
    usedBy: ["personal-brand-os", "agency-studio-os", "kreator-studio-os", "saas-marketing-os"],
    agentRecipe: "Each primitive is independently importable from @/features/motion-primitives. Use marquee for logo strips, kinetic-heading for hero text, magnetic for CTA buttons, cursor-spotlight for hover-reveal panels, stat-counter for animated numbers, reading-progress for blog top bar, grain for film texture, lightbox for image gallery.",
    previewPath: "/preview/slices/motion-primitives",
    defaultView: "desktop",
    defaultZoom: 0.6,
  },
  {
    slug: "responsive-dialog",
    title: "Responsive Dialog (Sheet ↔ Modal)",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "ResponsiveDialog — auto-switches between bottom Sheet (mobile) and centered Dialog (desktop) at the md breakpoint. Same API as shadcn Dialog. Kitab forbids raw <dialog>; use this everywhere. Facade slice — pulls from template-base/frontend/slices/responsive-dialog.",
    source: "superspace",
    docsUrl: "",
    install: "",
    slicePath: "template-base/frontend/slices/responsive-dialog",
    convexPaths: [],
    npm: [],
    shadcn: ["dialog", "sheet"],
    env: [],
    peers: [],
    tags: ["ui", "dialog", "modal", "sheet", "responsive", "primitive"],
    usedBy: ["personal-brand-os", "agency-studio-os", "konsultan-os", "wirausaha-os", "kreator-studio-os", "saas-marketing-os", "riset-kit", "cms-public-storefront"],
    agentRecipe: "Drop-in for shadcn Dialog. Use <ResponsiveDialog><ResponsiveDialogTrigger>…</ResponsiveDialogTrigger><ResponsiveDialogContent>…</ResponsiveDialogContent></ResponsiveDialog>. On mobile renders as Sheet sliding from bottom; on desktop as centered Dialog. Threshold via useMediaQuery('(min-width: 768px)').",
    previewPath: "/preview/slices/responsive-dialog",
    defaultView: "tablet",
    defaultZoom: 0.85,
  },
  {
    slug: "dashboard-shell",
    title: "Dashboard Shell — Responsive",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "ResponsiveDashboardShell — desktop sidebar + topbar, mobile dock + sheet sidebar, breakpoint-aware. Ports superspace's layout/dashboard/{Desktop,Mobile,Responsive}DashboardShell + sidebar primary/secondary slots. Facade slice — pulls from template-base/frontend/slices/dashboard-shell.",
    source: "superspace",
    docsUrl: "",
    install: "",
    slicePath: "template-base/frontend/slices/dashboard-shell",
    convexPaths: [],
    npm: [],
    shadcn: ["sheet", "scroll-area", "separator", "tooltip"],
    env: [],
    peers: [{ slug: "full-width-toggle", range: "^0.1", reason: "Topbar surfaces the width toggle when this is mounted." }],
    tags: ["ui", "layout", "dashboard", "sidebar", "topbar", "responsive"],
    usedBy: ["personal-brand-os", "agency-studio-os", "konsultan-os", "wirausaha-os", "kreator-studio-os", "riset-kit", "cms-public-storefront"],
    agentRecipe: "Wraps app/(admin) routes. <ResponsiveDashboardShell sidebar={<AppSidebar />} topbar={<TopBar />}>{children}</ResponsiveDashboardShell>. Mobile: sidebar collapses to <Sheet>. Desktop: persistent sidebar + topbar. Embed FullWidthToggle in topbar for instant container resize.",
    previewPath: "/preview/slices/dashboard-shell",
    defaultView: "desktop",
    defaultZoom: 0.6,
  },
  {
    slug: "broadcast-channel-sync",
    title: "BroadcastChannel — Cross-tab Sync",
    category: "realtime",
    kind: "ui",
    version: "0.1.0",
    description: "Same-origin cross-tab + cross-iframe state sync via BroadcastChannel API. Tiny, no backend, no install.",
    source: "Web Platform — BroadcastChannel API",
    docsUrl: "https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API",
    install: "// no install — Web Platform API",
    slicePath: "frontend/slices/broadcast-channel-sync",
    convexPaths: [],
    npm: [],
    shadcn: [],
    env: [],
    peers: [],
    tags: ["realtime", "cross-tab", "broadcast-channel", "demo-pattern"],
    usedBy: ["personal-brand-os"],
    agentRecipe: "Use BroadcastChannel only for demo / cross-iframe state mirroring. Production data still goes through Convex realtime. Use the useBroadcastSync(channelName, initial) hook from @/features/broadcast-channel-sync.",
    previewPath: "/preview/slices/broadcast-channel-sync",
    defaultView: "tablet",
    defaultZoom: 0.8,
    compat: {
      templates: {
        "personal-brand-os": { status: "native", note: "Public ↔ Admin live sync wired in StoreProvider." },
        "agency-studio-os": { status: "warn", note: "Demo-only; not used by agency template by default." },
      },
    },
  },
  // ------------------------------------------------------------------
  // Promoted from recipes.ts (Phase 3 of docs/REFACTOR-PLAN.md, 2026-05-12).
  // All paths point to existing template-base content. Foundation slices —
  // depend on template-base/{shared,convex/lib} internals, slicePath rooted
  // at template-base/.
  // ------------------------------------------------------------------
  {
    slug: "rbac-roles",
    title: "RBAC — Tiered System Roles",
    category: "auth",
    kind: "backend",
    version: "0.1.0",
    description: "Workspace-scoped RBAC with 6 system roles (owner/admin/manager/staff/client/guest) and three tier presets — solo, influencer, organization. Env-based platform admin bypass via PLATFORM_ADMIN_EMAILS. checkPermission / requirePermission helpers, role seeding mutation, @convex-dev/auth aware (no Clerk).",
    source: "superspace",
    slicePath: "",
    convexPaths: ["template-base/convex/lib/rbac"],
    npm: [],
    shadcn: [],
    env: [{ name: "PLATFORM_ADMIN_EMAILS", scope: "convex", description: "Comma-separated emails granted cross-workspace admin." }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "RBAC checks the authed user identity." }],
    tags: ["rbac", "auth", "permissions", "roles", "workspaces"],
    usedBy: ["personal-brand-os", "konsultan-os", "wirausaha-os"],
    agentRecipe: "Three tier presets pick which system roles to seed: solo (owner+admin), influencer (+manager), organization (6 roles). Platform admin via env PLATFORM_ADMIN_EMAILS bypasses all checks. Resolution: platform admin → workspace owner → membership.additionalPermissions → role.permissions.",
    previewPath: "/preview/slices/rbac-roles",
    defaultView: "desktop",
    defaultZoom: 0.7,
  },
  {
    slug: "admin-panel",
    title: "Admin Panel — Unified Product Admin",
    category: "infra",
    kind: "full",
    version: "0.1.0",
    description: "17-section admin surface (events, funnels, attribution, users, A/B, flags, pricing, CMS, email, audit, ...) gated by RBAC. Auto-filters sidebar by tier (solo/influencer/organization) and user permissions. Single backend resolver (getMyAdminAccess) mirrors frontend gate so UI can never leak.",
    source: "superspace + spec",
    slicePath: "template-base/frontend/slices/admin-panel",
    convexPaths: ["template-base/convex/features/admin-panel"],
    npm: [],
    shadcn: ["card", "badge", "button"],
    env: [],
    peers: [{ slug: "rbac-roles", range: "^0.1", reason: "Admin sections require RBAC perms — must seed roles first." }],
    tags: ["admin", "owner", "platform", "rbac", "instrumentation", "panel"],
    usedBy: ["personal-brand-os"],
    agentRecipe: "Wrap pages with <AdminPage workspaceId tier>. AccessGate hides UI for non-admins, AdminShell renders 2-col layout with sidebar filtered by tier+perms. ADMIN_SECTIONS in config.ts is SSOT (17 entries). Personal-brand-os = tier 'solo' = owner sees everything.",
    previewPath: "/preview/slices/admin-panel",
    defaultView: "desktop",
    defaultZoom: 0.65,
  },
  {
    slug: "event-tracking",
    title: "Event Tracking — P0 Instrumentation",
    category: "data",
    kind: "full",
    version: "0.1.0",
    description: "Client SDK + Convex ingestion endpoint for structured product events. Auto-captures page_view/signup/login + UTM/referrer/first-touch attribution. Batched flush via requestIdleCallback. Targets <100ms p99 ingestion.",
    source: "spec + superspace analytics",
    slicePath: "template-base/frontend/slices/admin-panel/slices/events",
    convexPaths: ["template-base/convex/features/admin-panel", "template-base/convex/features/analytics"],
    npm: [],
    shadcn: [],
    env: [],
    peers: [{ slug: "admin-panel", range: "^0.1", reason: "Lives under admin slice events subfolder." }],
    tags: ["events", "analytics", "instrumentation", "attribution", "utm", "p0"],
    usedBy: ["personal-brand-os"],
    agentRecipe: "Writes to analyticsEvents table (no new schema). Anonymous page_view allowed pre-signup; other events require workspaceId. Session id per tab (sessionStorage), first-touch UTM in localStorage. Flush every ~500ms via requestIdleCallback. Cap retry queue at 500.",
    previewPath: "/preview/slices/event-tracking",
    defaultView: "desktop",
    defaultZoom: 0.7,
  },
  {
    slug: "theme-preset-switcher",
    title: "Theme Preset Switcher",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "Runtime theme swap (colors + fonts + shadows + tracking). OKLch CSS vars per preset. Persists to localStorage + Convex. Add a new preset by appending a CSS block in app/globals.css with [data-theme=\"<name>\"], then register in preset-groups.ts.",
    source: "rahmanef.com",
    slicePath: "template-base/frontend/shared/theme",
    convexPaths: [],
    npm: [],
    shadcn: [],
    env: [],
    peers: [],
    tags: ["theme", "presets", "oklch", "design-system"],
    usedBy: ["personal-brand-os", "konsultan-os", "wirausaha-os"],
    agentRecipe: "Import ThemePresetSwitcher from @/frontend/shared/ui/components/theme-preset-switcher and mount in the topbar. Presets live in theme-presets.ts; preset-groups.ts groups them for the picker UI.",
    previewPath: "/preview/slices/theme-preset-switcher",
    defaultView: "tablet",
    defaultZoom: 0.85,
  },
  {
    slug: "icon-picker",
    title: "Icon Picker",
    category: "ui",
    kind: "ui",
    version: "0.2.0",
    description: "Emoji + lucide icon picker with search, 10-color palette, Twemoji/native toggle, recents tracking. One string stores emoji OR lucide:Name OR with ?c=hex tint — backwards-compat with raw-emoji fields. Two variants: Popover (compact trigger) and Inline (full sheet/dialog use). Lifted 2026-05-16 from notion-page-clone — full implementation (19 files) including emoji-keywords search index, twemoji renderer, lucide-catalog, recents store, style-pref hook.",
    source: "notion-page-clone",
    slicePath: "frontend/slices/icon-picker",
    convexPaths: [],
    npm: [],
    shadcn: ["popover", "button", "input", "scroll-area", "tabs"],
    env: [],
    peers: [],
    tags: ["icon", "emoji", "lucide", "picker", "twemoji", "notion"],
    usedBy: ["personal-brand-os"],
    agentRecipe: "Run `npx rr add icon-picker`. parseIconValue() decodes; lucideValue()/withColor() build. Add 'icon: v.string()' to Convex table — no migration needed for existing emoji fields. <IconPicker> wraps any trigger (Popover); <IconPickerInline> for sheets/dialogs. <DynamicIcon> renders from parsed value.",
    previewPath: "/preview/slices/icon-picker",
    defaultView: "tablet",
    defaultZoom: 0.9,
  },
  {
    slug: "cta",
    title: "Call to Action",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "Brutalist call-to-action section — eyebrow label, serif headline, body, arrow CTA. Pair with CtaButton standalone for inline placements. Lifted 2026-05-16 from rahmanef.com; assumes Tailwind tracking-brutal / tracking-brutal-sm utilities OR drop them for the default tracking scale.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/cta",
    convexPaths: [],
    npm: ["lucide-react@^0.400.0"],
    shadcn: [],
    env: [],
    peers: [],
    tags: ["ui", "marketing", "cta", "section", "brutalist"],
    usedBy: [],
    agentRecipe: "Run `npx rr add cta`. <CtaView eyebrow title body href ctaLabel /> renders the full section; <CtaButton href label /> drops a standalone arrow button anywhere. Override tracking-brutal utilities in tailwind.config or swap for tracking-wide if your design system has no brutal preset.",
    previewPath: "/preview/slices/cta",
    defaultView: "desktop",
    defaultZoom: 0.85,
  },
  {
    slug: "hero",
    title: "Hero",
    category: "ui",
    kind: "ui",
    version: "0.1.0",
    description: "Editorial split-grid landing hero — eyebrow pill + large serif H1 + italic pull-quote + 1-2 button CTA row + right-column portrait card with optional caption. Fully props-driven (title/quote/ctas/image). Sanitized from rahmanef.com on 2026-05-16: SITE_CONFIG hardcode dropped, custom Heading/Section primitives replaced with raw semantic elements + stock Tailwind tracking-widest so the slice ships without consumer preset utilities.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/hero",
    convexPaths: [],
    npm: ["lucide-react@^0.400.0"],
    shadcn: [],
    env: [],
    peers: [],
    tags: ["ui", "hero", "marketing", "landing", "section", "editorial", "brutalist"],
    usedBy: [],
    agentRecipe: "Run `npx rr add hero`. <HeroView title eyebrow quote ctas image imageCaption /> — all props optional except title. Pass `image={undefined}` for text-only hero (auto-collapses to single 12-column row). Pairs visually with cta slice (same brutalist border + serif scale).",
    previewPath: "/preview/slices/hero",
    defaultView: "desktop",
    defaultZoom: 0.7,
  },
  {
    slug: "rate-limit",
    title: "Rate Limit",
    category: "infra",
    kind: "backend",
    version: "0.1.0",
    description: "Convex-backed per-key request counter. Atomic check-and-increment via `consume` mutation; expired rows pruned by `_pruneExpired` internalMutation wired to a 5-min cron. Replaces single-replica in-memory Map so multi-replica Next deployments share buckets. Caller chooses key namespace (csp:<ip>, mcp:<ip>, oauth_token:<ip>). Lifted 2026-05-16 from rahmanef.com.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/rate-limit",
    convexPaths: ["convex/features/rate-limit"],
    npm: [],
    shadcn: [],
    env: [],
    peers: [],
    tags: ["infra", "rate-limit", "convex", "backend", "throttle"],
    usedBy: [],
    agentRecipe: "Run `npx rr add rate-limit`. Compose `rateLimitTables` into root convex/schema.ts. Wire `internal.features.rate_limit.mutations._pruneExpired` into convex/crons.ts every 5 min. Call `api.features.rate_limit.mutations.consume({ key, limit, windowMs })` from server-side handlers — keep a fail-open wrapper so a Convex outage doesn't 503 the route.",
    previewPath: undefined,
  },
  {
    slug: "subscribers",
    title: "Subscribers",
    category: "email",
    kind: "backend",
    version: "0.1.0",
    description: "Newsletter list with honeypot + per-email rate-limit + token-based unsubscribe + admin remove. Public `subscribe` returns status strings (`created` / `already` / `resubscribed` / `honeypot`); admin `listAll` / `count` queries gated by `requireAdmin` (rr `_shared/auth`). Lifted 2026-05-16 from rahmanef.com; sanitized: token args dropped, sibling `analyticsEvents` insert removed — wrap subscribe in a consumer action if you want funnel telemetry.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/subscribers",
    convexPaths: ["convex/features/subscribers"],
    npm: [],
    shadcn: [],
    env: [{ name: "SUPER_ADMIN_EMAIL", scope: "convex", required: false, description: "Optional super-admin gate for admin queries." }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "requireAdmin uses getAuthUserId from @convex-dev/auth." }],
    tags: ["email", "newsletter", "subscribers", "convex", "backend"],
    usedBy: [],
    agentRecipe: "Run `npx rr add subscribers`. Compose `subscribersTables` into root convex/schema.ts. Public form posts `api.features.subscribers.mutations.subscribe({ email, source, website })` — `website` is the honeypot, leave it `\"\"` from the form. Render unsubscribe link `/unsubscribe?t=<token>` and call `unsubscribe({ token })`.",
    previewPath: undefined,
  },
  {
    slug: "testimonials",
    title: "Testimonials",
    category: "content",
    kind: "backend",
    version: "0.1.0",
    description: "Quote/name/role rotator backend. Public `listAll` + `get` (no auth — testimonials are public), admin CRUD via `requireAdmin`, internal `seed` for one-shot bootstrap. Indexed by `order` so carousel/grid keeps stable rotation. Lifted 2026-05-16 from rahmanef.com; token-based admin gate swapped for rr `_shared/auth`.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/testimonials",
    convexPaths: ["convex/features/testimonials"],
    npm: [],
    shadcn: [],
    env: [{ name: "SUPER_ADMIN_EMAIL", scope: "convex", required: false }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "requireAdmin uses getAuthUserId from @convex-dev/auth." }],
    tags: ["content", "testimonials", "convex", "backend", "marketing"],
    usedBy: [],
    agentRecipe: "Run `npx rr add testimonials`. Compose `testimonialsTables` into root schema. Bootstrap via `npx convex run internal.features.testimonials.mutations.seed '{\"items\":[{\"quote\":\"...\",\"name\":\"...\",\"role\":\"...\",\"order\":1}]}'`. Render with `useQuery(api.features.testimonials.queries.listAll)`.",
    previewPath: undefined,
  },
  {
    slug: "services",
    title: "Services",
    category: "content",
    kind: "backend",
    version: "0.1.0",
    description: "Service offerings backend — title + summary + deliverables array + sort order. Public read, admin CRUD, internal seed. Pairs with a frontend services grid/list (consumer-side). Lifted 2026-05-16 from rahmanef.com; token-based admin gate swapped for rr `_shared/auth`.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/services",
    convexPaths: ["convex/features/services"],
    npm: [],
    shadcn: [],
    env: [{ name: "SUPER_ADMIN_EMAIL", scope: "convex", required: false }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "requireAdmin uses getAuthUserId from @convex-dev/auth." }],
    tags: ["content", "services", "convex", "backend", "marketing", "agency"],
    usedBy: [],
    agentRecipe: "Run `npx rr add services`. Compose `servicesTables` into root schema. Use `useQuery(api.features.services.queries.listAll)` from a server component / route to render service cards. CRUD via admin UI calling `create` / `update` / `remove` after `requireAdmin` passes.",
    previewPath: undefined,
  },
  {
    slug: "socials",
    title: "Socials",
    category: "content",
    kind: "backend",
    version: "0.1.0",
    description: "Single source of truth for profile/social links. Powers JSON-LD `Person.sameAs` (Google entity graph), IndieWeb `<link rel=\"me\">` tags, and footer/contact/about UI surfaces. URL-deduped, ordered, `visible` / `featured` / `relMe` / `sameAs` flags. Lifted 2026-05-16 from rahmanef.com; token-based admin gate swapped, baked-in 14-platform rahmanef seed dropped — `seed` now takes items via args so each adopter ships their own list.",
    source: "rahmanef.com",
    slicePath: "frontend/slices/socials",
    convexPaths: ["convex/features/socials"],
    npm: [],
    shadcn: [],
    env: [{ name: "SUPER_ADMIN_EMAIL", scope: "convex", required: false }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "requireAdmin uses getAuthUserId from @convex-dev/auth." }],
    tags: ["content", "socials", "seo", "indieweb", "convex", "backend"],
    usedBy: [],
    agentRecipe: "Run `npx rr add socials`. Compose `socialsTables` into root schema. Bootstrap with `npx convex run internal.features.socials.mutations.seed '{\"items\":[{\"platform\":\"github\",\"url\":\"https://github.com/<you>\",\"order\":1,\"visible\":true,\"featured\":true,\"sameAs\":true,\"relMe\":true}]}'`. Wire `useQuery(api.features.socials.queries.listVisible)` into footer for entity-graph SEO.",
    previewPath: undefined,
  },
  {
    slug: "contact-form-resend",
    title: "Contact Form + Resend",
    category: "email",
    kind: "full",
    version: "0.1.0",
    description: "Contact form posting to Resend email API. Server Action + Zod input validation. Convex mutation for storage + Resend send.",
    source: "cescadesigns",
    slicePath: "template-base/frontend/slices/contact-form-resend",
    convexPaths: [],
    npm: ["resend@^4.0.0", "framer-motion@^11.0.0"],
    shadcn: ["card", "button", "input", "label", "textarea"],
    env: [{ name: "RESEND_API_KEY", scope: "convex", required: true }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Optional — anonymous submission works without auth." }],
    tags: ["form", "email", "resend", "convex"],
    usedBy: [],
    agentRecipe: "Wire contactMessages.send mutation in convex/. Server emails via Resend from form@yourdomain.com. Always validate inputs with Zod or v.* server-side. Anonymous allowed.",
    previewPath: "/preview/slices/contact-form-resend",
    defaultView: "mobile",
    defaultZoom: 1,
  },
  {
    slug: "admin",
    title: "Admin — Generic Shell",
    category: "infra",
    kind: "full",
    version: "0.2.0",
    description: "Per-instance admin landing scaffold + portable nav-from-registry factory. Consumer supplies a SliceRegistryAdapter (each slice declares its own admin.activity[]) + queryTable reader; the slice's buildAdminStats(opts) emits the { counts, unreadMessages, activity } shape Convex's admin.stats query returns. Pulled UP from rahmanef.com (Wave N+3.1, commit b542389) — domain literals dropped at the kitab boundary. Gated by requireAdmin on Convex side; superadmin email gate via SUPER_ADMIN_EMAIL env.",
    source: "rahmanef63/resource-site",
    slicePath: "frontend/slices/admin",
    convexPaths: ["convex/features/admin"],
    npm: [],
    shadcn: ["card", "button"],
    env: [{ name: "SUPER_ADMIN_EMAIL", scope: "convex", required: false }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "requireAdmin gate uses convex-auth user identity." }],
    tags: ["infra", "admin", "shell", "crud", "nav-from-registry"],
    usedBy: [],
    agentRecipe: "Run `rr add admin`. Wire <AdminPage labels={...} /> at /admin and call buildAdminStats({ sliceRegistry, queryTable }) inside convex/features/admin/queries.ts — sliceRegistry.entries flat-maps each feature's admin.activity[] declarations. Set SUPER_ADMIN_EMAIL via `npx convex env set` to lock down /admin to one address.",
    previewPath: "/preview/slices/admin",
    defaultView: "desktop",
    defaultZoom: 0.65,
  },
  {
    slug: "platform-admin",
    title: "Platform Admin — Multi-Tenant Control Plane",
    category: "infra",
    kind: "full",
    version: "0.1.0",
    description: "Multi-tenant SaaS control plane. Workspace lifecycle ops (list/delete/cascade), per-tenant tier presets (gates + quota), KPI dashboard grid. Consumer-domain bits injected via adapter props (tenantTablesAdapter / tierPresets / kpiSources). Contract-only scaffold; canonical implementation lands via /rr-send from superspace. See docs/contract-negotiations-2026-05-15.md §4.",
    source: "rahmanef63/resource-site",
    slicePath: "frontend/slices/platform-admin",
    convexPaths: ["convex/features/platform-admin"],
    npm: [],
    shadcn: [],
    env: [{ name: "PLATFORM_ADMIN_EMAILS", scope: "convex", required: true, description: "Comma-separated list of platform admin email addresses." }],
    peers: [
      { slug: "convex-auth", range: "^0.1", reason: "Actor identity for audit + tier-set ops." },
      { slug: "audit-log", range: "^0.2", reason: "padmin_audit table feeds through audit-log TenantAdapter." },
    ],
    tags: ["infra", "admin", "multi-tenant", "saas", "platform"],
    usedBy: [],
    agentRecipe: "Contract-only scaffold. Wait for superspace /rr-send platform-admin before adopting. Distinct from per-instance `admin` slug.",
    previewPath: "/preview/slices/platform-admin",
    defaultView: "desktop",
    defaultZoom: 0.7,
  },
  {
    slug: "audit-log",
    title: "Audit Log — Workspace Events",
    category: "infra",
    kind: "backend",
    version: "0.2.0",
    description: "Workspace-scoped audit event recorder. Canonical logAuditEvent helper for mutations + actions; supports entity tracking, before/after diff, IP/user-agent capture.",
    source: "rahmanef63/resource-site",
    slicePath: "frontend/slices/audit-log",
    convexPaths: ["convex/features/audit-log"],
    npm: [],
    shadcn: [],
    env: [],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Event actor resolved via authenticated user." }],
    tags: ["infra", "audit", "compliance", "logging"],
    usedBy: [],
    agentRecipe: "Run `rr add audit-log`. Import logAuditEvent from convex/_shared/auditLogger.ts and call inside every workspace-scoped mutation with { action, workspaceId, entityType, entityId, before?, after? }.",
    previewPath: "/preview/slices/audit-log",
    defaultView: "desktop",
    defaultZoom: 0.7,
  },
  {
    slug: "comments",
    title: "Comments — Threaded",
    category: "content",
    kind: "full",
    version: "0.2.0",
    description: "Polymorphic-target threaded comments. Consumer picks `TargetRef = { kind, id, subId? }` (e.g. page+block, blog+slug, task+id). Renderless <CommentsThread> + <CommentsAnchor> wrappers. useComments(bindings, opts) hook returns items + openCount + CRUD + forbiddenWords guard. Adapter pattern — see contract-negotiations §1.",
    source: "rahmanef63/resource-site",
    slicePath: "frontend/slices/comments",
    convexPaths: ["convex/features/comments"],
    npm: [],
    shadcn: ["button", "textarea", "avatar"],
    env: [],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Comment author identity from convex-auth." }],
    tags: ["content", "social", "comments", "threaded", "annotations"],
    usedBy: [],
    agentRecipe: "Run `rr add comments`. Wire Convex bindings ({ list, create, update, resolve, remove }) then use <CommentsThread target={{ kind, id, subId? }} bindings={bindings} forbiddenWords={[...]}>{render-prop}</CommentsThread> OR <CommentsAnchor target=... bindings=... pathMap={(t)=>...}>. v0.2.0 polymorphic — pick `kind` literal per host domain.",
    previewPath: "/preview/slices/comments",
    defaultView: "mobile",
    defaultZoom: 1,
  },
  {
    slug: "seo",
    title: "SEO — AI Metadata Generator",
    category: "content",
    kind: "full",
    version: "0.2.0",
    description: "Service slice for SEO metadata generation — Anthropic-backed action with per-user 24h cost guard + portable persona prop. No public route. Backend exposes generate + generateAndApply mutations gated by requireAdmin; consumers inject brand voice via the personaContext arg (or buildSeoSystemPrompt factory).",
    source: "rahmanef63/resource-site",
    slicePath: "frontend/slices/seo",
    convexPaths: ["convex/features/seo"],
    npm: [],
    shadcn: [],
    env: [{ name: "ANTHROPIC_API_KEY", scope: "server", required: true }],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Cost guard + requireAdmin gates use convex-auth user identity." }],
    tags: ["content", "seo", "ai", "anthropic", "metadata-generator"],
    usedBy: [],
    agentRecipe: "Run `rr add seo`. Call seo.generate from server actions or admin mutations with `personaContext` describing your brand voice (or rely on the generic default). Cost guard rate-limits per-user within 24h via callsInWindow query.",
    previewPath: "/preview/slices/seo",
    defaultView: "tablet",
    defaultZoom: 0.8,
  },
  {
    slug: "document-checklist",
    title: "Document Checklist — Job-Search Doc Tracker",
    category: "content",
    kind: "full",
    version: "0.1.0",
    description: "Track required job-search documents (CV, KTP, ijazah, etc.) with country-scoped seed templates and per-user completion state. Ships an Indonesian default checklist. Toggle completed + notes + expiry per item.",
    source: "rahmanef63/CareerPack",
    slicePath: "frontend/slices/document-checklist",
    convexPaths: ["convex/features/document-checklist"],
    npm: ["lucide-react"],
    shadcn: ["badge", "button", "card", "dialog", "label", "popover", "calendar", "progress", "scroll-area", "skeleton", "tabs", "textarea"],
    env: [],
    peers: [{ slug: "convex-auth", range: "^0.1", reason: "Auth identity for user-scoped checklist state." }],
    tags: ["career", "documents", "checklist", "job-search", "indonesia"],
    usedBy: ["CareerPack"],
    agentRecipe: "Run `rr add document-checklist`. Wire <DocumentChecklist bindings={{ current, seed, updateStatus }} countryTemplateSlot={<CountryTemplateCard bindings={{ templates, getTemplate, instantiate }} />} /> — bindings sourced from api.features['document-checklist'].* queries/mutations.",
    previewPath: "/preview/slices/document-checklist",
    defaultView: "mobile",
    defaultZoom: 1,
  },
];

export function getSlice(slug: string): SliceEntry | null {
  return slices.find((s) => s.slug === slug) ?? null;
}
