<script lang="ts">
  import type { WidgetInstance, WidgetSize } from "../../glass-desktop/types";
  import WidgetCanvas from "./WidgetCanvas.svelte";
  let { space, instances, editing, onSpaceChange, onMove, onRemove, onResize }: { space:0|1; instances:WidgetInstance[]; editing:boolean; onSpaceChange:(space:0|1)=>void; onMove:(id:string,col:number,row:number)=>void; onRemove:(id:string)=>void; onResize:(id:string,size:WidgetSize)=>void }=$props();
  function key(event:KeyboardEvent){const el=event.target as HTMLElement|null;if(el&&/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName))return;if(event.key==="ArrowRight")onSpaceChange(1);if(event.key==="ArrowLeft")onSpaceChange(0)}
</script>
<svelte:window onkeydown={key}/><div class="pager"><div class="track" style:transform={`translateX(${space*-50}%)`}><section aria-label="Space 1 — Today" aria-hidden={space!==0}><WidgetCanvas space={0} {instances} {editing} {onMove} {onRemove} {onResize}/></section><section aria-label="Space 2 — System & work" aria-hidden={space!==1}><WidgetCanvas space={1} {instances} {editing} {onMove} {onRemove} {onResize}/></section></div><button class="edge left" aria-label="Previous space" disabled={space===0} onclick={()=>onSpaceChange(0)}>‹</button><button class="edge right" aria-label="Next space" disabled={space===1} onclick={()=>onSpaceChange(1)}>›</button><nav aria-label="Spaces"><button aria-label="Space 1" aria-current={space===0} onclick={()=>onSpaceChange(0)}></button><button aria-label="Space 2" aria-current={space===1} onclick={()=>onSpaceChange(1)}></button></nav></div>
<style>
.pager{position:relative;height:100%;overflow:hidden}.track{position:absolute;inset:0;display:flex;width:200%;transition:transform var(--duration-settle) var(--ease-settle)}section{width:50%;height:100%;flex:none;overflow:hidden}.edge{position:absolute;top:50%;translate:0 -50%;z-index:30;width:2rem;height:3rem;border:1px solid var(--color-hairline);border-radius:999px;background:var(--color-glass-lo);color:var(--color-ink-mid);font-size:1.5rem;cursor:pointer}.edge:disabled{opacity:.2}.left{left:.5rem}.right{right:.5rem}nav{position:absolute;left:50%;bottom:1rem;translate:-50% 0;z-index:41;display:flex;gap:.45rem}nav button{width:.5rem;height:.5rem;padding:0;border:1px solid var(--color-hairline);border-radius:50%;background:var(--color-glass-lo)}nav button[aria-current="true"]{background:var(--color-ink-hi)}@media(prefers-reduced-motion:reduce){.track{transition:none}}
</style>
