<script lang="ts">
  import { SIZE_CELLS } from "../../glass-desktop/config/constants";
  import { WIDGET_FAMILIES, WIDGET_FAMILY_LABELS, widgetDescriptors } from "../../glass-desktop/lib/widget-catalog";
  let { open, space, onClose, onAdd }: { open:boolean; space:0|1; onClose:()=>void; onAdd:(widgetId:string,space:0|1)=>void } = $props();
  function add(id:string){onAdd(id,space);onClose()}
</script>
{#if open}<div class="scrim" role="presentation" onclick={(e)=>e.currentTarget===e.target&&onClose()}><dialog open aria-label="Add a widget"><header><div><h2>Add a widget</h2><p>Pick a widget for space {space+1}.</p></div><button aria-label="Close" onclick={onClose}>×</button></header><div class="body">{#each WIDGET_FAMILIES as family (family)}{@const defs=widgetDescriptors.filter((d)=>d.family===family)}{#if defs.length}<div class="group"><h3>{WIDGET_FAMILY_LABELS[family]}</h3><div class="grid">{#each defs as descriptor (descriptor.id)}{@const cells=SIZE_CELLS[descriptor.size]}<button class="choice" onclick={()=>add(descriptor.id)}><span class="shape" style:aspect-ratio={`${cells.c*2}/${cells.r}`}></span><strong>{descriptor.title}</strong><small>{cells.c}×{cells.r}</small></button>{/each}</div></div>{/if}{/each}</div></dialog></div>{/if}
<style>
.scrim{position:absolute;inset:0;z-index:55;display:grid;place-items:center;background:#0008;padding:1rem}dialog{width:min(48rem,94vw);max-height:78vh;overflow:hidden;border:1px solid var(--color-hairline);border-radius:var(--radius-widget);background:var(--color-glass-solid);box-shadow:var(--shadow-drag);color:var(--color-ink-hi)}header{display:flex;align-items:start;justify-content:space-between;padding:1rem 1.15rem;border-bottom:1px solid var(--color-hairline)}h2,h3,p{margin:0}h2{font-size:1rem}p,small{color:var(--color-ink-low);font-size:.7rem}header button{border:0;background:transparent;color:var(--color-ink-mid);font-size:1.35rem;cursor:pointer}.body{max-height:65vh;overflow:auto;padding:1rem;display:grid;gap:1rem}.group{display:grid;gap:.45rem}.group h3{font-size:.65rem;text-transform:uppercase;letter-spacing:.08em;color:var(--color-ink-low)}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.45rem}.choice{display:grid;grid-template-columns:2rem 1fr auto;gap:.5rem;align-items:center;text-align:left;padding:.55rem;border:1px solid var(--color-hairline);border-radius:.65rem;background:transparent;color:var(--color-ink-hi);cursor:pointer}.choice:hover{border-color:var(--color-hairline-hover);background:var(--color-hairline)}.shape{width:1.8rem;max-height:1.5rem;border:1px solid var(--color-hairline);border-radius:.3rem;background:linear-gradient(var(--color-glass-hi),var(--color-glass-lo))}.choice strong{font-size:.72rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}@media(max-width:640px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
