/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-init-imports.ts
 * Source: each feature's init.ts (glob: frontend/slices/[slug]/init.ts)
 *
 * To update, add init.ts to your feature and run: pnpm run sync:all
 */

// Feature init files (auto-discovered)
import "@/frontend/slices/example/init"
import "@/frontend/slices/studio/init"

// Non-feature init files
import "@/frontend/shared/foundation/utils/notifications/init"

if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  console.log("[FeatureSettings] Auto-discovered 2 feature init files")
}

