// Optional Features Catalog
//
// Available features that can be installed from the Menu Store.
//
// AUTO-GENERATED - DO NOT EDIT MANUALLY.
// Source: frontend/slices/<feature>/config.ts (auto-discovered)
// Update via: pnpm run sync:features
export const OPTIONAL_FEATURES_CATALOG = [
  {
    "slug": "status",
    "name": "Status",
    "description": "Share status updates with your team",
    "icon": "RadioTower",
    "component": "StatusPage",
    "path": "/dashboard/status",
    "type": "route",
    "version": "2.0.0",
    "category": "communication",
    "tags": [
      "communication",
      "status",
      "updates",
      "stories"
    ],
    "requiresPermission": "status.view",
    "originalRequiresPermission": "status.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "documents",
    "name": "Documents",
    "description": "Collaborative document editor with real-time sync (Deprecated - use Knowledge > Docs)",
    "icon": "FileText",
    "component": "DocumentsPage",
    "path": "/dashboard/documents",
    "type": "route",
    "version": "1.2.0",
    "category": "productivity",
    "tags": [
      "collaboration",
      "real-time",
      "documents",
      "editor",
      "deprecated"
    ],
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "qsr-dashboard",
    "name": "QSR Dashboard",
    "description": "Restaurant weekly report overview — net sales trend, food cost %, daily cash flow, vendor purchases, attachment links.",
    "icon": "Utensils",
    "component": "QsrDashboardPage",
    "path": "/dashboard/qsr-dashboard",
    "type": "route",
    "version": "0.1.0",
    "category": "analytics",
    "tags": [
      "qsr",
      "fnb",
      "restaurant",
      "dashboard",
      "charts",
      "analytics"
    ],
    "requiresPermission": "qsr-dashboard.view",
    "originalRequiresPermission": "qsr-dashboard.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "calendar",
    "name": "Calendar",
    "description": "Team calendar with event management and scheduling",
    "icon": "Calendar",
    "component": "CalendarPage",
    "path": "/dashboard/calendar",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "scheduling",
      "events",
      "productivity"
    ],
    "requiresPermission": "calendar.view",
    "originalRequiresPermission": "calendar.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "reports",
    "name": "Reports",
    "description": "Analytics and reporting dashboard",
    "icon": "BarChart",
    "component": "ReportsPage",
    "path": "/dashboard/reports",
    "type": "route",
    "version": "1.0.0",
    "category": "analytics",
    "tags": [
      "reports",
      "analytics",
      "dashboard"
    ],
    "requiresPermission": "VIEW_REPORTS",
    "originalRequiresPermission": "VIEW_REPORTS",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "tasks",
    "name": "Tasks",
    "description": "Task management and tracking",
    "icon": "CheckSquare",
    "component": "TasksPage",
    "path": "/dashboard/tasks",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "productivity",
      "project-management"
    ],
    "requiresPermission": "tasks.view",
    "originalRequiresPermission": "tasks.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "forms",
    "name": "Forms",
    "description": "Build custom forms for data collection",
    "icon": "FormInput",
    "component": "FormsPage",
    "path": "/dashboard/forms",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "forms",
      "data-collection",
      "surveys"
    ],
    "requiresPermission": "forms.view",
    "originalRequiresPermission": "forms.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "approvals",
    "name": "Approvals",
    "description": "Approval workflows and request management",
    "icon": "CheckCircle",
    "component": "ApprovalsPage",
    "path": "/dashboard/approvals",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "approvals",
      "workflows",
      "requests"
    ],
    "requiresPermission": "approvals.view",
    "originalRequiresPermission": "approvals.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "support",
    "name": "Support",
    "description": "Customer support and helpdesk ticketing system",
    "icon": "Headphones",
    "component": "SupportPage",
    "path": "/dashboard/support",
    "type": "route",
    "version": "1.0.0",
    "category": "communication",
    "tags": [
      "support",
      "tickets",
      "helpdesk"
    ],
    "requiresPermission": "support.view",
    "originalRequiresPermission": "support.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "projects",
    "name": "Projects",
    "description": "Project management with team discussions",
    "icon": "FolderKanban",
    "component": "ProjectsPage",
    "path": "/dashboard/projects",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "projects",
      "collaboration",
      "discussions"
    ],
    "requiresPermission": "projects.view",
    "originalRequiresPermission": "projects.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "audit-log",
    "name": "Audit Log",
    "description": "View activity logs and audit trail",
    "icon": "History",
    "component": "AuditLogPage",
    "path": "/dashboard/audit-log",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "audit",
      "logs",
      "compliance",
      "security"
    ],
    "requiresPermission": "audit-log.view",
    "originalRequiresPermission": "audit-log.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "import-export",
    "name": "Import/Export",
    "description": "Import and export data across workspace",
    "icon": "ArrowUpDown",
    "component": "ImportExportPage",
    "path": "/dashboard/import-export",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "import",
      "export",
      "data",
      "migration"
    ],
    "requiresPermission": "import-export.view",
    "originalRequiresPermission": "import-export.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "integrations",
    "name": "Integrations",
    "description": "Connect with third-party services and APIs",
    "icon": "Plug",
    "component": "IntegrationsPage",
    "path": "/dashboard/integrations",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "integrations",
      "api",
      "webhooks",
      "oauth"
    ],
    "requiresPermission": "integrations.view",
    "originalRequiresPermission": "integrations.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "pos",
    "name": "POS",
    "description": "Point of Sale and retail management",
    "icon": "ShoppingCart",
    "component": "PosPage",
    "path": "/dashboard/pos",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "pos",
      "retail",
      "sales",
      "cashier"
    ],
    "requiresPermission": "pos.view",
    "originalRequiresPermission": "pos.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "marketing",
    "name": "Marketing",
    "description": "Marketing automation and campaign management",
    "icon": "Megaphone",
    "component": "MarketingPage",
    "path": "/dashboard/marketing",
    "type": "route",
    "version": "1.0.0",
    "category": "content",
    "tags": [
      "marketing",
      "campaigns",
      "email",
      "automation"
    ],
    "requiresPermission": "marketing.view",
    "originalRequiresPermission": "marketing.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "analytics",
    "name": "Analytics",
    "description": "Monitor your business performance with real-time analytics",
    "icon": "BarChart3",
    "component": "AnalyticsPage",
    "path": "/dashboard/analytics",
    "type": "route",
    "version": "1.0.0",
    "category": "analytics",
    "tags": [
      "analytics",
      "insights",
      "metrics",
      "dashboard"
    ],
    "requiresPermission": "analytics.view",
    "originalRequiresPermission": "analytics.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "bi",
    "name": "Business Intelligence",
    "description": "Advanced analytics and business intelligence",
    "icon": "LineChart",
    "component": "BiPage",
    "path": "/dashboard/bi",
    "type": "route",
    "version": "1.0.0",
    "category": "analytics",
    "tags": [
      "bi",
      "analytics",
      "dashboards",
      "reports"
    ],
    "requiresPermission": "bi.view",
    "originalRequiresPermission": "bi.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "sales",
    "name": "Sales",
    "description": "Sales management and pipeline tracking",
    "icon": "DollarSign",
    "component": "SalesPage",
    "path": "/dashboard/sales",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "sales",
      "pipeline",
      "deals",
      "revenue"
    ],
    "requiresPermission": "sales.view",
    "originalRequiresPermission": "sales.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "datasets",
    "name": "Datasets",
    "description": "Generic data containers — define schema once, ingest from any business or remote source.",
    "icon": "Table2",
    "component": "DatasetsPage",
    "path": "/dashboard/datasets",
    "type": "route",
    "version": "0.1.0",
    "category": "administration",
    "tags": [
      "data",
      "sync",
      "integration",
      "etl"
    ],
    "requiresPermission": "datasets.view",
    "originalRequiresPermission": "datasets.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "qsr-payables",
    "name": "QSR Payables",
    "description": "Vendor credit purchases pending payment — invoice tracking, due-date reminders, supplier aggregates.",
    "icon": "Receipt",
    "component": "QsrPayablesPage",
    "path": "/dashboard/qsr-payables",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "qsr",
      "fnb",
      "payables",
      "vendor"
    ],
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "qsr-petty-cash",
    "name": "QSR Petty Cash",
    "description": "Small-cash disbursements per branch (LPKK sheet — Laporan Pengeluaran Kas Kecil).",
    "icon": "Coins",
    "component": "QsrPettyCashPage",
    "path": "/dashboard/qsr-petty-cash",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "qsr",
      "fnb",
      "petty-cash"
    ],
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "qsr-master-data",
    "name": "QSR Master Data",
    "description": "Vendor purchases + product HPP catalog — supplier registry, ingredient pricing class, recipe costing.",
    "icon": "BookMarked",
    "component": "QsrMasterDataPage",
    "path": "/dashboard/qsr-master-data",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "qsr",
      "fnb",
      "master",
      "vendors",
      "ingredients"
    ],
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "qsr-allowances",
    "name": "QSR Allowances",
    "description": "Employee allowances — luar-kota, transport, kos subsidies + monthly incentives by branch.",
    "icon": "HandCoins",
    "component": "QsrAllowancesPage",
    "path": "/dashboard/qsr-allowances",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "qsr",
      "fnb",
      "allowances",
      "employee"
    ],
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "qsr-product-changes",
    "name": "QSR Product Changes",
    "description": "Weekly product additions/removals/price changes per branch — recipe lifecycle audit trail.",
    "icon": "Replace",
    "component": "QsrProductChangesPage",
    "path": "/dashboard/qsr-product-changes",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "qsr",
      "fnb",
      "product-changes",
      "waste"
    ],
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "guest-booking",
    "name": "Guest Booking",
    "description": "Hotel guest self-service lifecycle with Syariah-compliance verification",
    "icon": "BedDouble",
    "component": "GuestBookingPage",
    "path": "/dashboard/guest-booking",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "hospitality",
      "hotel",
      "booking",
      "syariah",
      "mahram"
    ],
    "requiresPermission": "guest-booking.view",
    "originalRequiresPermission": "guest-booking.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "staff-operations",
    "name": "Staff Operations",
    "description": "Housekeeping, laundry, damage reports, and shift scheduling for hospitality ops",
    "icon": "ConciergeBell",
    "component": "StaffOperationsPage",
    "path": "/dashboard/staff-operations",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "hospitality",
      "housekeeping",
      "laundry",
      "operations"
    ],
    "requiresPermission": "staff-operations.view",
    "originalRequiresPermission": "staff-operations.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "owner-analytics",
    "name": "Owner Analytics",
    "description": "Strategic financial dashboards, channel mix, and asset expansion tracking for property owners",
    "icon": "PieChart",
    "component": "OwnerAnalyticsPage",
    "path": "/dashboard/owner-analytics",
    "type": "route",
    "version": "0.1.0",
    "category": "analytics",
    "tags": [
      "hospitality",
      "analytics",
      "revenue",
      "kpi",
      "owner"
    ],
    "requiresPermission": "owner-analytics.view",
    "originalRequiresPermission": "owner-analytics.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "create-your-mcp",
    "name": "Create Your MCP",
    "description": "Ubah workspace jadi server MCP — sambungkan ChatGPT, Claude.ai, atau Cursor lewat OAuth 2.1 + PKCE, kelola bearer token, dan atur tool yang boleh dipanggil AI.",
    "icon": "Cable",
    "component": "CreateYourMcpPage",
    "path": "/dashboard/create-your-mcp",
    "type": "route",
    "version": "0.1.0",
    "category": "administration",
    "tags": [
      "ai",
      "mcp",
      "oauth",
      "pkce",
      "chatgpt",
      "claude",
      "cursor",
      "integration"
    ],
    "requiresPermission": "create-your-mcp.view",
    "originalRequiresPermission": "create-your-mcp.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "petty-cash",
    "name": "Petty Cash",
    "description": "Cash-on-hand request → approval → disbursement → close workflow with variance tracking.",
    "icon": "Wallet",
    "component": "PettyCashPage",
    "path": "/dashboard/petty-cash",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "petty-cash",
      "administration"
    ],
    "requiresPermission": "pettyCash.view",
    "originalRequiresPermission": "pettyCash.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "owner-transfers",
    "name": "Owner Transfers",
    "description": "Track owner capital movements: withdrawals, injections, loans, and repayments.",
    "icon": "ArrowLeftRight",
    "component": "OwnerTransfersPage",
    "path": "/dashboard/owner-transfers",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "owner-transfers",
      "administration"
    ],
    "requiresPermission": "ownerTransfers.view",
    "originalRequiresPermission": "ownerTransfers.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "operational-checklist",
    "name": "Operational Checklist",
    "description": "Build operational checklists and run them through the daily/audit workflow with photo + notes capture.",
    "icon": "ClipboardCheck",
    "component": "OperationalChecklistPage",
    "path": "/dashboard/operational-checklist",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "operational-checklist",
      "administration"
    ],
    "requiresPermission": "checklist.view",
    "originalRequiresPermission": "checklist.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "maintenance-scheduling",
    "name": "Maintenance Scheduling",
    "description": "Preventive and reactive maintenance with recurring schedules and cost tracking.",
    "icon": "Wrench",
    "component": "MaintenanceSchedulingPage",
    "path": "/dashboard/maintenance-scheduling",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "maintenance-scheduling",
      "administration"
    ],
    "requiresPermission": "maintenance.view",
    "originalRequiresPermission": "maintenance.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "kpi-thresholds",
    "name": "Kpi Thresholds",
    "description": "Define KPI alert thresholds and triage triggered alerts across branches.",
    "icon": "Gauge",
    "component": "KpiThresholdsPage",
    "path": "/dashboard/kpi-thresholds",
    "type": "route",
    "version": "1.0.0",
    "category": "analytics",
    "tags": [
      "kpi-thresholds",
      "analytics"
    ],
    "requiresPermission": "kpi.view",
    "originalRequiresPermission": "kpi.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "hr",
    "name": "HR Management",
    "description": "Human Resources Management",
    "icon": "Users",
    "component": "HrPage",
    "path": "/dashboard/hr",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "hr",
      "administration"
    ],
    "requiresPermission": "hr.view",
    "originalRequiresPermission": "hr.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "damage-reports",
    "name": "Damage Reports",
    "description": "Report and track damage incidents from reported to resolved.",
    "icon": "AlertTriangle",
    "component": "DamageReportsPage",
    "path": "/dashboard/damage-reports",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "damage-reports",
      "administration"
    ],
    "requiresPermission": "damages.view",
    "originalRequiresPermission": "damages.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "daily-closing",
    "name": "Daily Closing",
    "description": "End-of-day register close with per-payment-method variance and approval workflow.",
    "icon": "ClipboardList",
    "component": "DailyClosingPage",
    "path": "/dashboard/daily-closing",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "daily-closing",
      "administration"
    ],
    "requiresPermission": "closing.view",
    "originalRequiresPermission": "closing.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "customer-loyalty",
    "name": "Customer Loyalty",
    "description": "Customer loyalty program with tiered memberships and a points transaction ledger.",
    "icon": "Award",
    "component": "CustomerLoyaltyPage",
    "path": "/dashboard/customer-loyalty",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "customer-loyalty",
      "administration"
    ],
    "requiresPermission": "loyalty.view",
    "originalRequiresPermission": "loyalty.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "cash-flow-forecast",
    "name": "Cash Flow Forecast",
    "description": "Build cash-flow forecasts from bucketed revenue and expense line items.",
    "icon": "Banknote",
    "component": "CashFlowForecastPage",
    "path": "/dashboard/cash-flow-forecast",
    "type": "route",
    "version": "1.0.0",
    "category": "analytics",
    "tags": [
      "cash-flow-forecast",
      "analytics"
    ],
    "requiresPermission": "cashflow.view",
    "originalRequiresPermission": "cashflow.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "branch-health-scoring",
    "name": "Branch Health Scoring",
    "description": "Capture branch health snapshots across revenue, expense, ops, staff, and customer scores.",
    "icon": "Activity",
    "component": "BranchHealthScoringPage",
    "path": "/dashboard/branch-health-scoring",
    "type": "route",
    "version": "1.0.0",
    "category": "analytics",
    "tags": [
      "branch-health-scoring",
      "analytics"
    ],
    "requiresPermission": "branchhealth.view",
    "originalRequiresPermission": "branchhealth.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "asset-management",
    "name": "Asset Management",
    "description": "Track fixed assets with location, assignment, depreciation and transaction ledger.",
    "icon": "Boxes",
    "component": "AssetManagementPage",
    "path": "/dashboard/asset-management",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "asset-management",
      "administration"
    ],
    "requiresPermission": "assets.view",
    "originalRequiresPermission": "assets.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "accounting",
    "name": "Accounting",
    "description": "Financial Management and Accounting",
    "icon": "Calculator",
    "component": "AccountingPage",
    "path": "/dashboard/accounting",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "accounting",
      "administration"
    ],
    "requiresPermission": "accounting.view",
    "originalRequiresPermission": "accounting.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "inventory",
    "name": "Inventory Management",
    "description": "Comprehensive inventory management with multi-warehouse support, stock tracking, and demand forecasting",
    "icon": "Package",
    "component": "InventoryPage",
    "path": "/dashboard/erp/inventory",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "erp",
      "inventory",
      "warehouse",
      "stock"
    ],
    "requiresPermission": "erp.inventory.view",
    "originalRequiresPermission": "erp.inventory.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "blog",
    "name": "Blog",
    "description": "Tulis artikel, pengumuman, dan konten untuk pelanggan dengan editor sederhana.",
    "icon": "Newspaper",
    "component": "BlogPage",
    "path": "/dashboard/blog",
    "type": "route",
    "version": "1.0.0",
    "category": "content",
    "tags": [
      "blog",
      "content",
      "marketing"
    ],
    "requiresPermission": "blog.view",
    "originalRequiresPermission": "blog.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "notion",
    "name": "Notion",
    "description": "Editor blok ala Notion — tulis halaman kaya dengan slash menu, drag-and-drop blok, kolom, dan markdown.",
    "icon": "NotebookPen",
    "component": "NotionPage",
    "path": "/dashboard/notion",
    "type": "route",
    "version": "0.1.0",
    "category": "content",
    "tags": [
      "notion",
      "editor",
      "content",
      "pages"
    ],
    "requiresPermission": "notion.view",
    "originalRequiresPermission": "notion.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "ai-studio",
    "name": "AI Studio",
    "description": "Kanvas generasi AI — satu prompt besar menghasilkan output streaming dengan grid variasi dan pohon versi (pola Suno / Midjourney / Lovable).",
    "icon": "WandSparkles",
    "component": "AiStudioPage",
    "path": "/dashboard/ai-studio",
    "type": "route",
    "version": "0.1.0",
    "category": "creativity",
    "tags": [
      "ai",
      "studio",
      "generation",
      "streaming",
      "creativity"
    ],
    "requiresPermission": "ai-studio.view",
    "originalRequiresPermission": "ai-studio.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "ai-router",
    "name": "AI Router",
    "description": "Provider-proxy config UI untuk akses LLM ber-tier — nano (Haiku) untuk klasifikasi, mid (Sonnet) untuk chat, flagship (Opus) untuk reasoning. Non-functional scaffold.",
    "icon": "Waypoints",
    "component": "AiRouterPage",
    "path": "/dashboard/ai-router",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "ai",
      "llm",
      "openrouter",
      "tier-routing"
    ],
    "requiresPermission": "ai-router.view",
    "originalRequiresPermission": "ai-router.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "ai-agents",
    "name": "AI Agents",
    "description": "Dashboard pekerja AI otonom — antrean task + jejak langkah per run (gaya Devin/Replit-Agent). Scaffold non-fungsional.",
    "icon": "Workflow",
    "component": "AiAgentsPage",
    "path": "/dashboard/ai-agents",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "ai",
      "agent",
      "autonomous",
      "queue",
      "traces"
    ],
    "requiresPermission": "ai-agents.view",
    "originalRequiresPermission": "ai-agents.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "ai-chat",
    "name": "AI Chat",
    "description": "Chat workbench ala Claude.ai / ChatGPT — kirim pesan ke asisten AI. Scaffold non-fungsional; sambungkan backend untuk balasan sungguhan.",
    "icon": "BotMessageSquare",
    "component": "AiChatPage",
    "path": "/dashboard/ai-chat",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "ai",
      "chat",
      "assistant",
      "productivity"
    ],
    "requiresPermission": "ai-chat.view",
    "originalRequiresPermission": "ai-chat.view",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "crm",
    "name": "CRM",
    "description": "Customer Relationship Management with contacts, leads, opportunities, and sales pipeline",
    "icon": "Handshake",
    "component": "CrmView",
    "path": "/dashboard/erp/crm",
    "type": "route",
    "version": "1.0.0",
    "category": "administration",
    "tags": [
      "erp",
      "crm",
      "customers",
      "leads",
      "sales"
    ],
    "requiresPermission": "erp.crm.view",
    "originalRequiresPermission": "erp.crm.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "ai-admin",
    "name": "AI Admin",
    "description": "Operator console for the AI stack — providers, model registry, instructions, skills, tools, and agent definitions.",
    "icon": "SlidersHorizontal",
    "component": "AiAdminPage",
    "path": "/dashboard/ai-admin",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "ai",
      "admin",
      "providers",
      "models",
      "agents",
      "console"
    ],
    "requiresPermission": "ai.manage_providers",
    "originalRequiresPermission": "ai.manage_providers",
    "status": "beta",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "rate-limit",
    "name": "Rate Limit",
    "description": "Convex-backed per-key request counter. Atomic check-and-increment; expired rows pruned by 5-min cron. Backend-only — no UI.",
    "icon": "Timer",
    "component": "RateLimit",
    "path": "/dashboard/rate-limit",
    "type": "route",
    "version": "0.1.0",
    "category": "administration",
    "tags": [
      "infra",
      "rate-limit",
      "convex",
      "backend",
      "throttle"
    ],
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "notifications",
    "name": "Notifications",
    "description": "Per-page Notify Me popover with localStorage-backed subscription state. UI primitive consumed by other slices — not a top-level route.",
    "icon": "Bell",
    "component": "NotifyMePopover",
    "path": "/dashboard/notifications",
    "type": "route",
    "version": "0.1.0",
    "category": "communication",
    "tags": [
      "notifications",
      "ui",
      "popover",
      "library"
    ],
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "i18n-translate",
    "name": "i18n Translate",
    "description": "Google Translate widget — drop-in language switcher. No API key, no Google Cloud billing. Auto-detect browser language, persist via localStorage + cookie.",
    "icon": "Languages",
    "component": "GoogleTranslate",
    "path": "/dashboard/i18n-translate",
    "type": "route",
    "version": "0.1.0",
    "category": "productivity",
    "tags": [
      "i18n",
      "translate",
      "google-translate",
      "ui",
      "library"
    ],
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "example",
    "name": "Example Feature",
    "description": "A minimal example feature demonstrating SuperSpace patterns and conventions",
    "icon": "Lightbulb",
    "component": "ExampleView",
    "path": "/dashboard/example",
    "type": "route",
    "version": "1.0.0",
    "category": "productivity",
    "tags": [
      "example",
      "demo",
      "tutorial",
      "learning"
    ],
    "requiresPermission": "example.view",
    "originalRequiresPermission": "example.view",
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  },
  {
    "slug": "command-menu",
    "name": "Command Menu",
    "description": "Renderless ⌘K command palette + search modal. Consumer-supplied groups + bindings; slice owns dialog chrome, hotkey, MRU history.",
    "icon": "Command",
    "component": "CommandPalette",
    "path": "/dashboard/command-menu",
    "type": "route",
    "version": "0.2.0",
    "category": "productivity",
    "tags": [
      "ui",
      "palette",
      "cmd-k",
      "navigation",
      "keyboard",
      "library"
    ],
    "status": "stable",
    "isReady": true,
    "featureType": "optional"
  }
]
