/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-preview-registry.ts
 * Source of truth: feature preview modules under frontend/slices and frontend/shared/settings
 *
 * To update this file, add or update preview definitions and run:
 *   pnpm run sync:all
 */

import StudioPreview from '@/frontend/slices/studio/features-preview/index'
import ExamplePreview from '@/frontend/slices/example/features-preview/index'
import UserSettingsPreview from '@/frontend/shared/settings/user-settings/features-preview/index'

import {
  getFeaturePreview,
  getAllFeaturePreviews,
} from '@/frontend/shared/preview/registry'
import type { FeaturePreviewDefinition } from '@/frontend/shared/preview/types'

// Importing each preview module is enough because defineFeaturePreview()
// self-registers the preview in the shared registry on module evaluation.
const allPreviews: FeaturePreviewDefinition[] = [
  StudioPreview,
  ExamplePreview,
  UserSettingsPreview,
]

export { getFeaturePreview, getAllFeaturePreviews }

export {
  StudioPreview,
  ExamplePreview,
  UserSettingsPreview,
}

export const featurePreviewsMap = Object.fromEntries(
  allPreviews
    .filter((preview): preview is FeaturePreviewDefinition => Boolean(preview))
    .map(preview => [preview.featureId, preview])
) as Record<string, FeaturePreviewDefinition>
