import type { AuditAction, AuditEventRow, AuditSeverity } from "./types";

/** Action label + tone for badge rendering. */
export const ACTION_META: Record<AuditAction, { label: string; tone: string }> = {
  create: { label: "Created", tone: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30" },
  update: { label: "Updated", tone: "bg-sky-500/15 text-sky-300 border-sky-500/30" },
  delete: { label: "Deleted", tone: "bg-rose-500/15 text-rose-300 border-rose-500/30" },
  publish: { label: "Published", tone: "bg-violet-500/15 text-violet-300 border-violet-500/30" },
  unpublish: { label: "Unpublished", tone: "bg-zinc-500/15 text-zinc-300 border-zinc-500/30" },
  invite: { label: "Invited", tone: "bg-amber-500/15 text-amber-300 border-amber-500/30" },
  revoke: { label: "Revoked", tone: "bg-rose-500/15 text-rose-300 border-rose-500/30" },
  login: { label: "Signed in", tone: "bg-zinc-500/15 text-zinc-300 border-zinc-500/30" },
  logout: { label: "Signed out", tone: "bg-zinc-500/15 text-zinc-300 border-zinc-500/30" },
  export: { label: "Exported", tone: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30" },
};

export const SEVERITY_META: Record<AuditSeverity, { label: string; tone: string }> = {
  info: { label: "Info", tone: "bg-zinc-500/15 text-zinc-300 border-zinc-500/30" },
  warn: { label: "Warn", tone: "bg-amber-500/15 text-amber-300 border-amber-500/30" },
  alert: { label: "Alert", tone: "bg-rose-500/15 text-rose-300 border-rose-500/30" },
};

/** Demo events — 14 rows. Reset on browser reload. */
export const SEED_EVENTS: AuditEventRow[] = [
  {
    id: "ev_14",
    at: "2026-05-20T08:42:00Z",
    actor: { id: "u_1", name: "Maya Kusumawardani", initials: "MK", role: "owner" },
    action: "publish",
    entityType: "page",
    entityId: "p_home",
    entityLabel: "Homepage hero",
    severity: "info",
    diffSummary: "status: draft → published",
    ipAddress: "103.21.244.18",
  },
  {
    id: "ev_13",
    at: "2026-05-20T08:14:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "update",
    entityType: "role",
    entityId: "r_editor",
    entityLabel: "Editor role",
    severity: "warn",
    diffSummary: "permissions: +manage:workflows",
    ipAddress: "203.0.113.22",
  },
  {
    id: "ev_12",
    at: "2026-05-20T07:42:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "invite",
    entityType: "user",
    entityId: "u_4",
    entityLabel: "faisal@wirausaha.id",
    severity: "info",
  },
  {
    id: "ev_11",
    at: "2026-05-20T07:30:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "create",
    entityType: "post",
    entityId: "post_42",
    entityLabel: "Case study: Lumen rebrand",
    severity: "info",
  },
  {
    id: "ev_10",
    at: "2026-05-20T06:55:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "update",
    entityType: "page",
    entityId: "p_pricing",
    entityLabel: "Pricing — tiers section",
    severity: "info",
    diffSummary: "tiers[2].price: $99 → $129",
  },
  {
    id: "ev_9",
    at: "2026-05-20T06:12:00Z",
    actor: { id: "u_sys", name: "System", initials: "SY", role: "system" },
    action: "export",
    entityType: "session",
    entityId: "sess_export_0520",
    entityLabel: "Daily session export",
    severity: "info",
  },
  {
    id: "ev_8",
    at: "2026-05-19T22:10:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "publish",
    entityType: "post",
    entityId: "post_41",
    entityLabel: "Newsletter: May digest",
    severity: "info",
  },
  {
    id: "ev_7",
    at: "2026-05-19T18:33:00Z",
    actor: { id: "u_1", name: "Maya Kusumawardani", initials: "MK", role: "owner" },
    action: "update",
    entityType: "setting",
    entityId: "s_brand",
    entityLabel: "Brand colors",
    severity: "info",
    diffSummary: "primary: #5b1d99 → #6d28d9",
  },
  {
    id: "ev_6",
    at: "2026-05-19T14:01:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "delete",
    entityType: "webhook",
    entityId: "wh_old",
    entityLabel: "Legacy Zapier webhook",
    severity: "warn",
  },
  {
    id: "ev_5",
    at: "2026-05-19T11:46:00Z",
    actor: { id: "u_5", name: "Sari Nurhayati", initials: "SN", role: "viewer" },
    action: "login",
    entityType: "session",
    entityId: "sess_5_9912",
    entityLabel: "Browser session",
    severity: "info",
    ipAddress: "118.96.40.7",
  },
  {
    id: "ev_4",
    at: "2026-05-19T09:18:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "revoke",
    entityType: "user",
    entityId: "u_old",
    entityLabel: "former@konsultan.id",
    severity: "alert",
  },
  {
    id: "ev_3",
    at: "2026-05-18T20:55:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "create",
    entityType: "workflow",
    entityId: "wf_intake",
    entityLabel: "Lead intake automation",
    severity: "info",
  },
  {
    id: "ev_2",
    at: "2026-05-18T15:24:00Z",
    actor: { id: "u_1", name: "Maya Kusumawardani", initials: "MK", role: "owner" },
    action: "update",
    entityType: "role",
    entityId: "r_owner",
    entityLabel: "Owner role",
    severity: "warn",
    diffSummary: "transferred: u_old → u_1",
  },
  {
    id: "ev_1",
    at: "2026-05-18T08:00:00Z",
    actor: { id: "u_sys", name: "System", initials: "SY", role: "system" },
    action: "create",
    entityType: "setting",
    entityId: "s_init",
    entityLabel: "Workspace initialized",
    severity: "info",
  },
];
