#!/usr/bin/env tsx
/**
 * Auto-generate frontend/slices/initFeatureSettings.ts
 *
 * Scans feature init.ts files and produces static import statements.
 * Also includes non-feature init files (e.g., notifications).
 *
 * Usage:
 *   pnpm run generate:init-imports
 *
 * This script is invoked automatically from pnpm run sync:all.
 */

import fs from "fs"
import path from "path"
import { globSync } from "glob"

const ROOT_DIR = process.cwd()
const OUTPUT_PATH = path.join(ROOT_DIR, "frontend/slices/initFeatureSettings.ts")

/** Non-feature init files that must also be imported */
const EXTRA_INIT_IMPORTS = [
  "@/frontend/shared/foundation/utils/notifications/init",
]

function generateInitContent(): string {
  const initPaths = globSync("frontend/slices/*/init.ts", {
    cwd: ROOT_DIR,
    windowsPathsNoEscape: true,
  }).sort()

  if (initPaths.length === 0) {
    throw new Error("No feature init files found under frontend/slices/*")
  }

  const featureImports = initPaths
    .map(p => {
      const normalized = p.replace(/\\/g, "/").replace(/\.ts$/, "")
      return `import "@/${normalized}"`
    })
    .join("\n")

  const extraImports = EXTRA_INIT_IMPORTS
    .map(p => `import "${p}"`)
    .join("\n")

  const count = initPaths.length

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-init-imports.ts
 * Source: each feature's init.ts (glob: frontend/slices/[slug]/init.ts)
 *
 * To update, add init.ts to your feature and run: pnpm run sync:all
 */

// Feature init files (auto-discovered)
${featureImports}

// Non-feature init files
${extraImports}

if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  console.log("[FeatureSettings] Auto-discovered ${count} feature init files")
}

`
}

async function main() {
  console.log("Generating initFeatureSettings.ts...")

  const content = generateInitContent()

  fs.writeFileSync(OUTPUT_PATH, content, "utf-8")
  console.log(`✓ Generated ${OUTPUT_PATH} (${content.split("\n").length} lines)`)
}

main().catch(err => {
  console.error("Failed to generate init imports:", err)
  process.exit(1)
})
