#!/usr/bin/env tsx
/**
 * Auto-generate preview bindings for all feature previews.
 *
 * This script discovers preview modules from the filesystem so preview imports
 * stay aligned with feature folders and `sync:all` can keep the registry fresh.
 */

import fs from "fs"
import path from "path"
import { globSync } from "glob"
import { getAllFeatures, getFeatureMeta } from "../../frontend/shared/lib/features/registry.server"

const ROOT_DIR = process.cwd()
const OUTPUT_PATH = path.join(ROOT_DIR, "frontend/shared/bindings/previews/feature-previews.generated.ts")
const LAZY_OUTPUT_PATH = path.join(ROOT_DIR, "frontend/shared/preview/lazy-registry.ts")
const FEATURE_PREVIEW_GLOBS = [
  "frontend/slices/*/features-preview/index.ts",
  "frontend/slices/*/features-preview/index.tsx",
  "frontend/shared/settings/*/features-preview/index.ts",
  "frontend/shared/settings/*/features-preview/index.tsx",
]

interface PreviewEntry {
  importName: string
  importPath: string
  exportName: string
  sortOrder: number
}

function toPascalCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

function getPreviewKey(relativePath: string): string {
  const normalizedPath = relativePath.replace(/\\/g, "/")

  if (normalizedPath.startsWith("frontend/slices/")) {
    return normalizedPath.split("/")[2]
  }

  if (normalizedPath.startsWith("frontend/shared/settings/")) {
    return normalizedPath.split("/")[3]
  }

  return path.basename(path.dirname(path.dirname(normalizedPath)))
}

function getSortOrder(relativePath: string, featureOrderBySlug: Map<string, number>): number {
  const normalizedPath = relativePath.replace(/\\/g, "/")

  if (normalizedPath.startsWith("frontend/slices/")) {
    const slug = normalizedPath.split("/")[2]
    return featureOrderBySlug.get(slug) ?? Number.MAX_SAFE_INTEGER
  }

  return Number.MAX_SAFE_INTEGER
}

function buildPreviewEntries(): PreviewEntry[] {
  getAllFeatures()

  const featureOrderBySlug = new Map<string, number>()
  for (const feature of getAllFeatures()) {
    const meta = getFeatureMeta(feature.id)
    if (meta) {
      featureOrderBySlug.set(meta.slug, feature.ui.order)
    }
  }

  const previewPaths = FEATURE_PREVIEW_GLOBS.flatMap(pattern =>
    globSync(pattern, {
      cwd: ROOT_DIR,
      windowsPathsNoEscape: true,
    })
  )

  const uniquePreviewPaths = [...new Set(previewPaths)].sort((a, b) => a.localeCompare(b))

  return uniquePreviewPaths
    .map((relativePath) => {
      const key = getPreviewKey(relativePath)
      const exportName = `${toPascalCase(key)}Preview`

      return {
        importName: exportName,
        exportName,
        importPath: `@/${relativePath.replace(/\\/g, "/").replace(/\.(ts|tsx)$/, "")}`,
        sortOrder: getSortOrder(relativePath, featureOrderBySlug),
      }
    })
    .sort((a, b) => {
      if (a.sortOrder !== b.sortOrder) {
        return a.sortOrder - b.sortOrder
      }
      return a.importName.localeCompare(b.importName)
    })
}

function generateContent(entries: PreviewEntry[]): string {
  const imports = entries
    .map(entry => `import ${entry.importName} from '${entry.importPath}'`)
    .join("\n")

  const previewList = entries
    .map(entry => `  ${entry.importName},`)
    .join("\n")

  const exportList = entries
    .map(entry => `  ${entry.exportName},`)
    .join("\n")

 return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-preview-registry.ts
 * Source of truth: feature preview modules under frontend/slices and frontend/shared/settings
 *
 * To update this file, add or update preview definitions and run:
 *   pnpm run sync:all
 */

${imports}

import {
  getFeaturePreview,
  getAllFeaturePreviews,
} from '@/frontend/shared/preview/registry'
import type { FeaturePreviewDefinition } from '@/frontend/shared/preview/types'

// Importing each preview module is enough because defineFeaturePreview()
// self-registers the preview in the shared registry on module evaluation.
const allPreviews: FeaturePreviewDefinition[] = [
${previewList}
]

export { getFeaturePreview, getAllFeaturePreviews }

export {
${exportList}
}

export const featurePreviewsMap = Object.fromEntries(
  allPreviews
    .filter((preview): preview is FeaturePreviewDefinition => Boolean(preview))
    .map(preview => [preview.featureId, preview])
) as Record<string, FeaturePreviewDefinition>
`
}

function generateLazyRegistry(entries: PreviewEntry[]): string {
  const importerLines = entries
    .map((entry) => `  ${JSON.stringify(getKeyFromImportPath(entry.importPath))}: () => import(${JSON.stringify(entry.importPath)}),`)
    .join("\n")

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-preview-registry.ts
 * Source of truth: feature preview modules under frontend/slices and frontend/shared/settings
 *
 * Lazy loader — single-feature dynamic import + module-scoped cache.
 * Use this from any consumer surface that needs to render exactly one preview
 * (mock-dashboard, MenuStorePage preview pane, WorkspaceStorePage preview pane).
 *
 * To update this file, add or update preview definitions and run:
 *   pnpm run sync:all
 */

import type { FeaturePreviewDefinition } from "./types"

type PreviewImporter = () => Promise<{ default: FeaturePreviewDefinition }>

const PREVIEW_IMPORTERS: Record<string, PreviewImporter> = {
${importerLines}
}

const cache = new Map<string, FeaturePreviewDefinition>()

export async function loadSinglePreview(featureId: string): Promise<FeaturePreviewDefinition | null> {
  const cached = cache.get(featureId)
  if (cached) return cached

  const importer = PREVIEW_IMPORTERS[featureId]
  if (!importer) return null

  const mod = await importer()
  const preview = mod.default
  if (preview) cache.set(featureId, preview)
  return preview ?? null
}

export function hasSinglePreview(featureId: string): boolean {
  return featureId in PREVIEW_IMPORTERS
}

export function listPreviewIds(): string[] {
  return Object.keys(PREVIEW_IMPORTERS)
}
`
}

// Map "@/frontend/slices/foo-bar/features-preview" → "foo-bar"
// Map "@/frontend/shared/settings/user-settings/features-preview" → "user-settings"
function getKeyFromImportPath(importPath: string): string {
  const parts = importPath.split("/")
  const idx = parts.indexOf("features-preview")
  if (idx === -1) return parts[parts.length - 1]
  return parts[idx - 1]
}

function main() {
  const entries = buildPreviewEntries()
  const content = generateContent(entries)
  const lazyContent = generateLazyRegistry(entries)

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  fs.writeFileSync(OUTPUT_PATH, content)
  fs.writeFileSync(LAZY_OUTPUT_PATH, lazyContent)

  console.log(`Generated preview registry with ${entries.length} preview modules.`)
  console.log(`Generated lazy preview registry with ${entries.length} importers.`)
}

main()
