// AUTO-GENERATED by scripts/features/gen-slice-registries.mjs
// DO NOT EDIT — re-run `node scripts/features/gen-slice-registries.mjs`

// Re-exports of every slice's convex tables fragment so consumers can
// compose their root convex/schema.ts with a single barrel import.
// (no slices register an export-registry entry yet)
