// AUTO-GENERATED by scripts/features/gen-slice-registries.mjs
// DO NOT EDIT — re-run `node scripts/features/gen-slice-registries.mjs`

import type { ComponentType } from "react";

export const SLICE_PREVIEWS: Record<string, () => Promise<{ default: ComponentType }>> = {

};
