// AUTO-GENERATED by scripts/features/gen-slice-registries.mjs
// DO NOT EDIT — re-run `node scripts/features/gen-slice-registries.mjs`

import { registerFeatures } from "./registerFeature";
import type { RegisteredSlice } from "./registry";

import { adminConfig } from "@/features/admin/config";
import { aiRouterConfig } from "@/features/ai-router/config";
import { appStoreConfig } from "@/features/app-store/config";
import { appshellConfig } from "@/features/appshell/config";
import { assistantConfig } from "@/features/assistant/config";
import { auditLogConfig } from "@/features/audit-log/config";
import { broadcastChannelSyncConfig } from "@/features/broadcast-channel-sync/config";
import { browserConfig } from "@/features/browser/config";
import { calComBookingConfig } from "@/features/cal-com-booking/config";
import { codeEditorConfig } from "@/features/code-editor/config";
import { commandMenuConfig } from "@/features/command-menu/config";
import { commentsConfig } from "@/features/comments/config";
import { convexAuthConfig } from "@/features/convex-auth/config";
import { dokuPaymentConfig } from "@/features/doku-payment/config";
import { imageEditorConfig } from "@/features/image-editor/config";
import { mediaViewerConfig } from "@/features/media-viewer/config";
import { midtransPaymentConfig } from "@/features/midtrans-payment/config";
import { notionConfig } from "@/features/notion/config";
import { osTerminalConfig } from "@/features/os-terminal/config";
import { platformAdminConfig } from "@/features/platform-admin/config";
import { reelEditorConfig } from "@/features/reel-editor/config";
import { resendNewsletterConfig } from "@/features/resend-newsletter/config";
import { seoConfig } from "@/features/seo/config";
import { systemMonitorConfig } from "@/features/system-monitor/config";
import { vectorSearchConfig } from "@/features/vector-search/config";

export const REGISTERED_SLICES: RegisteredSlice[] = [
  {
    ...adminConfig,
    importPath: "@/features/admin/config",
    version: "0.2.1",
  },
  {
    ...aiRouterConfig,
    importPath: "@/features/ai-router/config",
    version: "0.1.0",
  },
  {
    ...appStoreConfig,
    importPath: "@/features/app-store/config",
    version: "1.0.0",
  },
  {
    ...appshellConfig,
    importPath: "@/features/appshell/config",
    version: "1.2.0",
  },
  {
    ...assistantConfig,
    importPath: "@/features/assistant/config",
    version: "1.0.0",
  },
  {
    ...auditLogConfig,
    importPath: "@/features/audit-log/config",
    version: "0.2.0",
  },
  {
    ...broadcastChannelSyncConfig,
    importPath: "@/features/broadcast-channel-sync/config",
    version: "0.1.0",
  },
  {
    ...browserConfig,
    importPath: "@/features/browser/config",
    version: "1.0.0",
  },
  {
    ...calComBookingConfig,
    importPath: "@/features/cal-com-booking/config",
    version: "0.1.0",
  },
  {
    ...codeEditorConfig,
    importPath: "@/features/code-editor/config",
    version: "1.0.0",
  },
  {
    ...commandMenuConfig,
    importPath: "@/features/command-menu/config",
    version: "0.2.0",
  },
  {
    ...commentsConfig,
    importPath: "@/features/comments/config",
    version: "0.2.1",
  },
  {
    ...convexAuthConfig,
    importPath: "@/features/convex-auth/config",
    version: "0.3.0",
  },
  {
    ...dokuPaymentConfig,
    importPath: "@/features/doku-payment/config",
    version: "0.1.1",
  },
  {
    ...imageEditorConfig,
    importPath: "@/features/image-editor/config",
    version: "2.0.0",
  },
  {
    ...mediaViewerConfig,
    importPath: "@/features/media-viewer/config",
    version: "1.0.0",
  },
  {
    ...midtransPaymentConfig,
    importPath: "@/features/midtrans-payment/config",
    version: "0.1.1",
  },
  {
    ...notionConfig,
    importPath: "@/features/notion/config",
    version: "1.0.0",
  },
  {
    ...osTerminalConfig,
    importPath: "@/features/os-terminal/config",
    version: "1.0.0",
  },
  {
    ...platformAdminConfig,
    importPath: "@/features/platform-admin/config",
    version: "0.1.0",
  },
  {
    ...reelEditorConfig,
    importPath: "@/features/reel-editor/config",
    version: "1.0.0",
  },
  {
    ...resendNewsletterConfig,
    importPath: "@/features/resend-newsletter/config",
    version: "0.1.3",
  },
  {
    ...seoConfig,
    importPath: "@/features/seo/config",
    version: "0.2.1",
  },
  {
    ...systemMonitorConfig,
    importPath: "@/features/system-monitor/config",
    version: "1.0.0",
  },
  {
    ...vectorSearchConfig,
    importPath: "@/features/vector-search/config",
    version: "0.1.0",
  },
];

registerFeatures(REGISTERED_SLICES);
