// AUTO-GENERATED by scripts/features/gen-slice-registries.mjs
// DO NOT EDIT — re-run `node scripts/features/gen-slice-registries.mjs`

import { registerFeatures } from "./registerFeature";
import type { RegisteredSlice } from "./registry";

export const REGISTERED_SLICES: RegisteredSlice[] = [

];

registerFeatures(REGISTERED_SLICES);
