// convex/migrations/M_doku_namespace_2026_05.ts
// AUTOGENERATED by scripts/apply-midtrans-collision-fix.mjs.
// Track G of Wave N+1 — resolves the legacy paymentOrders /
// paymentWebhookEvents collision between doku-payment + midtrans-payment.
//
// Slice: doku-payment
// From:  v0.9.0
// To:    v0.1.0
// Steps: 2 (2 renames, 0 drops)
//
// The blocks below are the planner's rename-step artifacts concatenated
// verbatim. Run each `internalMutation` once via the Convex dashboard,
// verify row counts match the prior shared-table count for THIS provider,
// then drop the legacy paymentOrders / paymentWebhookEvents tables in a
// follow-up irreversible migration. Filtering happens via the legacy
// `provider` discriminator on the row — see the rename body comments.
import { internalMutation } from "../_generated/server";

// convex/migrations/rename-paymentOrders-to-doku_orders.ts
// One-shot data copy — Convex has no in-place table rename.


export const renameTablePaymentOrdersToDokuOrders = internalMutation({
  args: {},
  handler: async (ctx) => {
    // 1. Copy every row from the old table into the new one.
    // NOTE: bare .collect() — one-shot migration; if paymentOrders > ~16k rows
    // batch via .paginate() loop and re-invoke the mutation per cursor.
    const rows = await ctx.db.query("paymentOrders").take(16000);
    for (const row of rows) {
      const { _id, _creationTime, ...rest } = row;
      await ctx.db.insert("doku_orders", rest);
    }
    // 2. Once verified, drop the old table in a follow-up migration.
    //    (Leaving the drop separate keeps this step reversible.)
    return { copied: rows.length };
  },
});
// slug: doku-payment

// convex/migrations/rename-paymentWebhookEvents-to-doku_webhook_events.ts
// One-shot data copy — Convex has no in-place table rename.


export const renameTablePaymentWebhookEventsToDokuWebhookEvents = internalMutation({
  args: {},
  handler: async (ctx) => {
    // 1. Copy every row from the old table into the new one.
    // NOTE: bare .collect() — one-shot migration; if paymentWebhookEvents
    // > ~16k rows batch via .paginate() loop and re-invoke per cursor.
    const rows = await ctx.db.query("paymentWebhookEvents").take(16000);
    for (const row of rows) {
      const { _id, _creationTime, ...rest } = row;
      await ctx.db.insert("doku_webhook_events", rest);
    }
    // 2. Once verified, drop the old table in a follow-up migration.
    //    (Leaving the drop separate keeps this step reversible.)
    return { copied: rows.length };
  },
});
// slug: doku-payment
