<script lang="ts">
 import{onMount}from"svelte";import AppIcon from"../components/AppIcon.svelte";import WindowFrame from"../components/WindowFrame.svelte";import{applyChromeInsets,openWindow,setLauncherOpen,setNotificationCenterOpen,shellStore}from"../../appshell/lib/store";import{setActiveSpace,SPACE_IDS,spaceOf}from"../../appshell/lib/spaces-core";import{groupTop}from"../../appshell/lib/window-tabs-core";import{setSpotlightOpen}from"../../appshell/lib/store-panels";import type{AppDescriptor}from"../types";
 let{apps,brand}:{apps:AppDescriptor[];brand:{name:string;logo?:string;idleAppName?:string}}=$props();let v=$state(0);onMount(()=>{applyChromeInsets({top:30,bottom:92});const u=shellStore.subscribe(()=>v++);return()=>{u();applyChromeInsets({})}});let order=$derived((v,shellStore.getOrder()));let focused=$derived((v,shellStore.getFocused()));let activeSpace=$derived((v,shellStore.getActiveSpace()));let wins=$derived(order.map(id=>shellStore.getWindow(id)).filter(w=>w&&!w.minimized&&spaceOf(w)===activeSpace&&(!w.groupId||groupTop(w.groupId)===w.id)));let focusedWin=$derived(focused?shellStore.getWindow(focused):undefined);let active=$derived(apps.find(a=>a.id===focusedWin?.app));let dock=$derived(apps.filter(a=>!a.noDock).slice(0,12));const launch=(a:AppDescriptor)=>openWindow(a.id,a.title,a.defaultSize,undefined,{multi:a.multi});
</script>
<div class="shell mac" data-shell="macos">
 <header class="menubar"><button class="brand" aria-label="Applications" onclick={()=>setLauncherOpen(true)}>{brand.logo??"◆"}</button><strong>{active?.title??brand.idleAppName??brand.name}</strong>{#each active?.menus??[] as menu (menu.label)}<button class="menu" onclick={()=>{}}>{menu.label}</button>{/each}<span></span><button onclick={()=>setSpotlightOpen(true)}>⌕</button>{#each SPACE_IDS as n (n)}<button class:current={n===activeSpace} onclick={()=>setActiveSpace(n)}>{n}</button>{/each}<button aria-label="Notifications" onclick={()=>setNotificationCenterOpen(true)}>◉</button><time>{new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></header>
 <main class="desktop"><div class="icons">{#each apps.filter(a=>!a.noDock).slice(0,8) as app (app.id)}<AppIcon {app} onclick={()=>launch(app)}/>{/each}</div>{#each wins as win (win.id)}{@const app=apps.find(a=>a.id===win.app)}{#if app}<WindowFrame {win} {app} shell="macos"/>{/if}{/each}</main>
 <footer class="dock" aria-label="Dock"><button class="launch" aria-label="Open applications" onclick={()=>setLauncherOpen(true)}>⌘</button>{#each dock as app (app.id)}<AppIcon {app} label={false} onclick={()=>launch(app)}/>{/each}</footer>
</div>
<style>.shell{position:absolute;inset:0;color:white}.menubar{height:30px;display:flex;align-items:center;gap:7px;padding:0 10px;background:#10101499;backdrop-filter:blur(24px);font-size:12px}.menubar>span{flex:1}.menubar button{border:0;background:transparent;color:inherit;padding:4px 6px;border-radius:6px}.menubar button:hover,.menubar .current{background:#ffffff20}.brand{font-weight:800}.desktop{position:absolute;inset:30px 0 0;overflow:hidden}.icons{position:absolute;right:14px;top:14px;z-index:2;display:grid;grid-template-columns:repeat(2,78px);gap:14px}.dock{position:absolute;z-index:800;bottom:12px;left:50%;transform:translateX(-50%);display:flex;align-items:end;gap:8px;padding:8px 10px;border:1px solid #ffffff4a;border-radius:18px;background:#ffffff24;backdrop-filter:blur(26px);box-shadow:0 16px 45px #0005}.launch{width:48px;height:48px;border:0;border-radius:14px;background:#ffffff25;color:white;font-size:20px}time{white-space:nowrap}</style>
