<script lang="ts">
 import{onMount}from"svelte";import AppIcon from"../components/AppIcon.svelte";import AppHost from"../components/AppHost.svelte";import{openWindow,restoreWindow,minimizeWindow,setLauncherOpen,setNotificationCenterOpen,shellStore}from"../../appshell/lib/store";import type{AppDescriptor}from"../types";
 let{apps,kind="ios"}:{apps:AppDescriptor[];kind?:"ios"|"android"}=$props();let v=$state(0),home=$state(true),recents=$state(false);onMount(()=>shellStore.subscribe(()=>v++));let order=$derived((v,shellStore.getOrder()));let focused=$derived((v,shellStore.getFocused()));let topId=$derived(focused&&!shellStore.getWindow(focused)?.minimized?focused:[...order].reverse().find(id=>!shellStore.getWindow(id)?.minimized)??null);let top=$derived(topId?shellStore.getWindow(topId):undefined);let active=$derived(apps.find(a=>a.id===top?.app));let visible=$derived(apps.filter(a=>!a.noDock));let recentWins=$derived([...order].reverse().map(id=>shellStore.getWindow(id)).filter(Boolean).slice(0,8));function launch(a:AppDescriptor){openWindow(a.id,a.title,a.defaultSize,undefined,{multi:a.multi});home=false;recents=false}function goHome(){if(topId)minimizeWindow(topId);home=true;recents=false}function resume(id:string){restoreWindow(id);home=false;recents=false}
</script>
<div class={`phone ${kind}`} data-shell={kind}><header class="status"><time>{new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time><span></span><button aria-label="Search" onclick={()=>setLauncherOpen(true)}>⌕</button><button aria-label="Notifications" onclick={()=>setNotificationCenterOpen(true)}>◉</button><b>{kind==="android"?"▮▮":"▰"}</b></header>
 {#if home}<main class="home"><div class="grid">{#each visible as app (app.id)}<AppIcon {app} onclick={()=>launch(app)}/>{/each}</div>{#if kind==="ios"}<footer class="dock">{#each visible.slice(0,4) as app (app.id)}<AppIcon {app} label={false} onclick={()=>launch(app)}/>{/each}</footer>{/if}</main>{:else if active&&top}<main class="app"><AppHost app={active} payload={top.payload}/></main>{/if}
 {#if recents}<div class="recents"><h2>Recent apps</h2><div>{#each recentWins as w (w.id)}<button onclick={()=>resume(w.id)}><b>{apps.find(a=>a.id===w.app)?.icon??w.title.slice(0,1)}</b><span>{w.title}</span></button>{/each}</div></div>{/if}
 <nav class="nav" aria-label="System navigation">{#if kind==="android"}<button onclick={goHome}>◁</button><button onclick={goHome}>○</button><button onclick={()=>recents=!recents}>▢</button>{:else}<button class="homebar" aria-label="Home" onclick={goHome} ondblclick={()=>recents=!recents}></button>{/if}</nav></div>
<style>.phone{position:absolute;inset:0;color:white;overflow:hidden}.status{height:34px;display:flex;align-items:center;gap:9px;padding:0 14px;font-size:11px;position:relative;z-index:20}.status span{flex:1}.status button{border:0;background:transparent;color:inherit}.home{position:absolute;inset:34px 0 28px;overflow:auto;padding:20px 14px 92px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px 8px}.android .grid{grid-template-columns:repeat(5,1fr);gap:17px 5px}.android :global(.tile){border-radius:50%}.dock{position:fixed;left:14px;right:14px;bottom:28px;height:70px;display:flex;justify-content:space-around;align-items:center;border-radius:22px;background:#ffffff2b;backdrop-filter:blur(24px)}.app{position:absolute;inset:34px 0 28px;background:var(--background,#fff);color:var(--foreground,#111);overflow:auto}.nav{position:absolute;z-index:30;bottom:0;left:0;right:0;height:28px;display:flex;justify-content:space-around;align-items:center}.android .nav{background:#0003}.nav button{border:0;background:transparent;color:white}.homebar{width:120px;height:5px;border-radius:99px!important;background:white!important}.recents{position:absolute;z-index:25;inset:34px 0 28px;background:#111b;backdrop-filter:blur(20px);padding:18px;overflow:auto}.recents h2{font-size:1rem}.recents>div{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.recents button{display:grid;height:140px;place-items:center;border:1px solid #ffffff26;border-radius:18px;background:#ffffff18;color:white}.recents button b{font-size:2rem}.ios{background:linear-gradient(160deg,#27446f,#753f73 52%,#d97865)}.android{background:linear-gradient(160deg,#31483e,#27445c 52%,#665b48)}</style>
