<script lang="ts">
 import{onMount}from"svelte";import{clipboardStore,copyClip,removeClip,setClipboardOpen}from"../../appshell/lib/clipboard-core";import{quickLookStore,closeQuickLook}from"../../appshell/lib/quick-look-core";import{shareStore,closeShare,targetsFor}from"../../appshell/lib/share-core";import{lockStore,requestUnlock}from"../../appshell/lib/lock-core";import{shortcutStore,setShortcutHelpOpen}from"../../appshell/lib/shortcuts-core";let c=$state(0),q=$state(0),s=$state(0),l=$state(0),h=$state(0);onMount(()=>{const f=[clipboardStore.subscribe(()=>c++),quickLookStore.subscribe(()=>q++),shareStore.subscribe(()=>s++),lockStore.subscribe(()=>l++),shortcutStore.subscribe(()=>h++)];return()=>f.forEach(x=>x())});let clips=$derived((c,clipboardStore.get())),clipOpen=$derived((c,clipboardStore.getOpen())),ql=$derived((q,quickLookStore.get())),share=$derived((s,shareStore.get())),locked=$derived((l,lockStore.get())),help=$derived((h,shortcutStore.getOpen())),hints=$derived((h,shortcutStore.get()));
 const text=(v:unknown)=>typeof v==="string"?v:JSON.stringify(v,null,2);
</script>
{#if clipOpen}<section class="sheet"><header><b>Clipboard</b><button onclick={()=>setClipboardOpen(false)}>×</button></header>{#each clips as x (x.id)}<article><button class="copy" onclick={()=>copyClip(x.text)}>{x.text}</button><button onclick={()=>removeClip(x.id)}>×</button></article>{/each}</section>{/if}
{#if ql.open}<div class="modal" role="presentation" onclick={closeQuickLook}><section role="dialog" tabindex="-1" onclick={e=>e.stopPropagation()} onkeydown={e=>e.stopPropagation()}><header><b>Quick Look</b><button onclick={closeQuickLook}>×</button></header><pre>{text(ql.target)}</pre></section></div>{/if}
{#if share.open}<div class="modal" role="presentation" onclick={closeShare}><section role="dialog" tabindex="-1" onclick={e=>e.stopPropagation()} onkeydown={e=>e.stopPropagation()}><header><b>Share</b><button onclick={closeShare}>×</button></header>{#each targetsFor(share.payload) as t (t.id)}<button class="target" onclick={()=>{t.run(share.payload);closeShare()}}>{t.label}</button>{/each}</section></div>{/if}
{#if help}<div class="modal" role="presentation" onclick={()=>setShortcutHelpOpen(false)}><section role="dialog" tabindex="-1" onclick={e=>e.stopPropagation()} onkeydown={e=>e.stopPropagation()}><header><b>Keyboard shortcuts</b><button onclick={()=>setShortcutHelpOpen(false)}>×</button></header>{#each hints as x (`${x.group??""}:${x.keys}:${x.label}`)}<article><span>{x.label}</span><kbd>{x.keys}</kbd></article>{/each}</section></div>{/if}
{#if locked}<div class="lock"><div><div class="clock">{new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</div><p>Locked</p><button onclick={()=>requestUnlock()}>Unlock</button></div></div>{/if}
<style>.sheet{position:absolute;z-index:945;left:50%;bottom:70px;transform:translateX(-50%);width:min(520px,92vw);max-height:55vh;overflow:auto;background:#171717eb;color:white;border:1px solid #ffffff30;border-radius:16px;padding:12px}.sheet header,.modal header{display:flex;justify-content:space-between}.sheet header button,.modal header button{border:0;background:transparent;color:inherit}.sheet article{display:flex;gap:8px}.sheet article button{border:0;background:transparent;color:white}.sheet .copy{flex:1;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:8px}.modal{position:absolute;inset:0;z-index:960;display:grid;place-items:center;background:#0007;backdrop-filter:blur(10px)}.modal section{width:min(560px,90vw);max-height:70vh;overflow:auto;border-radius:18px;padding:16px;background:#18181b;color:white}.modal pre{white-space:pre-wrap;word-break:break-word}.target{display:block;width:100%;margin-top:8px;border:0;border-radius:10px;padding:10px;background:#ffffff12;color:white;text-align:left}.modal article{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #ffffff12}kbd{font:600 11px ui-monospace;background:#ffffff12;padding:4px 7px;border-radius:6px}.lock{position:absolute;inset:0;z-index:1100;display:grid;place-items:center;background:#111827e8;color:white;backdrop-filter:blur(30px);text-align:center}.clock{font-size:4rem;font-weight:200}.lock button{border:0;border-radius:999px;padding:10px 22px}</style>
