<script lang="ts">
  import katex from "katex";
  import type { Block } from "@notion/shared/types";
  import type { PageEditorCore } from "@notion/slices/editor/lib/page-core";
  let { block, core, readonly = false, onNavigate } = $props<{ block: Block; core: PageEditorCore; readonly?: boolean; onNavigate?: (pageId: string) => void }>();
  function patch(patch: Partial<Block>) { if (!readonly) void core.updateBlock(block.id, patch); }
  function cell(row: number, col: number, value: string) { const rows=(block.tableRows??[["",""]]).map((r)=>[...r]); rows[row] ??=[]; rows[row][col]=value; patch({tableRows:rows}); }
</script>
{#if block.type === "divider"}<hr class="my-3 border-border" />
{:else if block.type === "code"}<div class="rounded-lg bg-muted p-3"><input class="mb-2 w-28 bg-transparent text-xs text-muted-foreground outline-none" value={block.lang??"text"} disabled={readonly} onchange={(e)=>patch({lang:e.currentTarget.value})}/><textarea class="min-h-24 w-full resize-y bg-transparent font-mono text-sm outline-none" value={block.text} disabled={readonly} oninput={(e)=>patch({text:e.currentTarget.value})}></textarea></div>
{:else if block.type === "equation"}<div class="grid gap-2 rounded-lg border p-3"><textarea class="min-h-16 w-full resize-y bg-transparent font-mono text-sm outline-none" value={block.text} disabled={readonly} oninput={(e)=>patch({text:e.currentTarget.value})}></textarea><div class="overflow-x-auto text-center text-lg" {@attach (node)=>{katex.render(block.text||"\\square",node,{throwOnError:false});}}></div></div>
{:else if block.type === "image"}<div class="grid gap-2"><input class="rounded-md border bg-transparent px-2 py-1 text-sm" placeholder="Image URL" value={block.url??""} disabled={readonly} onchange={(e)=>patch({url:e.currentTarget.value})}/>{#if block.url}<img class="max-h-80 max-w-full rounded-lg border object-contain" src={block.url} alt={block.caption??"Image block"}/>{/if}<input class="bg-transparent text-xs text-muted-foreground outline-none" placeholder="Caption" value={block.caption??""} disabled={readonly} onchange={(e)=>patch({caption:e.currentTarget.value})}/></div>
{:else if block.type === "audio"}<div class="grid gap-2"><input class="rounded-md border bg-transparent px-2 py-1 text-sm" placeholder="Audio URL" value={block.url??""} disabled={readonly} onchange={(e)=>patch({url:e.currentTarget.value})}/>{#if block.url}<audio class="w-full" controls src={block.url}><track kind="captions" /></audio>{/if}</div>
{:else if block.type === "video"}<div class="grid gap-2"><input class="rounded-md border bg-transparent px-2 py-1 text-sm" placeholder="Video URL" value={block.url??""} disabled={readonly} onchange={(e)=>patch({url:e.currentTarget.value})}/>{#if block.url}<video class="max-h-80 w-full rounded-lg bg-black" controls src={block.url}><track kind="captions" /></video>{/if}</div>
{:else if block.type === "embed"}<div class="grid gap-2"><input class="rounded-md border bg-transparent px-2 py-1 text-sm" placeholder="https://…" value={block.url??""} disabled={readonly} onchange={(e)=>patch({url:e.currentTarget.value})}/>{#if block.url}<iframe class="h-64 w-full rounded-lg border" src={block.url} title={block.caption||"Embedded content"}></iframe>{/if}</div>
{:else if block.type === "table"}<div class="overflow-x-auto"><table class="w-full border-collapse text-sm"><tbody>{#each (block.tableRows?.length?block.tableRows:[["",""],["",""]]) as row, ri (ri)}<tr>{#each row as value, ci (ci)}<td class="border p-0"><input class="w-full bg-transparent px-2 py-1 outline-none" value={value} disabled={readonly} oninput={(e)=>cell(ri,ci,e.currentTarget.value)}/></td>{/each}</tr>{/each}</tbody></table></div>
{:else if block.type === "toggle"}<div class="rounded-lg border p-2"><button type="button" class="flex w-full items-center gap-2 text-left text-sm font-medium" onclick={()=>patch({collapsed:!block.collapsed})}><span>{block.collapsed?"▸":"▾"}</span><span>{block.text||"Toggle"}</span></button>{#if !block.collapsed}<div class="mt-2 grid gap-1 border-l pl-4">{#each block.children??[] as child (child.id)}<textarea class="w-full resize-none bg-transparent text-sm outline-none" value={child.text} disabled={readonly} onchange={(e)=>patch({children:(block.children??[]).map((x)=>x.id===child.id?{...x,text:e.currentTarget.value}:x)})}></textarea>{/each}</div>{/if}</div>
{:else if block.type.startsWith("columns")}<div class="grid gap-2" style={`grid-template-columns:repeat(${block.columns?.length||Number(block.type.slice(-1))||2},minmax(0,1fr))`}>{#each block.columns??[] as column, ci (ci)}<div class="min-h-16 rounded-lg border p-2">{#each column as child (child.id)}<p class="text-sm">{child.text||child.type}</p>{/each}</div>{/each}</div>
{:else if block.type === "page"}<button type="button" class="flex w-full items-center gap-2 rounded-lg border px-3 py-2 text-left hover:bg-muted" onclick={()=>block.pageId&&onNavigate?.(block.pageId)}>📄 <span>{block.text||"Untitled page"}</span></button>
{:else if block.type === "database"}<div class="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">Database {block.databaseId?`· ${block.databaseId}`:"· connect a database adapter in the host"}</div>
{:else if block.type === "button"}<div class="flex gap-2"><input class="flex-1 rounded-md border bg-transparent px-2 py-1 text-sm" value={block.text} placeholder="Button label" disabled={readonly} onchange={(e)=>patch({text:e.currentTarget.value})}/><input class="flex-1 rounded-md border bg-transparent px-2 py-1 text-sm" value={block.url??""} placeholder="URL" disabled={readonly} onchange={(e)=>patch({url:e.currentTarget.value})}/></div>
{:else if block.type === "toc"}<div class="rounded-lg bg-muted/40 p-3 text-sm text-muted-foreground">Table of contents is derived from page headings.</div>
{:else if block.type === "synced"}<div class="rounded-lg border-l-2 border-brand bg-muted/20 p-3 text-sm">{block.text||"Synced block"}</div>
{:else}<textarea class="min-h-12 w-full resize-y bg-transparent text-sm outline-none" value={block.text} disabled={readonly} oninput={(e)=>patch({text:e.currentTarget.value})}></textarea>{/if}
