/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-registry.ts
 * Source of truth: frontend/slices/[feature]/config.ts
 *
 * To update this file, modify feature config files and run:
 *   pnpm run sync:all
 */

import type { FeatureConfig } from './defineFeature'

import overviewConfig from '@/frontend/slices/overview/config'
import communicationsConfig from '@/frontend/slices/communications/config'
import statusConfig from '@/frontend/slices/status/config'
import aiConfig from '@/frontend/slices/ai/config'
import contactsConfig from '@/frontend/slices/contacts/config'
import knowledgeConfig from '@/frontend/slices/knowledge/config'
import workspaceStoreConfig from '@/frontend/slices/workspace-store/config'
import databaseConfig from '@/frontend/slices/database/config'
import documentsConfig from '@/frontend/slices/documents/config'
import menusConfig from '@/frontend/slices/menus/config'
import calendarConfig from '@/frontend/slices/calendar/config'
import reportsConfig from '@/frontend/slices/reports/config'
import userManagementConfig from '@/frontend/slices/user-management/config'
import tasksConfig from '@/frontend/slices/tasks/config'
import formsConfig from '@/frontend/slices/forms/config'
import approvalsConfig from '@/frontend/slices/approvals/config'
import supportConfig from '@/frontend/slices/support/config'
import projectsConfig from '@/frontend/slices/projects/config'
import auditLogConfig from '@/frontend/slices/audit-log/config'
import importExportConfig from '@/frontend/slices/import-export/config'
import integrationsConfig from '@/frontend/slices/integrations/config'
import posConfig from '@/frontend/slices/pos/config'
import studioConfig from '@/frontend/slices/studio/config'
import marketingConfig from '@/frontend/slices/marketing/config'
import analyticsConfig from '@/frontend/slices/analytics/config'
import biConfig from '@/frontend/slices/bi/config'
import salesConfig from '@/frontend/slices/sales/config'
import guestBookingConfig from '@/frontend/slices/guest-booking/config'
import staffOperationsConfig from '@/frontend/slices/staff-operations/config'
import ownerAnalyticsConfig from '@/frontend/slices/owner-analytics/config'
import industryTemplatesConfig from '@/frontend/slices/industry-templates/config'
import hrConfig from '@/frontend/slices/hr/config'
import contentConfig from '@/frontend/slices/content/config'
import cmsLiteConfig from '@/frontend/slices/cms-lite/config'
import pettyCashConfig from '@/frontend/slices/petty-cash/config'
import accountingConfig from '@/frontend/slices/accounting/config'
import dailyClosingConfig from '@/frontend/slices/daily-closing/config'
import kpiThresholdsConfig from '@/frontend/slices/kpi-thresholds/config'
import damageReportsConfig from '@/frontend/slices/damage-reports/config'
import ownerTransfersConfig from '@/frontend/slices/owner-transfers/config'
import customerLoyaltyConfig from '@/frontend/slices/customer-loyalty/config'
import assetManagementConfig from '@/frontend/slices/asset-management/config'
import cashFlowForecastConfig from '@/frontend/slices/cash-flow-forecast/config'
import operationalChecklistConfig from '@/frontend/slices/operational-checklist/config'
import branchHealthScoringConfig from '@/frontend/slices/branch-health-scoring/config'
import maintenanceSchedulingConfig from '@/frontend/slices/maintenance-scheduling/config'
import inventoryConfig from '@/frontend/slices/inventory/config'
import crmConfig from '@/frontend/slices/crm/config'
import exampleConfig from '@/frontend/slices/example/config'
import platformAdminConfig from '@/frontend/slices/platform-admin/config'

const featureConfigs: FeatureConfig[] = [
  overviewConfig,
  communicationsConfig,
  statusConfig,
  aiConfig,
  contactsConfig,
  knowledgeConfig,
  workspaceStoreConfig,
  databaseConfig,
  documentsConfig,
  menusConfig,
  calendarConfig,
  reportsConfig,
  userManagementConfig,
  tasksConfig,
  formsConfig,
  approvalsConfig,
  supportConfig,
  projectsConfig,
  auditLogConfig,
  importExportConfig,
  integrationsConfig,
  posConfig,
  studioConfig,
  marketingConfig,
  analyticsConfig,
  biConfig,
  salesConfig,
  guestBookingConfig,
  staffOperationsConfig,
  ownerAnalyticsConfig,
  industryTemplatesConfig,
  hrConfig,
  contentConfig,
  cmsLiteConfig,
  pettyCashConfig,
  accountingConfig,
  dailyClosingConfig,
  kpiThresholdsConfig,
  damageReportsConfig,
  ownerTransfersConfig,
  customerLoyaltyConfig,
  assetManagementConfig,
  cashFlowForecastConfig,
  operationalChecklistConfig,
  branchHealthScoringConfig,
  maintenanceSchedulingConfig,
  inventoryConfig,
  crmConfig,
  exampleConfig,
  platformAdminConfig,
]
/**
 * Extract and validate all discovered features
 */
export const DISCOVERED_FEATURES: FeatureConfig[] = [...featureConfigs].sort(
  (a, b) => a.ui.order - b.ui.order
)

/**
 * Get all registered features
 */
export function getAllFeatures(): FeatureConfig[] {
  return DISCOVERED_FEATURES
}

/**
 * Get feature by ID
 */
export function getFeatureById(id: string): FeatureConfig | undefined {
  const findFeature = (features: FeatureConfig[]): FeatureConfig | undefined => {
    for (const feature of features) {
      if (feature.id === id) return feature
      if (feature.children) {
        const found = findFeature(feature.children)
        if (found) return found
      }
    }
    return undefined
  }
  return findFeature(DISCOVERED_FEATURES)
}

/**
 * Get features by category
 */
export function getFeaturesByCategory(category: string): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.ui.category === category)
}

/**
 * Get features by type (default, optional, etc.)
 */
export function getFeaturesByType(
  type: 'default' | 'system' | 'optional' | 'experimental'
): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.technical.featureType === type)
}

/**
 * Get features by status
 */
export function getFeaturesByStatus(
  status: 'stable' | 'beta' | 'development' | 'experimental' | 'deprecated'
): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.status.state === status)
}

/**
 * Get all ready features (isReady = true)
 */
export function getReadyFeatures(): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.status.isReady)
}

/**
 * Get all feature IDs (flat list)
 */
export function getAllFeatureIds(): string[] {
  const collectIds = (features: FeatureConfig[]): string[] => {
    return features.flatMap(f => [f.id, ...(f.children ? collectIds(f.children) : [])])
  }
  return collectIds(DISCOVERED_FEATURES)
}

/**
 * Get features by bundle ID and role
 * @param bundleId - The bundle ID to filter by
 * @param role - Optional: 'core' | 'recommended' | 'optional'
 */
export function getFeaturesByBundle(
  bundleId: string,
  role?: 'core' | 'recommended' | 'optional'
): FeatureConfig[] {
  const flattenFeatures = (features: FeatureConfig[]): FeatureConfig[] => {
    return features.flatMap(f => [f, ...(f.children ? flattenFeatures(f.children) : [])])
  }
  
  return flattenFeatures(DISCOVERED_FEATURES).filter(feature => {
    if (!feature.bundles) return false
    
    if (role) {
      return feature.bundles[role]?.includes(bundleId as any) ?? false
    }
    
    return (
      feature.bundles.core?.includes(bundleId as any) ||
      feature.bundles.recommended?.includes(bundleId as any) ||
      feature.bundles.optional?.includes(bundleId as any)
    )
  })
}

/**
 * Get core features for a bundle (cannot be disabled)
 */
export function getBundleCoreFeatures(bundleId: string): FeatureConfig[] {
  return getFeaturesByBundle(bundleId, 'core')
}

/**
 * Get recommended features for a bundle (enabled by default)
 */
export function getBundleRecommendedFeatures(bundleId: string): FeatureConfig[] {
  return getFeaturesByBundle(bundleId, 'recommended')
}

/**
 * Get optional features for a bundle (disabled by default)
 */
export function getBundleOptionalFeatures(bundleId: string): FeatureConfig[] {
  return getFeaturesByBundle(bundleId, 'optional')
}

/**
 * Validate registry for duplicates and issues
 */
export function validateRegistry(): { valid: boolean; errors: string[] } {
  const errors: string[] = []
  const ids = getAllFeatureIds()
  const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index)

  if (duplicates.length > 0) {
    errors.push(`Duplicate feature IDs found: ${duplicates.join(', ')}`)
  }

  const paths = DISCOVERED_FEATURES.map(f => f.ui.path)
  const duplicatePaths = paths.filter((path, index) => paths.indexOf(path) !== index)
  if (duplicatePaths.length > 0) {
    errors.push(`Duplicate paths found: ${duplicatePaths.join(', ')}`)
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}

/**
 * Backward compatibility exports
 * @deprecated Use DISCOVERED_FEATURES instead
 */
export const FEATURES_REGISTRY = DISCOVERED_FEATURES

/**
 * Convert to the legacy feature metadata format used by features.config.ts
 * @deprecated Will be removed when legacy manifest is retired
 */
export function toLegacyFormat() {
  return DISCOVERED_FEATURES.map(f => ({
    slug: f.id,
    name: f.name,
    description: f.description,
    featureType: f.technical.featureType,
    category: f.ui.category,
    icon: f.ui.icon,
    path: f.ui.path,
    component: f.ui.component,
    order: f.ui.order,
    type: 'route' as const,
    version: f.technical.version,
    hasUI: f.technical.hasUI,
    hasConvex: f.technical.hasConvex,
    hasTests: f.technical.hasTests,
    generationMode: f.generation.mode,
    sharedEngineId: f.generation.sharedEngineId,
    tags: f.tags,
    status: f.status.state,
    isReady: f.status.isReady,
    children: f.children?.map(c => ({
      slug: c.id,
      name: c.name,
      description: c.description,
      featureType: c.technical.featureType,
      category: c.ui.category,
      icon: c.ui.icon,
      path: c.ui.path,
      component: c.ui.component,
      order: c.ui.order,
      type: 'route' as const,
      version: c.technical.version,
      hasUI: c.technical.hasUI,
      hasConvex: c.technical.hasConvex,
      hasTests: c.technical.hasTests,
      generationMode: c.generation.mode,
      sharedEngineId: c.generation.sharedEngineId,
    })),
  }))
}

if (process.env.NODE_ENV !== 'production') {
  const validation = validateRegistry()
  if (!validation.valid) {
    console.error('Feature Registry Validation Failed:')
    validation.errors.forEach(err => console.error(`  - ${err}`))
  } else {
    console.log(`Feature Registry: ${DISCOVERED_FEATURES.length} features discovered`)
  }
}

