/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/features/generate-manifest.ts
 * Source of truth: frontend/slices/[feature]/config.ts via registry.server.ts
 *
 * To update this file:
 *   1. Edit the relevant frontend/slices/{slug}/config.ts
 *   2. Run: pnpm run generate:manifest
 */

"use client"

import type { Id } from "@convex/_generated/dataModel"
import type { ElementType, ReactElement } from "react"
import { lazy } from "react"

import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  ArrowUpDown,
  Award,
  BarChart,
  BarChart3,
  BedDouble,
  BookOpen,
  Bot,
  Box,
  Building2,
  Calculator,
  Calendar,
  Camera,
  CheckCircle,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Contact,
  Database,
  DollarSign,
  FileText,
  FolderKanban,
  Gauge,
  Headphones,
  History,
  Home,
  Layers3,
  LayoutTemplate,
  Library,
  Lightbulb,
  LineChart,
  Megaphone,
  Menu,
  MessageSquare,
  Package,
  Plug,
  Shield,
  ShoppingCart,
  TrendingUp,
  UserCog,
  Users,
  Wallet,
  Wrench
} from "lucide-react"

export type AppPageComponent = (props: { workspaceId?: Id<"workspaces"> | null }) => ReactElement | null

export interface PageManifestItem {
  id: string
  componentId: string
  title: string
  description?: string
  icon?: ElementType
  color?: string
  component: React.LazyExoticComponent<React.ComponentType<any>>
  path: string
  aliases?: string[]
  patterns?: Record<string, string>
}

export const DEFAULT_PAGE_MANIFEST: PageManifestItem[] = [
  {
    id: "overview",
    componentId: "OverviewPage",
    title: "Overview",
    description: "Dashboard overview with analytics and insights",
    icon: Home,
    component: lazy(() => import("@/frontend/slices/overview/page")),
    path: "/dashboard/overview",
    aliases: ["dashboard"],
    patterns: undefined,
  },
  {
    id: "communications",
    componentId: "CommunicationsPage",
    title: "Communications",
    description: "Unified communication platform with channels, direct messages, voice/video calls, and AI integrations",
    icon: MessageSquare,
    component: lazy(() => import("@/frontend/slices/communications/page")),
    path: "/dashboard/communications",
    aliases: ["message", "chat"],
    patterns: undefined,
  },
  {
    id: "status",
    componentId: "StatusPage",
    title: "Status",
    description: "Share status updates with your team",
    icon: Camera,
    component: lazy(() => import("@/frontend/slices/status/page")),
    path: "/dashboard/status",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "ai",
    componentId: "AIPage",
    title: "AI",
    description: "AI assistant",
    icon: Bot,
    component: lazy(() => import("@/frontend/slices/ai/page")),
    path: "/dashboard/ai",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "workspace-store",
    componentId: "WorkspaceStorePage",
    title: "Workspace Store",
    description: "Manage workspace hierarchy with nested workspaces, drag & drop, and tree visualization",
    icon: Building2,
    component: lazy(async () => {
        const module = await import("@/frontend/slices/workspace-store")
        const Component = module.WorkspaceStorePage
        if (!Component) {
          throw new Error("Failed to load component WorkspaceStorePage from @/frontend/slices/workspace-store")
        }
        return { default: Component }
      }),
    path: "/dashboard/workspace-store",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "knowledge",
    componentId: "KnowledgePage",
    title: "Knowledge",
    description: "Centralized knowledge base with documents, articles, and AI-consumable data",
    icon: BookOpen,
    component: lazy(() => import("@/frontend/slices/knowledge/page")),
    path: "/dashboard/knowledge",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "contacts",
    componentId: "ContactsPage",
    title: "Contacts",
    description: "Manage your contacts and connections",
    icon: Contact,
    component: lazy(() => import("@/frontend/slices/contacts/page")),
    path: "/dashboard/contacts",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "database",
    componentId: "DatabasesPage",
    title: "Database",
    description: "Notion-style database views and management",
    icon: Database,
    component: lazy(() => import("@/frontend/slices/database/page")),
    path: "/dashboard/database",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "documents",
    componentId: "DocumentsPage",
    title: "Documents",
    description: "Collaborative document editor with real-time sync (Deprecated - use Knowledge > Docs)",
    icon: FileText,
    component: lazy(() => import("@/frontend/slices/documents/page")),
    path: "/dashboard/documents",
    aliases: ["doc", "file"],
    patterns: {"file":"?file=:id"},
  },
  {
    id: "menus",
    componentId: "MenuStorePage",
    title: "Menu Store",
    description: "Install and manage navigation menus",
    icon: Menu,
    component: lazy(async () => {
        const module = await import("@/frontend/slices/menus")
        const Component = module.MenuStorePage
        if (!Component) {
          throw new Error("Failed to load component MenuStorePage from @/frontend/slices/menus")
        }
        return { default: Component }
      }),
    path: "/dashboard/menus",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "calendar",
    componentId: "CalendarPage",
    title: "Calendar",
    description: "Team calendar with event management and scheduling",
    icon: Calendar,
    component: lazy(() => import("@/frontend/slices/calendar/page")),
    path: "/dashboard/calendar",
    aliases: ["event", "deadline"],
    patterns: {"event":"event/:id"},
  },
  {
    id: "user-management",
    componentId: "UserManagementPage",
    title: "User Management",
    description: "Unified user management: members, teams, invitations, and role hierarchy",
    icon: UserCog,
    component: lazy(() => import("@/frontend/slices/user-management/page")),
    path: "/dashboard/user-management",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "reports",
    componentId: "ReportsPage",
    title: "Reports",
    description: "Analytics and reporting dashboard",
    icon: BarChart,
    component: lazy(() => import("@/frontend/slices/reports/page")),
    path: "/dashboard/reports",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "tasks",
    componentId: "TasksPage",
    title: "Tasks",
    description: "Task management and tracking",
    icon: CheckSquare,
    component: lazy(() => import("@/frontend/slices/tasks/page")),
    path: "/dashboard/tasks",
    aliases: ["task"],
    patterns: {"task":"?id=:id"},
  },
  {
    id: "forms",
    componentId: "FormsPage",
    title: "Forms",
    description: "Build custom forms for data collection",
    icon: FileText,
    component: lazy(() => import("@/frontend/slices/forms/page")),
    path: "/dashboard/forms",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "approvals",
    componentId: "ApprovalsPage",
    title: "Approvals",
    description: "Approval workflows and request management",
    icon: CheckCircle,
    component: lazy(() => import("@/frontend/slices/approvals/page")),
    path: "/dashboard/approvals",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "support",
    componentId: "SupportPage",
    title: "Support",
    description: "Customer support and helpdesk ticketing system",
    icon: Headphones,
    component: lazy(() => import("@/frontend/slices/support/page")),
    path: "/dashboard/support",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "projects",
    componentId: "ProjectsPage",
    title: "Projects",
    description: "Project management with team discussions",
    icon: FolderKanban,
    component: lazy(() => import("@/frontend/slices/projects/page")),
    path: "/dashboard/projects",
    aliases: ["project"],
    patterns: {"project":":id"},
  },
  {
    id: "audit-log",
    componentId: "AuditLogPage",
    title: "Audit Log",
    description: "View activity logs and audit trail",
    icon: History,
    component: lazy(() => import("@/frontend/slices/audit-log/page")),
    path: "/dashboard/audit-log",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "import-export",
    componentId: "ImportExportPage",
    title: "Import/Export",
    description: "Import and export data across workspace",
    icon: ArrowUpDown,
    component: lazy(() => import("@/frontend/slices/import-export/page")),
    path: "/dashboard/import-export",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "integrations",
    componentId: "IntegrationsPage",
    title: "Integrations",
    description: "Connect with third-party services and APIs",
    icon: Plug,
    component: lazy(() => import("@/frontend/slices/integrations/page")),
    path: "/dashboard/integrations",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "pos",
    componentId: "PosPage",
    title: "POS",
    description: "Point of Sale and retail management",
    icon: ShoppingCart,
    component: lazy(() => import("@/frontend/slices/pos/page")),
    path: "/dashboard/pos",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "studio",
    componentId: "StudioPage",
    title: "Studio",
    description: "Unified visual builder combining UI design and workflow automation in a single canvas",
    icon: Layers3,
    component: lazy(() => import("@/frontend/slices/studio/page")),
    path: "/dashboard/studio",
    aliases: ["builder", "automation"],
    patterns: undefined,
  },
  {
    id: "marketing",
    componentId: "MarketingPage",
    title: "Marketing",
    description: "Marketing automation and campaign management",
    icon: Megaphone,
    component: lazy(() => import("@/frontend/slices/marketing/page")),
    path: "/dashboard/marketing",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "analytics",
    componentId: "AnalyticsPage",
    title: "Analytics",
    description: "Monitor your business performance with real-time analytics",
    icon: BarChart3,
    component: lazy(() => import("@/frontend/slices/analytics/page")),
    path: "/dashboard/analytics",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "analytics-dashboard",
    componentId: "AnalyticsDashboardPage",
    title: "Dashboard",
    description: "Overview of key metrics",
    icon: TrendingUp,
    component: lazy(() => import("@/frontend/slices/analytics/page")),
    path: "/dashboard/analytics/dashboard",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "analytics-reports",
    componentId: "AnalyticsReportsPage",
    title: "Reports",
    description: "Generate detailed reports",
    icon: FileText,
    component: lazy(() => import("@/frontend/slices/analytics/page")),
    path: "/dashboard/analytics/reports",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "bi",
    componentId: "BiPage",
    title: "Business Intelligence",
    description: "Advanced analytics and business intelligence",
    icon: LineChart,
    component: lazy(() => import("@/frontend/slices/bi/page")),
    path: "/dashboard/bi",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "sales",
    componentId: "SalesPage",
    title: "Sales",
    description: "Sales management and pipeline tracking",
    icon: DollarSign,
    component: lazy(() => import("@/frontend/slices/sales/page")),
    path: "/dashboard/sales",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "guest-booking",
    componentId: "GuestBookingPage",
    title: "Guest Booking",
    description: "Hotel guest self-service lifecycle with Syariah-compliance verification",
    icon: BedDouble,
    component: lazy(() => import("@/frontend/slices/guest-booking/page")),
    path: "/dashboard/guest-booking",
    aliases: ["booking", "reservation", "stay"],
    patterns: {"booking":"booking/:id","verification":"verification/:id"},
  },
  {
    id: "staff-operations",
    componentId: "StaffOperationsPage",
    title: "Staff Operations",
    description: "Housekeeping, laundry, damage reports, and shift scheduling for hospitality ops",
    icon: ClipboardList,
    component: lazy(() => import("@/frontend/slices/staff-operations/page")),
    path: "/dashboard/staff-operations",
    aliases: ["housekeeping", "laundry", "shift"],
    patterns: {"task":"task/:id","damage":"damage/:id"},
  },
  {
    id: "owner-analytics",
    componentId: "OwnerAnalyticsPage",
    title: "Owner Analytics",
    description: "Strategic financial dashboards, channel mix, and asset expansion tracking for property owners",
    icon: TrendingUp,
    component: lazy(() => import("@/frontend/slices/owner-analytics/page")),
    path: "/dashboard/owner-analytics",
    aliases: ["revenue", "kpi", "expansion"],
    patterns: {"project":"project/:id"},
  },
  {
    id: "industry-templates",
    componentId: "IndustryTemplatesPage",
    title: "Industry Templates",
    description: "Pre-configured workspace bundles for specific industries — get started in seconds with role-specific features, workflows, and settings",
    icon: LayoutTemplate,
    component: lazy(() => import("@/frontend/slices/industry-templates/page")),
    path: "/dashboard/industry-templates",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "petty-cash",
    componentId: "PettyCashPage",
    title: "Petty Cash",
    description: "Cash-on-hand request → approval → disbursement → close workflow with variance tracking.",
    icon: Wallet,
    component: lazy(() => import("@/frontend/slices/petty-cash/page")),
    path: "/dashboard/petty-cash",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "owner-transfers",
    componentId: "OwnerTransfersPage",
    title: "Owner Transfers",
    description: "Track owner capital movements: withdrawals, injections, loans, and repayments.",
    icon: ArrowLeftRight,
    component: lazy(() => import("@/frontend/slices/owner-transfers/page")),
    path: "/dashboard/owner-transfers",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "operational-checklist",
    componentId: "OperationalChecklistPage",
    title: "Operational Checklist",
    description: "Build operational checklists and run them through the daily/audit workflow with photo + notes capture.",
    icon: ClipboardCheck,
    component: lazy(() => import("@/frontend/slices/operational-checklist/page")),
    path: "/dashboard/operational-checklist",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "maintenance-scheduling",
    componentId: "MaintenanceSchedulingPage",
    title: "Maintenance Scheduling",
    description: "Preventive and reactive maintenance with recurring schedules and cost tracking.",
    icon: Wrench,
    component: lazy(() => import("@/frontend/slices/maintenance-scheduling/page")),
    path: "/dashboard/maintenance-scheduling",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "kpi-thresholds",
    componentId: "KpiThresholdsPage",
    title: "Kpi Thresholds",
    description: "Define KPI alert thresholds and triage triggered alerts across branches.",
    icon: Gauge,
    component: lazy(() => import("@/frontend/slices/kpi-thresholds/page")),
    path: "/dashboard/kpi-thresholds",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "hr",
    componentId: "hrPage",
    title: "HR Management",
    description: "Human Resources Management",
    icon: Users,
    component: lazy(() => import("@/frontend/slices/hr/page")),
    path: "/dashboard/hr",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "damage-reports",
    componentId: "DamageReportsPage",
    title: "Damage Reports",
    description: "Report and track damage incidents from reported to resolved.",
    icon: AlertTriangle,
    component: lazy(() => import("@/frontend/slices/damage-reports/page")),
    path: "/dashboard/damage-reports",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "daily-closing",
    componentId: "DailyClosingPage",
    title: "Daily Closing",
    description: "End-of-day register close with per-payment-method variance and approval workflow.",
    icon: ClipboardList,
    component: lazy(() => import("@/frontend/slices/daily-closing/page")),
    path: "/dashboard/daily-closing",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "customer-loyalty",
    componentId: "CustomerLoyaltyPage",
    title: "Customer Loyalty",
    description: "Customer loyalty program with tiered memberships and a points transaction ledger.",
    icon: Award,
    component: lazy(() => import("@/frontend/slices/customer-loyalty/page")),
    path: "/dashboard/customer-loyalty",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "content",
    componentId: "ContentPage",
    title: "Content Library",
    description: "Centralized content management for images, videos, audio, and documents with AI generation capabilities.",
    icon: Library,
    component: lazy(() => import("@/frontend/slices/content/page")),
    path: "/dashboard/content",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "cms-lite",
    componentId: "CmsLitePage",
    title: "CMS Lite",
    description: "Lightweight CMS for managing website content, blog posts, and landing pages.",
    icon: Box,
    component: lazy(() => import("@/frontend/slices/cms-lite/page")),
    path: "/dashboard/cms-lite",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "cash-flow-forecast",
    componentId: "CashFlowForecastPage",
    title: "Cash Flow Forecast",
    description: "Build cash-flow forecasts from bucketed revenue and expense line items.",
    icon: TrendingUp,
    component: lazy(() => import("@/frontend/slices/cash-flow-forecast/page")),
    path: "/dashboard/cash-flow-forecast",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "branch-health-scoring",
    componentId: "BranchHealthScoringPage",
    title: "Branch Health Scoring",
    description: "Capture branch health snapshots across revenue, expense, ops, staff, and customer scores.",
    icon: Activity,
    component: lazy(() => import("@/frontend/slices/branch-health-scoring/page")),
    path: "/dashboard/branch-health-scoring",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "asset-management",
    componentId: "AssetManagementPage",
    title: "Asset Management",
    description: "Track fixed assets with location, assignment, depreciation and transaction ledger.",
    icon: Package,
    component: lazy(() => import("@/frontend/slices/asset-management/page")),
    path: "/dashboard/asset-management",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "accounting",
    componentId: "accountingPage",
    title: "Accounting",
    description: "Financial Management and Accounting",
    icon: Calculator,
    component: lazy(() => import("@/frontend/slices/accounting/page")),
    path: "/dashboard/accounting",
    aliases: ["finance"],
    patterns: {"invoice":"invoices/:id","expense":"expenses/:id"},
  },
  {
    id: "inventory",
    componentId: "InventoryPage",
    title: "Inventory Management",
    description: "Comprehensive inventory management with multi-warehouse support, stock tracking, and demand forecasting",
    icon: Package,
    component: lazy(() => import("@/frontend/slices/inventory/page")),
    path: "/dashboard/erp/inventory",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "crm",
    componentId: "CrmPage",
    title: "CRM",
    description: "Customer Relationship Management with contacts, leads, opportunities, and sales pipeline",
    icon: Users,
    component: lazy(() => import("@/frontend/slices/crm/page")),
    path: "/dashboard/erp/crm",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "platform-admin",
    componentId: "PlatformAdminPage",
    title: "Platform Admin",
    description: "Super Admin panel for managing features, workspaces, and system configuration",
    icon: Shield,
    component: lazy(() => import("@/frontend/slices/platform-admin/page")),
    path: "/dashboard/platform-admin",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "example",
    componentId: "ExamplePage",
    title: "Example Feature",
    description: "A minimal example feature demonstrating SuperSpace patterns and conventions",
    icon: Lightbulb,
    component: lazy(() => import("@/frontend/slices/example/page")),
    path: "/dashboard/example",
    aliases: undefined,
    patterns: undefined,
  }
]

export const PAGE_MANIFEST_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.id, p]),
)

export const COMPONENT_REGISTRY_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.componentId, p]),
)

export const RESOURCE_TO_FEATURE_MAP: Record<string, string> = {
  "dashboard": "overview",
  "message": "communications",
  "chat": "communications",
  "doc": "documents",
  "file": "documents",
  "event": "calendar",
  "deadline": "calendar",
  "task": "tasks",
  "project": "projects",
  "builder": "studio",
  "automation": "studio",
  "booking": "guest-booking",
  "reservation": "guest-booking",
  "stay": "guest-booking",
  "verification": "guest-booking",
  "housekeeping": "staff-operations",
  "laundry": "staff-operations",
  "shift": "staff-operations",
  "damage": "staff-operations",
  "revenue": "owner-analytics",
  "kpi": "owner-analytics",
  "expansion": "owner-analytics",
  "finance": "accounting",
  "invoice": "accounting",
  "expense": "accounting"
}

export function getDefaultPages(): PageManifestItem[] {
  return DEFAULT_PAGE_MANIFEST
}

export function getPageById(id: string): PageManifestItem | undefined {
  return DEFAULT_PAGE_MANIFEST.find((p) => p.id === id)
}

export function getComponentById(componentId: string): PageManifestItem | undefined {
  return COMPONENT_REGISTRY_MAP[componentId]
}

interface AppContentProps {
  workspaceId?: Id<"workspaces"> | null
  activeView: string
}

export function AppContent({ workspaceId, activeView }: AppContentProps) {
  const fallbackPage =
    DEFAULT_PAGE_MANIFEST.find((p) => p.id === activeView) ?? DEFAULT_PAGE_MANIFEST.find((p) => p.id === "overview")

  if (!fallbackPage) {
    return <div className="flex-1 p-8">Page not found: {activeView}</div>
  }

  const Comp = fallbackPage.component
  return (
    <div className="flex-1 overflow-hidden">
      <Comp workspaceId={workspaceId ?? null} />
    </div>
  )
}
