/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/features/generate-manifest.ts
 * Source of truth: frontend/slices/[feature]/config.ts via registry.server.ts
 *
 * To update this file:
 *   1. Edit the relevant frontend/slices/{slug}/config.ts
 *   2. Run: pnpm run generate:manifest
 */

"use client"

import type { Id } from "@convex/_generated/dataModel"
import type { ElementType, ReactElement } from "react"
import { lazy } from "react"

import {
  Layers3,
  Lightbulb
} from "lucide-react"

export type AppPageComponent = (props: { workspaceId?: Id<"workspaces"> | null }) => ReactElement | null

export interface PageManifestItem {
  id: string
  componentId: string
  title: string
  description?: string
  icon?: ElementType
  color?: string
  component: React.LazyExoticComponent<React.ComponentType<any>>
  path: string
  aliases?: string[]
  patterns?: Record<string, string>
}

export const DEFAULT_PAGE_MANIFEST: PageManifestItem[] = [
  {
    id: "studio",
    componentId: "StudioPage",
    title: "Studio",
    description: "Unified visual builder combining UI design and workflow automation in a single canvas",
    icon: Layers3,
    component: lazy(() => import("@/frontend/slices/studio/page")),
    path: "/dashboard/studio",
    aliases: ["builder", "automation"],
    patterns: undefined,
  },
  {
    id: "example",
    componentId: "ExamplePage",
    title: "Example Feature",
    description: "A minimal example feature demonstrating SuperSpace patterns and conventions",
    icon: Lightbulb,
    component: lazy(() => import("@/frontend/slices/example/page")),
    path: "/dashboard/example",
    aliases: undefined,
    patterns: undefined,
  }
]

export const PAGE_MANIFEST_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.id, p]),
)

export const COMPONENT_REGISTRY_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.componentId, p]),
)

export const RESOURCE_TO_FEATURE_MAP: Record<string, string> = {
  "builder": "studio",
  "automation": "studio"
}

export function getDefaultPages(): PageManifestItem[] {
  return DEFAULT_PAGE_MANIFEST
}

export function getPageById(id: string): PageManifestItem | undefined {
  return DEFAULT_PAGE_MANIFEST.find((p) => p.id === id)
}

export function getComponentById(componentId: string): PageManifestItem | undefined {
  return COMPONENT_REGISTRY_MAP[componentId]
}

interface AppContentProps {
  workspaceId?: Id<"workspaces"> | null
  activeView: string
}

export function AppContent({ workspaceId, activeView }: AppContentProps) {
  const fallbackPage =
    DEFAULT_PAGE_MANIFEST.find((p) => p.id === activeView) ?? DEFAULT_PAGE_MANIFEST.find((p) => p.id === "overview")

  if (!fallbackPage) {
    return <div className="flex-1 p-8">Page not found: {activeView}</div>
  }

  const Comp = fallbackPage.component
  return (
    <div className="flex-1 overflow-hidden">
      <Comp workspaceId={workspaceId ?? null} />
    </div>
  )
}
