/* eslint-disable max-lines */

import { createTemplate } from '../shared';

const createSaaSProductLandingTemplate = () => createTemplate({
    'page': { type: 'section', props: { path: '/', className: 'bg-zinc-950 text-white' }, children: ['wrap'] },
    'wrap': { type: 'div', props: { className: 'flex flex-col' }, children: ['nav', 'hero', 'logos', 'platform', 'stories', 'pricing', 'final'] },

    'nav': { type: 'div', props: { className: 'flex flex-row items-center justify-between px-8 py-6 max-w-6xl mx-auto w-full' }, children: ['brand', 'nav-links', 'nav-actions'] },
    'brand': { type: 'text', props: { tag: 'span', content: 'SIGNALOS', className: 'text-lg font-black tracking-[0.32em] text-cyan-300' }, children: [] },
    'nav-links': { type: 'div', props: { className: 'hidden md:flex flex-row items-center gap-6 text-sm text-zinc-400' }, children: ['nav-l1', 'nav-l2', 'nav-l3'] },
    'nav-l1': { type: 'text', props: { tag: 'span', content: 'Product', className: 'hover:text-white cursor-pointer transition-colors' }, children: [] },
    'nav-l2': { type: 'text', props: { tag: 'span', content: 'Customers', className: 'hover:text-white cursor-pointer transition-colors' }, children: [] },
    'nav-l3': { type: 'text', props: { tag: 'span', content: 'Pricing', className: 'hover:text-white cursor-pointer transition-colors' }, children: [] },
    'nav-actions': { type: 'div', props: { className: 'flex flex-row gap-3 items-center' }, children: ['nav-login', 'nav-cta'] },
    'nav-login': { type: 'button', props: { text: 'Book Demo', variant: 'ghost', className: 'text-zinc-300 hover:text-white' }, children: [] },
    'nav-cta': { type: 'button', props: { text: 'Start Free', size: 'lg', className: 'bg-cyan-300 text-zinc-950 hover:bg-cyan-200 font-semibold' }, children: [] },

    'hero': { type: 'div', props: { className: 'px-8 pb-20 pt-8' }, children: ['hero-shell'] },
    'hero-shell': { type: 'div', props: { className: 'max-w-6xl mx-auto grid lg:grid-cols-2 gap-10 items-center' }, children: ['hero-copy', 'hero-visual'] },
    'hero-copy': { type: 'div', props: { className: 'flex flex-col gap-6' }, children: ['hero-label', 'hero-title', 'hero-body', 'hero-actions', 'hero-proof'] },
    'hero-label': { type: 'text', props: { tag: 'span', content: 'Workflow OS for revenue teams', className: 'inline-flex w-fit rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200' }, children: [] },
    'hero-title': { type: 'text', props: { tag: 'h1', content: 'Close deals faster with one operating system for pipeline, handoff, and renewal.', className: 'max-w-2xl text-5xl md:text-6xl font-black leading-[1.02] tracking-tight' }, children: [] },
    'hero-body': { type: 'text', props: { tag: 'p', content: 'SignalOS replaces scattered dashboards with a command center that gives sales, onboarding, and customer success the same live source of truth.', className: 'max-w-xl text-lg leading-8 text-zinc-400' }, children: [] },
    'hero-actions': { type: 'div', props: { className: 'flex flex-row gap-4 flex-wrap' }, children: ['hero-primary', 'hero-secondary'] },
    'hero-primary': { type: 'button', props: { text: 'Start Free Workspace', size: 'lg', className: 'bg-white text-zinc-950 hover:bg-zinc-100 font-semibold px-8' }, children: [] },
    'hero-secondary': { type: 'button', props: { text: 'See Live Tour', variant: 'outline', size: 'lg', className: 'border-zinc-700 text-white hover:bg-zinc-900 px-8' }, children: [] },
    'hero-proof': { type: 'div', props: { className: 'grid grid-cols-3 gap-3 pt-3' }, children: ['proof-1', 'proof-2', 'proof-3'] },
    'proof-1': { type: 'card', props: { title: '34%', description: 'Faster deal cycles after replacing handoff spreadsheets.', className: 'bg-zinc-900/80 border border-zinc-800 rounded-2xl p-5 h-full' }, children: [] },
    'proof-2': { type: 'card', props: { title: '11 hrs', description: 'Saved weekly by leadership with automated health reporting.', className: 'bg-zinc-900/80 border border-zinc-800 rounded-2xl p-5 h-full' }, children: [] },
    'proof-3': { type: 'card', props: { title: '98%', description: 'Forecast accuracy with stage-by-stage visibility.', className: 'bg-zinc-900/80 border border-zinc-800 rounded-2xl p-5 h-full' }, children: [] },
    'hero-visual': { type: 'div', props: { className: 'relative' }, children: ['hero-image', 'hero-panel'] },
    'hero-image': { type: 'image', props: { src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', alt: 'SaaS dashboard preview', className: 'w-full rounded-[2rem] border border-white/10 shadow-[0_30px_90px_rgba(0,0,0,0.5)] object-cover' }, children: [] },
    'hero-panel': { type: 'div', props: { className: 'absolute -bottom-8 -left-4 max-w-sm rounded-3xl border border-cyan-300/20 bg-zinc-950/95 p-6 shadow-2xl backdrop-blur' }, children: ['panel-kicker', 'panel-title', 'panel-grid'] },
    'panel-kicker': { type: 'text', props: { tag: 'span', content: 'Live pipeline pulse', className: 'text-[11px] uppercase tracking-[0.24em] text-cyan-300' }, children: [] },
    'panel-title': { type: 'text', props: { tag: 'p', content: 'Every team sees the same revenue narrative, updated in real time.', className: 'mt-3 text-base font-semibold leading-7 text-white' }, children: [] },
    'panel-grid': { type: 'grid', props: { columns: '3', gap: 'sm', className: 'mt-5' }, children: ['panel-m1', 'panel-m2', 'panel-m3'] },
    'panel-m1': { type: 'card', props: { title: '$2.4M', description: 'Open pipeline', className: 'bg-zinc-900 border border-zinc-800 rounded-2xl p-4' }, children: [] },
    'panel-m2': { type: 'card', props: { title: '82%', description: 'On-time onboarding', className: 'bg-zinc-900 border border-zinc-800 rounded-2xl p-4' }, children: [] },
    'panel-m3': { type: 'card', props: { title: '9.4', description: 'CSAT this month', className: 'bg-zinc-900 border border-zinc-800 rounded-2xl p-4' }, children: [] },

    'logos': { type: 'div', props: { className: 'border-y border-white/5 px-8 py-8' }, children: ['logos-inner'] },
    'logos-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto flex flex-col gap-4' }, children: ['logos-label', 'logos-row'] },
    'logos-label': { type: 'text', props: { tag: 'p', content: 'Trusted by modern operating teams at', className: 'text-sm text-zinc-500' }, children: [] },
    'logos-row': { type: 'div', props: { className: 'grid grid-cols-2 md:grid-cols-5 gap-4 text-zinc-300 text-sm font-semibold uppercase tracking-[0.2em]' }, children: ['logo-1', 'logo-2', 'logo-3', 'logo-4', 'logo-5'] },
    'logo-1': { type: 'text', props: { tag: 'span', content: 'Northstar', className: '' }, children: [] },
    'logo-2': { type: 'text', props: { tag: 'span', content: 'Arcwell', className: '' }, children: [] },
    'logo-3': { type: 'text', props: { tag: 'span', content: 'RelayPay', className: '' }, children: [] },
    'logo-4': { type: 'text', props: { tag: 'span', content: 'Launchgrid', className: '' }, children: [] },
    'logo-5': { type: 'text', props: { tag: 'span', content: 'SummitOps', className: '' }, children: [] },

    'platform': { type: 'div', props: { className: 'px-8 py-24' }, children: ['platform-inner'] },
    'platform-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto flex flex-col gap-12' }, children: ['platform-head', 'platform-grid', 'platform-story'] },
    'platform-head': { type: 'div', props: { className: 'max-w-3xl flex flex-col gap-4' }, children: ['platform-label', 'platform-title', 'platform-copy'] },
    'platform-label': { type: 'text', props: { tag: 'span', content: 'Why teams switch', className: 'text-sm font-semibold uppercase tracking-[0.24em] text-cyan-300' }, children: [] },
    'platform-title': { type: 'text', props: { tag: 'h2', content: 'Built for teams that outgrew stitched-together tools.', className: 'text-4xl font-black tracking-tight' }, children: [] },
    'platform-copy': { type: 'text', props: { tag: 'p', content: 'Instead of six disconnected systems and one weekly spreadsheet ritual, SignalOS gives every team a single, operational view of revenue.', className: 'text-lg leading-8 text-zinc-400' }, children: [] },
    'platform-grid': { type: 'grid', props: { columns: '3', gap: 'md', className: '' }, children: ['platform-1', 'platform-2', 'platform-3'] },
    'platform-1': { type: 'card', props: { title: 'Shared context', description: 'Pipeline, onboarding, and renewals live in one flow so handoffs stop breaking.', className: 'bg-zinc-900 border border-zinc-800 rounded-3xl p-7 h-full' }, children: [] },
    'platform-2': { type: 'card', props: { title: 'Operator-grade reporting', description: 'Leadership sees lagging and leading indicators without waiting on manual reports.', className: 'bg-zinc-900 border border-zinc-800 rounded-3xl p-7 h-full' }, children: [] },
    'platform-3': { type: 'card', props: { title: 'Automated follow-through', description: 'Workflows trigger the next action when a deal moves, a launch slips, or churn risk spikes.', className: 'bg-zinc-900 border border-zinc-800 rounded-3xl p-7 h-full' }, children: [] },
    'platform-story': { type: 'div', props: { className: 'grid lg:grid-cols-[1.2fr_0.8fr] gap-6' }, children: ['story-quote', 'story-side'] },
    'story-quote': { type: 'div', props: { className: 'rounded-[2rem] border border-white/10 bg-gradient-to-br from-zinc-900 to-zinc-950 p-8 flex flex-col gap-5' }, children: ['story-quote-label', 'story-quote-copy', 'story-quote-author'] },
    'story-quote-label': { type: 'text', props: { tag: 'span', content: 'Customer story', className: 'text-sm uppercase tracking-[0.2em] text-cyan-300' }, children: [] },
    'story-quote-copy': { type: 'text', props: { tag: 'p', content: '"Before SignalOS, our sales and onboarding leaders were arguing over whose spreadsheet was correct. Now every call starts with the same live numbers."', className: 'text-2xl leading-10 font-medium text-white' }, children: [] },
    'story-quote-author': { type: 'text', props: { tag: 'p', content: 'Maya Fadel, COO at Northstar Cloud', className: 'text-sm text-zinc-400' }, children: [] },
    'story-side': { type: 'div', props: { className: 'grid grid-cols-1 gap-4' }, children: ['story-side-1', 'story-side-2'] },
    'story-side-1': { type: 'card', props: { title: '19 days', description: 'Average time from signed deal to go-live after rollout.', className: 'bg-white text-zinc-950 rounded-[2rem] p-7 h-full' }, children: [] },
    'story-side-2': { type: 'card', props: { title: '0 missed renewals', description: 'All at-risk accounts now trigger owner follow-up automatically.', className: 'bg-zinc-900 border border-zinc-800 rounded-[2rem] p-7 h-full' }, children: [] },

    'pricing': { type: 'div', props: { className: 'px-8 py-24 bg-zinc-900/60' }, children: ['pricing-inner'] },
    'pricing-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto flex flex-col gap-10' }, children: ['pricing-head', 'pricing-grid'] },
    'pricing-head': { type: 'div', props: { className: 'max-w-2xl flex flex-col gap-4' }, children: ['pricing-label', 'pricing-title', 'pricing-copy'] },
    'pricing-label': { type: 'text', props: { tag: 'span', content: 'Pricing', className: 'text-sm uppercase tracking-[0.2em] text-cyan-300' }, children: [] },
    'pricing-title': { type: 'text', props: { tag: 'h2', content: 'Choose the operating cadence your team needs.', className: 'text-4xl font-black tracking-tight' }, children: [] },
    'pricing-copy': { type: 'text', props: { tag: 'p', content: 'Every plan includes live dashboards, workflow automation, and collaborative handoff views.', className: 'text-lg text-zinc-400' }, children: [] },
    'pricing-grid': { type: 'grid', props: { columns: '3', gap: 'md', className: '' }, children: ['plan-1', 'plan-2', 'plan-3'] },
    'plan-1': { type: 'card', props: { title: 'Starter', description: '$29 per seat. Pipeline command center for lean GTM teams.', className: 'bg-zinc-950 border border-zinc-800 rounded-[2rem] p-8 h-full' }, children: [] },
    'plan-2': { type: 'card', props: { title: 'Growth', description: '$79 per seat. Adds onboarding, renewals, and live health automations.', className: 'bg-cyan-300 text-zinc-950 rounded-[2rem] p-8 h-full border-0' }, children: [] },
    'plan-3': { type: 'card', props: { title: 'Scale', description: 'Custom. Multi-region workspaces, dedicated SLA, and revenue ops advisory.', className: 'bg-zinc-950 border border-zinc-800 rounded-[2rem] p-8 h-full' }, children: [] },

    'final': { type: 'div', props: { className: 'px-8 py-24' }, children: ['final-inner'] },
    'final-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto rounded-[2.5rem] border border-white/10 bg-gradient-to-r from-cyan-400 to-sky-500 p-10 md:p-14 flex flex-col md:flex-row gap-8 items-start md:items-center justify-between' }, children: ['final-copy', 'final-cta'] },
    'final-copy': { type: 'div', props: { className: 'max-w-2xl flex flex-col gap-4' }, children: ['final-title', 'final-body'] },
    'final-title': { type: 'text', props: { tag: 'h2', content: 'Stop operating from screenshots and stale exports.', className: 'text-4xl font-black text-zinc-950 tracking-tight' }, children: [] },
    'final-body': { type: 'text', props: { tag: 'p', content: 'Move your pipeline, handoffs, and renewals into one system that keeps every team on the same page.', className: 'text-lg leading-8 text-zinc-900/80' }, children: [] },
    'final-cta': { type: 'button', props: { text: 'Launch Workspace', size: 'lg', className: 'bg-zinc-950 text-white hover:bg-black px-8 py-6 text-base font-semibold' }, children: [] },
  });

export default createSaaSProductLandingTemplate;
