<script lang="ts">
  import type {Database,DatabaseViewConfig,DbView,Page,PropertyType,PropertyValue} from "@/features/notion-ui/variants/database/types"; import {applyView} from "@/features/notion-ui/variants/database/lib/viewData"; import ViewRouter from "./views/ViewRouter.svelte";
  let {db,rows,readOnly=false,pages=[],onRowAdd,onRowUpdate,onRowRemove,onViewActivate,onViewAdd,onViewRemove,onViewConfigChange,onPropertyAdd,onOpenRow,onRowCreate,onRowAddInGroup}= $props<{db:Database;rows:Page[];readOnly?:boolean;pages?:Page[];onRowAdd?:()=>void;onRowUpdate?:(r:string,p:string,v:PropertyValue)=>void;onRowRemove?:(id:string)=>void;onViewActivate?:(id:string)=>void;onViewAdd?:(t:DbView)=>void;onViewRemove?:(id:string)=>void;onViewConfigChange?:(id:string,p:Partial<DatabaseViewConfig>)=>void;onPropertyAdd?:(t:PropertyType)=>void;onOpenRow?:(id:string)=>void;onRowCreate?:(d:{title:string;rowProps:Record<string,PropertyValue>})=>Promise<void>|void;onRowAddInGroup?:(a:{groupPropId:string;groupValue:string|null})=>void}>();
  let active=$derived(db.views.find(v=>v.id===db.activeViewId)??db.views[0]); let visible=$derived(active?applyView(rows,db,active):[]); const kinds:DbView[]=["table","board","list","gallery","calendar","feed","chart","dashboard","form","map","timeline"];
</script>
<section class="overflow-hidden rounded-lg border bg-card"><header class="flex items-center justify-between gap-3 border-b px-3 py-2"><div><h3 class="text-sm font-semibold">{db.icon} {db.name}</h3><p class="text-[10px] text-muted-foreground">{visible.length} / {rows.length} rows</p></div>{#if !readOnly}<div class="flex gap-1">{#if onPropertyAdd}<button class="rounded border px-2 py-1 text-xs" onclick={()=>onPropertyAdd?.("text")}>+ Property</button>{/if}{#if onRowAdd}<button class="rounded border px-2 py-1 text-xs" onclick={onRowAdd}>+ Row</button>{/if}</div>{/if}</header>
  {#if active}<div class="flex items-center gap-1 overflow-x-auto border-b p-1">{#each db.views as view (view.id)}<button class={`shrink-0 rounded px-2 py-1 text-xs ${view.id===active.id?"bg-muted font-medium":"hover:bg-muted/60"}`} onclick={()=>onViewActivate?.(view.id)}>{view.name}</button>{#if !readOnly&&onViewRemove&&db.views.length>1&&view.id===active.id}<button class="size-6 rounded text-xs hover:bg-muted" onclick={()=>onViewRemove?.(view.id)} aria-label="Remove view">×</button>{/if}{/each}{#if !readOnly&&onViewAdd}<select class="ml-1 rounded border bg-background px-2 py-1 text-xs" aria-label="Add view" onchange={(e)=>{if(e.currentTarget.value){onViewAdd?.(e.currentTarget.value as DbView);e.currentTarget.value="";}}}><option value="">+ View</option>{#each kinds as kind (kind)}<option value={kind}>{kind}</option>{/each}</select>{/if}<input class="ml-auto w-40 rounded border bg-background px-2 py-1 text-xs" value={active.search} placeholder="Search rows" oninput={(e)=>onViewConfigChange?.(active!.id,{search:e.currentTarget.value})}/></div>
  <ViewRouter {db} view={active} rows={visible} {readOnly} {pages} {onRowUpdate} {onRowRemove} {onOpenRow} {onRowCreate} {onRowAddInGroup}/>{:else}<p class="p-4 text-xs text-muted-foreground">No views configured.</p>{/if}
</section>
