import { v } from "convex/values";
import { internalMutation, internalQuery } from "../../_generated/server";
import type { Id } from "../../_generated/dataModel";
import { logAuditEvent } from "../../shared/audit";

/**
 * Check for breached SLAs and escalate or notify
 * Should be run by a cron job periodically (e.g. every hour)
 */
export const checkSLABreaches = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // 1. Check running workflow executions that have exceeded SLA
    const runningExecutions = await ctx.db
      .query("workflowExecutions")
      .withIndex("by_status", (q) => q.eq("status", "running"))
      .collect();

    for (const execution of runningExecutions) {
      const workflow = await ctx.db.get(execution.workflowId);
      if (!workflow || !workflow.definition?.settings?.slaDurationMs) continue;

      const slaDuration = workflow.definition.settings.slaDurationMs;
      const duration = now - execution.startedAt;

      if (duration > slaDuration) {
        // SLA Breached
        console.log(`SLA Breach: Execution ${execution._id} exceeded ${slaDuration}ms`);

        // Log breach
        const logs = execution.logs || [];
        logs.push({
          timestamp: now,
          level: "error",
          message: `SLA BREACH: Workflow exceeded max duration of ${slaDuration}ms`,
        });

        await ctx.db.patch(execution._id, { logs });

        // Audit: SLA breached
        await logAuditEvent(ctx, {
          workspaceId: execution.workspaceId,
          actorUserId: execution.triggeredBy,
          action: "studio.sla.breached",
          resourceType: "workflowExecution",
          resourceId: execution._id,
          metadata: {
            workflowId: execution.workflowId,
            workflowName: workflow.name,
            slaDurationMs: slaDuration,
            actualDurationMs: duration,
            exceededByMs: duration - slaDuration,
          },
        });

        // Notify workspace admins (placeholder logic)
        const notificationId = await ctx.db.insert("notifications", {
          workspaceId: execution.workspaceId,
          userId: execution.triggeredBy, // Notify triggerer for now
          createdBy: execution.triggeredBy, // System notification attributed to triggerer or system user
          type: "system",
          title: "SLA Breach Alert",
          message: `Workflow "${workflow.name}" has exceeded its SLA duration.`,
          isRead: false,
        });

        // Audit: SLA breach notification sent
        await logAuditEvent(ctx, {
          workspaceId: execution.workspaceId,
          actorUserId: execution.triggeredBy,
          action: "studio.sla.notified",
          resourceType: "notification",
          resourceId: notificationId,
          metadata: {
            workflowId: execution.workflowId,
            executionId: execution._id,
          },
        });

        // Escalation Logic: Reassign todo tasks created during this execution to an escalation user
        const settings = workflow.definition?.settings as {
          slaDurationMs?: number;
          maxRetries?: number;
          escalationUserId?: string;
        } | undefined;
        if (settings?.escalationUserId) {
            const escalationUserId = settings.escalationUserId as Id<"users">;

            // Query todo tasks for this workspace using the efficient compound index
            const pendingTasks = await ctx.db
                .query("tasks")
                .withIndex("by_workspace_status", (q) =>
                    q.eq("workspaceId", execution.workspaceId).eq("status", "todo")
                )
                .collect();

            // Heuristic: reassign tasks that were created after this execution started,
            // as these are most likely the tasks generated by this workflow run.
            let escalatedCount = 0;
            for (const task of pendingTasks) {
                if (task.createdAt >= execution.startedAt) {
                    await ctx.db.patch(task._id, {
                        assigneeId: escalationUserId,
                        updatedAt: now,
                        updatedBy: escalationUserId,
                    });
                    escalatedCount++;
                }
            }

            // Audit: SLA escalation triggered
            await logAuditEvent(ctx, {
              workspaceId: execution.workspaceId,
              actorUserId: execution.triggeredBy,
              action: "studio.sla.escalated",
              resourceType: "workflowExecution",
              resourceId: execution._id,
              metadata: {
                workflowId: execution.workflowId,
                escalationUserId: settings.escalationUserId,
                escalatedTaskCount: escalatedCount,
              },
            });
        }
      }
    }
  },
});
