/* eslint-disable max-lines */

import { createTemplate } from '../shared';

const createAgencyStudioTemplate = () => createTemplate({
    'page': { type: 'section', props: { path: '/', className: 'bg-stone-950 text-stone-100' }, children: ['wrap'] },
    'wrap': { type: 'div', props: { className: 'flex flex-col' }, children: ['nav', 'hero', 'work', 'services', 'process', 'quote', 'contact'] },

    'nav': { type: 'div', props: { className: 'max-w-6xl mx-auto w-full flex flex-row items-center justify-between px-8 py-6' }, children: ['brand', 'nav-links', 'nav-cta'] },
    'brand': { type: 'text', props: { tag: 'span', content: 'MONO / STUDIO', className: 'text-lg font-black tracking-[0.28em] text-stone-50' }, children: [] },
    'nav-links': { type: 'div', props: { className: 'hidden md:flex flex-row gap-6 text-sm text-stone-400' }, children: ['nav-1', 'nav-2', 'nav-3'] },
    'nav-1': { type: 'text', props: { tag: 'span', content: 'Work', className: 'hover:text-white cursor-pointer transition-colors' }, children: [] },
    'nav-2': { type: 'text', props: { tag: 'span', content: 'Services', className: 'hover:text-white cursor-pointer transition-colors' }, children: [] },
    'nav-3': { type: 'text', props: { tag: 'span', content: 'About', className: 'hover:text-white cursor-pointer transition-colors' }, children: [] },
    'nav-cta': { type: 'button', props: { text: 'Start a Project', variant: 'outline', className: 'border-stone-700 text-stone-100 hover:bg-stone-900' }, children: [] },

    'hero': { type: 'div', props: { className: 'px-8 pt-6 pb-20' }, children: ['hero-shell'] },
    'hero-shell': { type: 'div', props: { className: 'max-w-6xl mx-auto grid lg:grid-cols-[1.1fr_0.9fr] gap-10 items-end' }, children: ['hero-copy', 'hero-card'] },
    'hero-copy': { type: 'div', props: { className: 'flex flex-col gap-6' }, children: ['hero-kicker', 'hero-title', 'hero-body', 'hero-actions', 'hero-metrics'] },
    'hero-kicker': { type: 'text', props: { tag: 'span', content: 'Editorial systems for high-growth brands', className: 'text-xs uppercase tracking-[0.28em] text-amber-300' }, children: [] },
    'hero-title': { type: 'text', props: { tag: 'h1', content: 'We build brand worlds that feel expensive before the first word is read.', className: 'max-w-3xl text-5xl md:text-6xl font-black leading-[1.02] tracking-tight' }, children: [] },
    'hero-body': { type: 'text', props: { tag: 'p', content: 'Identity, launch sites, and campaign systems for companies that want sharper positioning and a web presence with actual point of view.', className: 'max-w-xl text-lg leading-8 text-stone-400' }, children: [] },
    'hero-actions': { type: 'div', props: { className: 'flex flex-row gap-4 flex-wrap' }, children: ['hero-primary', 'hero-secondary'] },
    'hero-primary': { type: 'button', props: { text: 'View Selected Work', size: 'lg', className: 'bg-stone-100 text-stone-950 hover:bg-white font-semibold px-8' }, children: [] },
    'hero-secondary': { type: 'button', props: { text: 'Read Our Process', variant: 'ghost', size: 'lg', className: 'text-stone-300 hover:text-white px-6' }, children: [] },
    'hero-metrics': { type: 'grid', props: { columns: '3', gap: 'sm', className: 'max-w-2xl pt-2' }, children: ['metric-1', 'metric-2', 'metric-3'] },
    'metric-1': { type: 'card', props: { title: '12 wks', description: 'Average full rebrand and launch cycle.', className: 'bg-stone-900 border border-stone-800 rounded-3xl p-5 h-full' }, children: [] },
    'metric-2': { type: 'card', props: { title: '4.9/5', description: 'Client NPS across retained design partners.', className: 'bg-stone-900 border border-stone-800 rounded-3xl p-5 h-full' }, children: [] },
    'metric-3': { type: 'card', props: { title: '22 launches', description: 'Shipped in the last 18 months across web and campaign.', className: 'bg-stone-900 border border-stone-800 rounded-3xl p-5 h-full' }, children: [] },
    'hero-card': { type: 'div', props: { className: 'rounded-[2rem] border border-stone-800 bg-stone-900/60 p-6 flex flex-col gap-5' }, children: ['hero-card-img', 'hero-card-meta'] },
    'hero-card-img': { type: 'image', props: { src: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80', alt: 'Creative studio project showcase', className: 'w-full rounded-[1.5rem] object-cover' }, children: [] },
    'hero-card-meta': { type: 'div', props: { className: 'grid grid-cols-2 gap-4' }, children: ['hero-meta-1', 'hero-meta-2'] },
    'hero-meta-1': { type: 'card', props: { title: 'Identity system', description: 'Naming, tone, visual language, campaign kit.', className: 'bg-stone-950 border border-stone-800 rounded-2xl p-4' }, children: [] },
    'hero-meta-2': { type: 'card', props: { title: 'Launch site', description: 'High-conviction web story with modular CMS handoff.', className: 'bg-stone-950 border border-stone-800 rounded-2xl p-4' }, children: [] },

    'work': { type: 'div', props: { className: 'px-8 py-20 border-t border-stone-900' }, children: ['work-inner'] },
    'work-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto flex flex-col gap-10' }, children: ['work-head', 'work-grid'] },
    'work-head': { type: 'div', props: { className: 'max-w-3xl flex flex-col gap-4' }, children: ['work-label', 'work-title', 'work-copy'] },
    'work-label': { type: 'text', props: { tag: 'span', content: 'Selected work', className: 'text-xs uppercase tracking-[0.24em] text-amber-300' }, children: [] },
    'work-title': { type: 'text', props: { tag: 'h2', content: 'Three different categories. One level of craft.', className: 'text-4xl font-black tracking-tight' }, children: [] },
    'work-copy': { type: 'text', props: { tag: 'p', content: 'We design every launch around a clear commercial story, not just a prettier set of screens.', className: 'text-lg text-stone-400 leading-8' }, children: [] },
    'work-grid': { type: 'grid', props: { columns: '3', gap: 'md', className: '' }, children: ['work-1', 'work-2', 'work-3'] },
    'work-1': { type: 'card', props: { title: 'Orbit Health', description: 'Positioning reset and waitlist launch that doubled qualified demos in 6 weeks.', imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=800&q=80', className: 'bg-stone-900 border border-stone-800 rounded-[2rem] overflow-hidden h-full' }, children: [] },
    'work-2': { type: 'card', props: { title: 'Luma Capital', description: 'Editorial identity and investor microsite for a fund with a stronger thesis voice.', imageUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=800&q=80', className: 'bg-stone-900 border border-stone-800 rounded-[2rem] overflow-hidden h-full' }, children: [] },
    'work-3': { type: 'card', props: { title: 'North Current', description: 'Commerce relaunch with richer storytelling and premium conversion surfaces.', imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80', className: 'bg-stone-900 border border-stone-800 rounded-[2rem] overflow-hidden h-full' }, children: [] },

    'services': { type: 'div', props: { className: 'px-8 py-20 bg-stone-900/50' }, children: ['services-inner'] },
    'services-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto grid lg:grid-cols-[0.8fr_1.2fr] gap-10 items-start' }, children: ['services-copy', 'services-grid'] },
    'services-copy': { type: 'div', props: { className: 'flex flex-col gap-4' }, children: ['services-label', 'services-title', 'services-body'] },
    'services-label': { type: 'text', props: { tag: 'span', content: 'Scope', className: 'text-xs uppercase tracking-[0.24em] text-amber-300' }, children: [] },
    'services-title': { type: 'text', props: { tag: 'h2', content: 'Strategy, design, and launch operations under one roof.', className: 'text-4xl font-black tracking-tight' }, children: [] },
    'services-body': { type: 'text', props: { tag: 'p', content: 'You get one partner from narrative architecture through rollout, with a system that your internal team can actually maintain after launch.', className: 'text-lg text-stone-400 leading-8' }, children: [] },
    'services-grid': { type: 'grid', props: { columns: '2', gap: 'md', className: '' }, children: ['service-1', 'service-2', 'service-3', 'service-4'] },
    'service-1': { type: 'card', props: { title: 'Brand direction', description: 'Messaging architecture, naming, visual system, rollout toolkits.', className: 'bg-stone-950 border border-stone-800 rounded-[2rem] p-6 h-full' }, children: [] },
    'service-2': { type: 'card', props: { title: 'Launch sites', description: 'Narrative-driven marketing sites with modular content systems.', className: 'bg-stone-950 border border-stone-800 rounded-[2rem] p-6 h-full' }, children: [] },
    'service-3': { type: 'card', props: { title: 'Campaign systems', description: 'Landing pages, paid media kits, events, investor updates, social rollout.', className: 'bg-stone-950 border border-stone-800 rounded-[2rem] p-6 h-full' }, children: [] },
    'service-4': { type: 'card', props: { title: 'Internal enablement', description: 'Figma and CMS handoff, governance docs, launch operations with your team.', className: 'bg-stone-950 border border-stone-800 rounded-[2rem] p-6 h-full' }, children: [] },

    'process': { type: 'div', props: { className: 'px-8 py-20 border-t border-stone-900' }, children: ['process-inner'] },
    'process-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto flex flex-col gap-8' }, children: ['process-title', 'process-grid'] },
    'process-title': { type: 'text', props: { tag: 'h2', content: 'A process built for fast alignment, not endless rounds.', className: 'text-3xl font-black tracking-tight' }, children: [] },
    'process-grid': { type: 'grid', props: { columns: '4', gap: 'sm', className: '' }, children: ['step-1', 'step-2', 'step-3', 'step-4'] },
    'step-1': { type: 'card', props: { title: '01 Audit', description: 'Find the positioning gap and the story competitors cannot claim.', className: 'bg-stone-900 border border-stone-800 rounded-[1.75rem] p-5 h-full' }, children: [] },
    'step-2': { type: 'card', props: { title: '02 Direction', description: 'Establish voice, visual gravity, and the primary conversion arc.', className: 'bg-stone-900 border border-stone-800 rounded-[1.75rem] p-5 h-full' }, children: [] },
    'step-3': { type: 'card', props: { title: '03 Build', description: 'Translate the concept into web, campaign, and launch surfaces.', className: 'bg-stone-900 border border-stone-800 rounded-[1.75rem] p-5 h-full' }, children: [] },
    'step-4': { type: 'card', props: { title: '04 Rollout', description: 'Ship with internal docs, content handoff, and launch sequencing.', className: 'bg-stone-900 border border-stone-800 rounded-[1.75rem] p-5 h-full' }, children: [] },

    'quote': { type: 'div', props: { className: 'px-8 py-20 bg-amber-100 text-stone-950' }, children: ['quote-inner'] },
    'quote-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto grid lg:grid-cols-[1.2fr_0.8fr] gap-8 items-start' }, children: ['quote-copy', 'quote-metric'] },
    'quote-copy': { type: 'div', props: { className: 'flex flex-col gap-4' }, children: ['quote-mark', 'quote-body', 'quote-author'] },
    'quote-mark': { type: 'text', props: { tag: 'span', content: 'Client note', className: 'text-xs uppercase tracking-[0.24em] text-stone-700' }, children: [] },
    'quote-body': { type: 'text', props: { tag: 'p', content: '"Mono gave us a brand presence that finally matched the confidence of the product. The launch site felt like a new category, not a template."', className: 'text-3xl leading-[1.35] font-semibold' }, children: [] },
    'quote-author': { type: 'text', props: { tag: 'p', content: 'Arman K., Founder at Arcwell', className: 'text-sm text-stone-700' }, children: [] },
    'quote-metric': { type: 'card', props: { title: '+41%', description: 'Increase in qualified inbound after the relaunch went live.', className: 'bg-stone-950 text-stone-100 rounded-[2rem] p-8 h-full border-0' }, children: [] },

    'contact': { type: 'div', props: { className: 'px-8 py-24' }, children: ['contact-inner'] },
    'contact-inner': { type: 'div', props: { className: 'max-w-6xl mx-auto rounded-[2.5rem] border border-stone-800 bg-stone-900 p-10 md:p-14 flex flex-col md:flex-row gap-8 justify-between items-start md:items-center' }, children: ['contact-copy', 'contact-button'] },
    'contact-copy': { type: 'div', props: { className: 'max-w-2xl flex flex-col gap-4' }, children: ['contact-title', 'contact-body'] },
    'contact-title': { type: 'text', props: { tag: 'h2', content: 'If your launch needs a stronger point of view, we should talk.', className: 'text-4xl font-black tracking-tight' }, children: [] },
    'contact-body': { type: 'text', props: { tag: 'p', content: 'Limited to a small number of retained projects each quarter so the work stays sharp and senior-led.', className: 'text-lg text-stone-400 leading-8' }, children: [] },
    'contact-button': { type: 'button', props: { text: 'Schedule Intro Call', size: 'lg', className: 'bg-stone-100 text-stone-950 hover:bg-white font-semibold px-8' }, children: [] },
  });

export default createAgencyStudioTemplate;
