/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-preview-registry.ts
 * Source of truth: feature preview modules under frontend/slices and frontend/shared/settings
 *
 * Lazy loader — single-feature dynamic import + module-scoped cache.
 * Use this from any consumer surface that needs to render exactly one preview
 * (mock-dashboard, MenuStorePage preview pane, WorkspaceStorePage preview pane).
 *
 * To update this file, add or update preview definitions and run:
 *   pnpm run sync:all
 */

import type { FeaturePreviewDefinition } from "./types"

type PreviewImporter = () => Promise<{ default: FeaturePreviewDefinition }>

const PREVIEW_IMPORTERS: Record<string, PreviewImporter> = {
  "communications": () => import("@/frontend/slices/communications/features-preview/index"),
  "overview": () => import("@/frontend/slices/overview/features-preview/index"),
  "status": () => import("@/frontend/slices/status/features-preview/index"),
  "ai": () => import("@/frontend/slices/ai/features-preview/index"),
  "contacts": () => import("@/frontend/slices/contacts/features-preview/index"),
  "knowledge": () => import("@/frontend/slices/knowledge/features-preview/index"),
  "workspace-store": () => import("@/frontend/slices/workspace-store/features-preview/index"),
  "database": () => import("@/frontend/slices/database/features-preview/index"),
  "documents": () => import("@/frontend/slices/documents/features-preview/index"),
  "calendar": () => import("@/frontend/slices/calendar/features-preview/index"),
  "menus": () => import("@/frontend/slices/menus/features-preview/index"),
  "reports": () => import("@/frontend/slices/reports/features-preview/index"),
  "user-management": () => import("@/frontend/slices/user-management/features-preview/index"),
  "forms": () => import("@/frontend/slices/forms/features-preview/index"),
  "tasks": () => import("@/frontend/slices/tasks/features-preview/index"),
  "approvals": () => import("@/frontend/slices/approvals/features-preview/index"),
  "support": () => import("@/frontend/slices/support/features-preview/index"),
  "audit-log": () => import("@/frontend/slices/audit-log/features-preview/index"),
  "projects": () => import("@/frontend/slices/projects/features-preview/index"),
  "import-export": () => import("@/frontend/slices/import-export/features-preview/index"),
  "integrations": () => import("@/frontend/slices/integrations/features-preview/index"),
  "pos": () => import("@/frontend/slices/pos/features-preview/index"),
  "analytics": () => import("@/frontend/slices/analytics/features-preview/index"),
  "marketing": () => import("@/frontend/slices/marketing/features-preview/index"),
  "studio": () => import("@/frontend/slices/studio/features-preview/index"),
  "bi": () => import("@/frontend/slices/bi/features-preview/index"),
  "sales": () => import("@/frontend/slices/sales/features-preview/index"),
  "guest-booking": () => import("@/frontend/slices/guest-booking/features-preview/index"),
  "staff-operations": () => import("@/frontend/slices/staff-operations/features-preview/index"),
  "owner-analytics": () => import("@/frontend/slices/owner-analytics/features-preview/index"),
  "industry-templates": () => import("@/frontend/slices/industry-templates/features-preview/index"),
  "accounting": () => import("@/frontend/slices/accounting/features-preview/index"),
  "asset-management": () => import("@/frontend/slices/asset-management/features-preview/index"),
  "branch-health-scoring": () => import("@/frontend/slices/branch-health-scoring/features-preview/index"),
  "cash-flow-forecast": () => import("@/frontend/slices/cash-flow-forecast/features-preview/index"),
  "cms-lite": () => import("@/frontend/slices/cms-lite/features-preview/index"),
  "content": () => import("@/frontend/slices/content/features-preview/index"),
  "customer-loyalty": () => import("@/frontend/slices/customer-loyalty/features-preview/index"),
  "daily-closing": () => import("@/frontend/slices/daily-closing/features-preview/index"),
  "damage-reports": () => import("@/frontend/slices/damage-reports/features-preview/index"),
  "hr": () => import("@/frontend/slices/hr/features-preview/index"),
  "kpi-thresholds": () => import("@/frontend/slices/kpi-thresholds/features-preview/index"),
  "maintenance-scheduling": () => import("@/frontend/slices/maintenance-scheduling/features-preview/index"),
  "operational-checklist": () => import("@/frontend/slices/operational-checklist/features-preview/index"),
  "owner-transfers": () => import("@/frontend/slices/owner-transfers/features-preview/index"),
  "petty-cash": () => import("@/frontend/slices/petty-cash/features-preview/index"),
  "inventory": () => import("@/frontend/slices/inventory/features-preview/index"),
  "crm": () => import("@/frontend/slices/crm/features-preview/index"),
  "example": () => import("@/frontend/slices/example/features-preview/index"),
  "platform-admin": () => import("@/frontend/slices/platform-admin/features-preview/index"),
  "user-settings": () => import("@/frontend/shared/settings/user-settings/features-preview/index"),
}

const cache = new Map<string, FeaturePreviewDefinition>()

export async function loadSinglePreview(featureId: string): Promise<FeaturePreviewDefinition | null> {
  const cached = cache.get(featureId)
  if (cached) return cached

  const importer = PREVIEW_IMPORTERS[featureId]
  if (!importer) return null

  const mod = await importer()
  const preview = mod.default
  if (preview) cache.set(featureId, preview)
  return preview ?? null
}

export function hasSinglePreview(featureId: string): boolean {
  return featureId in PREVIEW_IMPORTERS
}

export function listPreviewIds(): string[] {
  return Object.keys(PREVIEW_IMPORTERS)
}
