/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-preview-registry.ts
 * Source of truth: feature preview modules under frontend/slices and frontend/shared/settings
 *
 * Lazy loader — single-feature dynamic import + module-scoped cache.
 * Use this from any consumer surface that needs to render exactly one preview
 * (mock-dashboard, MenuStorePage preview pane, WorkspaceStorePage preview pane).
 *
 * To update this file, add or update preview definitions and run:
 *   pnpm run sync:all
 */

import type { FeaturePreviewDefinition } from "./types"

type PreviewImporter = () => Promise<{ default: FeaturePreviewDefinition }>

const PREVIEW_IMPORTERS: Record<string, PreviewImporter> = {
  "studio": () => import("@/frontend/slices/studio/features-preview/index"),
  "example": () => import("@/frontend/slices/example/features-preview/index"),
  "user-settings": () => import("@/frontend/shared/settings/user-settings/features-preview/index"),
}

const cache = new Map<string, FeaturePreviewDefinition>()

export async function loadSinglePreview(featureId: string): Promise<FeaturePreviewDefinition | null> {
  const cached = cache.get(featureId)
  if (cached) return cached

  const importer = PREVIEW_IMPORTERS[featureId]
  if (!importer) return null

  const mod = await importer()
  const preview = mod.default
  if (preview) cache.set(featureId, preview)
  return preview ?? null
}

export function hasSinglePreview(featureId: string): boolean {
  return featureId in PREVIEW_IMPORTERS
}

export function listPreviewIds(): string[] {
  return Object.keys(PREVIEW_IMPORTERS)
}
